namespace = "monitoring"
prometheus_container_image = "drjetf/prometheus:v1.0.0"
alertmanager_container_image = "drjetf/alertmanager:0.21.0"
pushgateway_container_image = "drjetf/pushgateway:1.3.0"
grafana_container_image = "drjetf/grafana:7.3.3"
postgres_container_image = "drjetf/postgres:13"
nginx_container_image = "nginx"
