[[servers]]
host = "${ grafana_ldap_host }"
port = 636
use_ssl = true
start_tls = false
ssl_skip_verify = true
client_cert = "/etc/grafana/ldap/u_grafana.pem"
client_key = "/etc/grafana/ldap/u_grafana.key"
#root_ca_cert= ""
bind_dn = "uid=u_grafana,cn=users,cn=accounts,${ grafana_ldap_bind_suffix }"
bind_password = "${ grafana_ldap_bind_password }"
search_filter = "(uid=%s)"
search_base_dns = ["cn=users,cn=accounts,${ grafana_ldap_bind_suffix }"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
group_dn = "cn=g_grafana_admins,cn=groups,cn=accounts,${ grafana_ldap_bind_suffix }"
org_role = "Admin"
org_id = 1

[[servers.group_mappings]]
group_dn = "cn=g_grafana_editors,cn=groups,cn=accounts,${ grafana_ldap_bind_suffix }"
org_role = "Editor"
org_id = 1

[[servers.group_mappings]]
group_dn = "cn=ipausers,cn=groups,cn=accounts,${ grafana_ldap_bind_suffix }"
org_role = "Viewer"
org_id = 1
