apiVersion: 1

datasources:
- name: thanos-query-frontend
  type: prometheus
  access: proxy
  orgId: 1
  url: http://${ thanos_query_frontend_name }:${ prometheus_container_port }
  version: 1
  isDefault: true
  editable: false
  jsonData:
    timeInterval: '60s'
- name: prometheus-os
  type: prometheus
  access: proxy
  orgId: 1
  url: '${ prometheus_os_host }'
  basicAuth: true
  basicAuthUser: '${ prometheus_os_user }'
  secureJsonData:
    basicAuthPassword: '${ prometheus_os_password }'
  version: 1
  isDefault: false
  editable: false
  jsonData:
    timeInterval: '60s'
    tlsSkipVerify: true
- name: prometheus-pg
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus-pg:${ prometheus_container_port }
  version: 1
  isDefault: false
  editable: false
  jsonData:
    timeInterval: '300s'

- name: es
  type: elasticsearch
  access: proxy
  orgId: 1
  url: ${ elasticsearch_url }
  database: "logs*"
  version: 1
  isDefault: false
  editable: false
  jsonData:
    timeField: '@timestamp'
    esVersion: 60
    timeInterval: '60s'
    tlsSkipVerify: true
