{
 "title": "[SERVICE] YARN WF-1-6-0",
 "tags": [
  "service",
  "yarn",
  "wf"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "5m,10m,15m,30m,1h" },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   { "name": "service", "query": "label_values(service)" },
   {
    "name": "instance",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   },
   {
    "name": "q0",
    "query": "label_values(hadoop_yarn_jmx_allocated_vcores{},q0)"
   },
   {
    "name": "q1",
    "query": "label_values(hadoop_yarn_app_state{q0=~\"$q0\",wf_name=~\".+\"},q1)"
   },
   {
    "name": "q2",
    "query": "label_values(hadoop_yarn_app_state{q0=~\"$q0\",q1=~\"$q1\",wf_name=~\".+\"},q2)"
   },
   {
    "name": "wf_name_old",
    "label": "wf_name",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"},wf_name)"
   },
   {
    "name": "name",
    "label": "name",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"},wf_name)"
   },
   {
    "name": "finalStatus",
    "label": "finalStatus",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\"},finalStatus)"
   },
   { "name": "metrics", "query": "metrics(^hadoop_yarn_app_)" },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   {
    "name": "alert_group",
    "query": "label_values(ALERTS_FOR_STATE,alert_group)"
   },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{alert_group=~\"$alert_group\",},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   { "name": "threshold_cores", "query": "-1,0,1,2,5,10,50,100" },
   { "name": "threshold_mem", "label": "threshold_mem GB", "query": "-1,0,1,2,5,10,20,50,100,500" },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" }
  ]
 },
 "panels": [
  { "title": "app summary, q1=$q1", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "q1=[  $q1  ] allocateted mb, finalStatus=$finalStatus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(hadoop_yarn_app_allocatedmb{finalStatus=~\"$finalStatus\",q0=~\"$q0\",q1=~\"$q1\"}) by (system)",
     "legendFormat": "allocated mb sum"
    }
   ]
  },
  {
   "title": "q1=[  $q1  ] vcores & containers finalStatus=$finalStatus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hadoop_yarn_app_allocatedvcores{finalStatus=~\"$finalStatus\",q0=~\"$q0\",q1=~\"$q1\"}) by (system,q1)",
     "legendFormat": " allocated vcores sum"
    },
    {
     "expr": "sum(hadoop_yarn_app_runningcontainers{finalStatus=~\"$finalStatus\",q0=~\"$q0\",q1=~\"$q1\"}) by (system,q1)",
     "legendFormat": "running containers"
    }
   ]
  },
  {
   "title": "q1=$q1, name=$name, allocateted mb, finalStatus=$finalStatus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(hadoop_yarn_app_allocatedmb{name=~\"$name\",finalStatus=~\"$finalStatus\",q0=~\"$q0\",q1=~\"$q1\"}) by (name,q1)",
     "legendFormat": "{{ name }} allocated mb sum"
    }
   ]
  },
  {
   "title": "name=[  $name  ] vcores & containers finalStatus=$finalStatus",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hadoop_yarn_app_allocatedvcores{name=~\"$name\",finalStatus=~\"$finalStatus\",q0=~\"$q0\",q1=~\"$q1\"}) by (system,q1,name)",
     "legendFormat": " {{ name }} allocated vcores sum"
    },
    {
     "expr": "sum(hadoop_yarn_app_runningcontainers{name=~\"$name\",finalStatus=~\"$finalStatus\",q0=~\"$q0\",q1=~\"$q1\"}) by (system,q1,name)",
     "legendFormat": " {{ name }} running containers"
    }
   ]
  },
  {
   "title": "q1=[  $q1  ] stages",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max_over_time(max(hadoop_yarn_app_startedtime{q1=~\"$q1\",finalStatus=~\"$finalStatus\"}) by (name,q1)[$__range:])"
    },
    {
     "expr": "max_over_time(max(hadoop_yarn_app_finishedtime{q1=~\"$q1\",finalStatus=~\"$finalStatus\"}>0) by (name,q1)[$__range:])"
    },
    {
     "expr": "max_over_time(max(hadoop_yarn_app_elapsedtime{name=~\".*$wf_name.*\",finalStatus=~\"$finalStatus\"}) by (name,q1)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_allocatedmb{q1=~\"$q1\",finalStatus=~\"$finalStatus\"}>-1) by(name,q1)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_allocatedvcores{q1=~\"$q1\",finalStatus=~\"$finalStatus\"}>-1) by(name,q1)[$__range:])"
    },
    {
     "expr": "max_over_time (max(hadoop_yarn_app_finalstatus{q1=~\"$q1\",finalStatus=~\"$finalStatus\"}) by(name,q1)[$__range:])"
    }
   ]
  },
  {
   "title": "name=$name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "name",
   "collapsed": true,
   "panels": [
    {
     "title": "name=[ $name ] allocateted mb",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedmb{name=\"$name\"}) by (q1,name)",
       "legendFormat": "allocated mb sum"
      }
     ]
    },
    {
     "title": "name=[$name] vcores & containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedvcores{name=\"$name\"}) by (q1,name)",
       "legendFormat": " allocated vcores sum"
      },
      {
       "expr": "sum(hadoop_yarn_app_runningcontainers{name=\"$name\"}) by (q1,name)",
       "legendFormat": "running containers"
      }
     ]
    },
    {
     "title": "name=[$name]  state",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max(hadoop_yarn_app_state{name=\"$name\"}) by (q1,name)",
       "legendFormat": "state"
      }
     ]
    }
   ]
  },
  {
   "title": "raw metrics $name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "name",
   "collapsed": true,
   "panels": [
    {
     "title": "$metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "$metrics{name=~\"$name\"}"
      }
     ]
    }
   ]
  }
 ]
}