{
 "title": "[SERVICE] YARN WF",
 "tags": [
  "service",
  "yarn",
  "wf"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "5m,10m,15m,30m,1h" },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   { "name": "service", "query": "label_values(service)" },
   {
    "name": "instance",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   },
   {
    "name": "q0",
    "query": "label_values(hadoop_yarn_jmx_allocated_vcores{},q0)"
   },
   {
    "name": "q1",
    "query": "label_values(hadoop_yarn_app_state{q0=~\"$q0\",wf_name=~\".+\"},q1)"
   },
   {
    "name": "q2",
    "query": "label_values(hadoop_yarn_jmx_allocated_vcores{q0=~\"$q0\",q1=~\"$q1\"},q2)"
   },
   {
    "name": "name",
    "label": "name",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"},wf_name)"
   },
   {
    "name": "stage",
    "label": "stage",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"},stage)"
   },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   { "name": "threshold_cores", "query": "-1,0,1,2,5,10,50,100" },
   { "name": "threshold_mem", "label": "threshold_mem GB", "query": "-1,0,1,2,5,10,20,50,100,500" },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" }
  ]
 },
 "panels": [
  { "title": "APPs summary, q1=$q1 q2=$q2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "APPs q1=[  $q1  ] q2=[  $q2 ] allocateted mb",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"}) by (system,q1,q2)",
     "legendFormat": "allocated mb sum"
    }
   ]
  },
  {
   "title": "APPs q1=[  $q1  ] q2=[ $q2 ] vcores & containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hadoop_yarn_app_allocatedvcores{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"}) by (system,q1,q2)",
     "legendFormat": " allocated vcores sum"
    },
    {
     "expr": "sum(hadoop_yarn_app_runningcontainers{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"}) by (system,q1,q2)",
     "legendFormat": "running containers"
    }
   ]
  },
  {
   "title": "APPs q1=[  $q1  ] q2=[ $q2 ] last stages",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max_over_time(max(hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"q1\",q2=~\"$q2\",q2=~\"$q2\"}) by (name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}>-1) by(name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_allocatedvcores{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}>-1) by(name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}) by(name,stage,q1,q2)[$__range:])"
    }
   ]
  },
  {
   "title": "WFs summary q1=$q1 q2=$q2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "WF q1=[  $q1  ] q2=[ $q2 ] last stages",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "max_over_time(max(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}) by (name,stage,q1,q2)[$__range:])"
      },
      {
       "expr": "max_over_time(max(hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}>0) by (name,stage,q1,q2)[$__range:])"
      },
      {
       "expr": "max_over_time(max(hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"q1\",q2=~\"$q2\",q2=~\"$q2\",wf_name=~\".+\"}) by (name,stage,q1,q2)[$__range:])"
      },
      {
       "expr": "max_over_time (sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}>-1) by(name,stage,q1,q2)[$__range:])"
      },
      {
       "expr": "max_over_time (sum(hadoop_yarn_app_allocatedvcores{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}>-1) by(name,stage,q1,q2)[$__range:])"
      },
      {
       "expr": "max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}) by(name,stage,q1,q2)[$__range:])"
      }
     ]
    },
    {
     "title": "APPs q1=[  $q1  ] q2=[  $q2 ] allocateted mb >$threshold_mem GB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}) by (system,q1,q2)",
       "legendFormat": "allocated mb sum"
      }
     ]
    },
    {
     "title": "APPs q1=[  $q1  ] q2=[ $q2 ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedvcores{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}) by (system,q1,q2)",
       "legendFormat": " allocated vcores sum q1={{ q1 }} q2={{ q2 }}"
      },
      {
       "expr": "sum(hadoop_yarn_app_runningcontainers{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}) by (system,q1,q2)",
       "legendFormat": "running containers  q1={{ q1 }} q2={{ q2 }}"
      }
     ]
    }
   ]
  },
  {
   "title": "WFs detailed q1=$q1 q2=$q2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "APPs q1=[  $q1  ] q2=[  $q2 ] allocateted mb >$threshold_mem GB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}>$threshold_mem*1024) by (system,q1,q2,name)",
       "legendFormat": "allocated mb sum {{ name }}"
      }
     ]
    },
    {
     "title": "APPs q1=[  $q1  ] q2=[ $q2 ] vcores >$threshold_cores",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedvcores{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}>$threshold_cores) by (system,q1,q2,name)",
       "legendFormat": " allocated vcores sum {{ name }}"
      }
     ]
    },
    {
     "title": "APPs q1=[  $q1  ] q2=[ $q2 ] vcores & containers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_runningcontainers{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}) by (system,q1,q2,name)",
       "legendFormat": "running containers {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "name=$name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "repeat": "name",
   "collapsed": true,
   "panels": [
    {
     "title": "WF q1=[  $q1  ] q2=[ $q2 ] stages",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "max_over_time(max(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=\"$name\"}) by (name,stage,q1,q2)[$__range:])"
      },
      {
       "expr": "max_over_time(max(hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=\"$name\"}>0) by (name,stage,q1,q2)[$__range:])"
      },
      {
       "expr": "max_over_time(max(hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"q1\",q2=~\"$q2\",q2=~\"$q2\",name=\"$name\"}) by (name,stage,q1,q2)[$__range:])"
      },
      {
       "expr": "max_over_time (sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=\"$name\"}>-1) by(name,stage,q1,q2)[$__range:])"
      },
      {
       "expr": "max_over_time (sum(hadoop_yarn_app_allocatedvcores{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=\"$name\"}>-1) by(name,stage,q1,q2)[$__range:])"
      },
      {
       "expr": "max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=\"$name\"}) by(name,stage,q1,q2)[$__range:])"
      }
     ]
    },
    {
     "title": "name=[ $name ] allocateted mb",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedmb{name=\"$name\"}) by (q1,name)",
       "legendFormat": "allocated mb sum"
      }
     ]
    },
    {
     "title": "name=[$name] vcores & containers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedvcores{name=\"$name\"}) by (q1,name)",
       "legendFormat": " allocated vcores sum"
      },
      {
       "expr": "sum(hadoop_yarn_app_runningcontainers{name=\"$name\"}) by (q1,name)",
       "legendFormat": "running containers"
      }
     ]
    },
    {
     "title": "name=[$name]  state( RUNNING - 5, FINISHED - 6, FAILED - 7)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max(hadoop_yarn_app_state{name=\"$name\"}) by (q1,name)",
       "legendFormat": "state"
      }
     ]
    }
   ]
  }
 ]
}