{
 "title": "[SERVICE] Greenplum",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" },
   { "name": "service", "query": "label_values(service)" },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   {
    "name": "instance",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   },
   {
    "name": "datname",
    "query": "label_values(pgsql_database_size{system=~\"$system\",service=~\"$service\"},datname)"
   },
   {
    "name": "state",
    "query": "label_values(pgsql_count_session{system=~\"$system\",service=~\"$service\"},state)"
   },
   {
    "name": "parameter",
    "query": "label_values(pgsql_segments{system=~\"$system\",service=~\"$service\"},parameter)"
   },
   {
    "name": "gp_segment_id",
    "query": "label_values(pgsql_warn_percentage{system=~\"$system\",service=~\"$service\"},gp_segment_id)"
   },
   {
    "name": "mode",
    "query": "label_values(pgsql_count_locks_this_state{system=~\"$system\",service=~\"$service\"},mode)"
   },
   {
    "name": "message",
    "query": "label_values(pgsql_age{system=~\"$system\",service=~\"$service\"},message)"
   },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   {
    "name": "alert_group",
    "query": "label_values(ALERTS_FOR_STATE,alert_group)"
   },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{alert_group=~\"$alert_group\",},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" },
   {
    "name": "regexp",
    "label": "regexp for FQDN",
    "query": "([a-zA-Z0-9]+-[a-zA-Z0-9]+)[.].+ , (.+)"
   },
   {
    "name": "mountpoint",
    "label": "mountpoint !=",
    "query": "label_values({system=~\"$system\",instance=~\"$instance_list\",fstype=~\"ext4|xfs\"},mountpoint)"
   },
   { "name": "metrics", "label": "raw metric", "query": "metrics(^hadoop_$service)" },
   {
    "name": "instance_list",
    "query": "label_values({system=~\"$system\",service=~\"$service\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Readme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Описание",
     "type": "text",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
     "content": "\n## Описание дашборда\n\nДанный дашборд отображает основные метрики собираемые с greenplum посредством\n- exporter-node\n- exporter-sql-select\n\nБлоки Summary содержат информацию о всех инстансах сервиса. Остальные блоки фильтруют информацию по полю instance\n\n#### переменные\n- ds - выбор датасорса(prometheus) из которого запрашивать данные для отображения(подробнее про типы прометеусов см https://confluence.ca.sbrf.ru/pages/editpage.action?pageId=2383122863)\n- system - имя системы\n- quantile - значение персентия для расчета значений в таблицах\n- last - период вермени отображения метрик для таблиц(чтобы не делать тяжелые расчеты на больших выборках)\n- regexp for FQDN - regexp для отсекания FQDN имен на графиках (экономия используемого места дашборда)\n- ountpoint != список точек монтирования, которые НЕ интересны для мониторинга(не учитывать в TopK селектах по утилизации файловых систем)\n- raw metric - выбрать метрику для отображения ее в \"сыром\" виде в блоке RAW METRICS (возможность для пользователя посмотрить метрки данного сервиса отсутствующие на дашборде, аналогичный функционал в меню графаны EXPLORE\n\n\n#### drill down links\n- из таблиц возможен переход по имени инстанса на более подробный дашборд по выбранному инстансу\n\n\n\n\n"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Readme",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
     "content": "Данный блок должен содержать виджеты по ключевым метрикам сервиса.\nКлючивые метрики определяет разработчик/админ сервиса.\n\nКлючевыми метриками могут быть как стандартные метрики ОС или Java, так и кастомные метрики сервиса(кол-во ошибок, задержки, статус и т.д.)\n\nКрайне желательно определить метрику определяющую общий статус сервиса.\n\n"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Greenplum metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Readme",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "content": "Данный блок содержит наиболее важные кастомные метрики сервиса.\nВажные метрики метрики определяет разработчик/админ сервиса\nДанный блок можно разбить на несколько если метрик много\n\n"
  },
  {
   "title": "primary segments is up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(pgsql_segments{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",parameter=~\"primary segments is up\"})"
    }
   ]
  },
  {
   "title": "mirror segments is up",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(pgsql_segments{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",parameter=~\"mirror segments is up\"})"
    }
   ]
  },
  {
   "title": "$datname base table",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "quantile_over_time ($quantile,(max(pgsql_database_size{system=~\"$system\",service=~\"$service\",datname=~\"$datname\"}) by (system,service,instance,datname))[$__range:])"
    }
   ]
  },
  {
   "title": "primary segments is down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(pgsql_segments{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",parameter=~\"primary segments is down\"})"
    }
   ]
  },
  {
   "title": "mirror as primary segments",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(pgsql_segments{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",parameter=~\"mirror as primary segments\"})"
    }
   ]
  },
  {
   "title": "mirror segments is down",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(pgsql_segments{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",parameter=~\"mirror segments is down\"})"
    }
   ]
  },
  {
   "title": "pgsql_count_locks_this_state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max(rate(pgsql_count_locks_this_state{system=~\"$system\",service=~\"$service\",datname=~\"$datname\",mode=~\"$mode\"}[5m])) by (service,instance,datname,mode))",
     "legendFormat": "{{datname}} {{mode}}"
    }
   ]
  },
  {
   "title": "pgsql_warn_percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(max(pgsql_warn_percentage{system=~\"$system\",service=~\"$service\",datname=~\"$datname\",gp_segment_id=~\"$gp_segment_id\",message=~\"$message\"}) by (service,instance,datname,message))",
     "legendFormat": "{{datname}} {{state}}"
    }
   ]
  },
  {
   "title": "pgsql_count_session",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace((irate(pgsql_count_session{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",datname=~\"$datname\",state=~\"$state\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{datname}} {{state}}"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU%",
     "type": "singlestat",
     "description": "$service -  avg Host system CPU% Utilization over all hosts",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 28 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"idle\",}[$interval])) by(system,instance)) by (system,service)"
      }
     ]
    },
    {
     "title": "CPU% User",
     "type": "singlestat",
     "description": "$service -  avg Host system CPU% user Utilization over all hosts",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 28 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"user\"}[$interval]))"
      }
     ]
    },
    {
     "title": "CPU% iowait",
     "type": "gauge",
     "description": "$service -  max Host system CPU% iowait Utilization over all hosts",
     "gridPos": { "h": 6, "w": 2, "x": 6, "y": 28 },
     "targets": [
      {
       "expr": "max_over_time (max(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"iowait\"}[$interval]))[$__range:])",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Cores Total",
     "type": "singlestat",
     "description": "$service -  Summary Cores count",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{system=~\"$system\", instance=~\"$instance_list\",}) by (cpu,system,instance)) by(system,service)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Mem Total",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 28 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}))"
      }
     ]
    },
    {
     "title": "disk util max read_time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 28 },
     "format": "s",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))",
       "legendFormat": "read"
      }
     ]
    },
    {
     "title": "Top Usage FS",
     "type": "table",
     "description": "Top  most usage File Systems over all hosts\n\nmountpoint  != variable: $mountpoint",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 28 },
     "targets": [
      {
       "expr": "label_replace( topk(5,max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by (instance,mountpoint)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Mem Free Total",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 30 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"}))"
      }
     ]
    },
    {
     "title": "CPU% System",
     "type": "singlestat",
     "description": "$service -  avg Host system CPU%  system Utilization over all hosts",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 31 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg (rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"system\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Nodes Count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 31 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_exporter_build_info{system=~\"$system\", instance=~\"$instance_list\",})"
      }
     ]
    },
    {
     "title": "disk util max write_time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 31 },
     "format": "s",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))",
       "legendFormat": "write "
      }
     ]
    },
    {
     "title": "Mem%",
     "type": "singlestat",
     "description": "$service -  avg Host system Mem% Utilization over all hosts",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 32 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} \n- (node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"} +\nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"})) / \nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})"
      }
     ]
    },
    {
     "title": "System:[  $system  ] Service:[  $service  ] OS metrics, quantile=$quantile ",
     "type": "table",
     "description": "OS metrics summary table for last $last.\n\nAggregation(quanlile/max/last)  values during last $last\n\nJava/Heap/Pool - means Java application(service) metrics.\n\nYou can change colors threatholds as you wish\n\n",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": " (min(up{system=~\"$system\", instance=~\"$instance_list\", roletype!~\".+\"}) by (system,instance))"
      },
      {
       "expr": "(min(node_boot_time_seconds{system=~\"$system\", instance=~\"$instance_list\", }) by (system,instance))"
      },
      {
       "expr": "count(count(node_cpu_seconds_total{system=~\"$system\", instance=~\"$instance_list\",}) by (cpu,system,instance)) by(system,instance)"
      },
      {
       "expr": "quantile_over_time ($quantile,max(node_load5{system=~\"$system\", instance=~\"$instance_list\",}) by(system,service,instance)[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"idle\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"system\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"user\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"iowait\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"irq\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"softirq\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "max(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by(system,instance)"
      },
      {
       "expr": "max(((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"})) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by(system,instance)"
      },
      {
       "expr": "max_over_time(max by(system,instance) (rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))[$__range:])"
      },
      {
       "expr": "max_over_time(max by(system,instance) (rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))[$__range:])"
      },
      {
       "expr": "(max(node_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by (system,service,instance))"
      },
      {
       "expr": "max (1 - (node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} / on(system,instance)\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by (system,instance)"
      },
      {
       "expr": "sum(irate(node_network_receive_bytes_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))by (system,instance)"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))by (system,instance)"
      },
      {
       "expr": "max((node_netstat_Tcp_CurrEstab{system=~\"$system\",instance=~\"$instance_list\"}))by (system,instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes CPU  - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization % Host Systems ",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"idle\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 1m Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load1{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 5m Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load5{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 15m Host Systems ",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load15{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  System %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"system\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  User %  ]  Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"user\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  IOWait %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"iowait\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Memory - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization% Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\ncurrent formula\n(node_memory_MemTotal_bytes-node_memory_MemFree_bytes-node_memory_Cached_bytes-node_memory_Buffers_bytes ) /\nnode_memory_MemTotal_bytes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Available %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Free %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory Utilization GB Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Available GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Free GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Cached %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Cached GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Buffers %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Buffers GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "[  SWAP Utilization %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max (1 - (node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance\"} / on(system,instance)\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "[  SWAP Utilization GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace( max(\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance\"}-node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance\"}) by (system,instance) , \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Disk & Network - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read/write time seconds",
     "type": "graph",
     "description": "read - negative  Y\nwrite - positive Y",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      {
       "format": "s",
       "label": "disr read s (-) / disk write s (+)"
      }
     ],
     "targets": [
      {
       "expr": "label_replace(sum by(system,instance) (rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-read"
      },
      {
       "expr": "label_replace(sum by(system,instance) (rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-write"
      }
     ]
    },
    {
     "title": "Disk IOps ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_disk_reads_completed_total{system=~\"$system\",instance=~\"$instance\",device=~\"[a-z]*[a-z]\"}[$interval])) by (service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-read"
      },
      {
       "expr": "label_replace(sum(irate(node_disk_writes_completed_total{system=~\"$system\",instance=~\"$instance\",device=~\"[a-z]*[a-z]\"}[$interval])) by (service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-write"
      }
     ]
    },
    {
     "title": "Network transmited/resived time seconds",
     "type": "graph",
     "description": "read - negative  Y\nwrite - positive Y",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Bps", "label": "transmit (-) /resive (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-out"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "description": "irate - packets per second",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-out"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "description": "irate - packets per second",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-out"
      }
     ]
    },
    {
     "title": "TCP Connections count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_netstat_Tcp_CurrEstab{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "UDP In / Out",
     "type": "graph",
     "description": "irate - per second  Datagrams",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(irate(node_netstat_Udp_InDatagrams{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-in"
      },
      {
       "expr": "label_replace(irate(node_netstat_Udp_OutDatagrams{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-out"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "description": "irate - per second  errors",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(irate(node_netstat_Udp_InErrors{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-InErrors"
      },
      {
       "expr": "label_replace(irate(node_netstat_Udp_NoPorts{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-NoPorts"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes FS - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 25 },
     "repeat": "instance_list",
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 25 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 25 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 25 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 39 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service] Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 9 },
     "repeat": "alertname",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Alert List: system:$system, GROUP:$alert_group",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "ALERTS{system=~\"$system\", instance=~\"$instance\",alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"} "
      }
     ]
    }
   ]
  },
  {
   "title": "raw metrics: $metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "$metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "repeat": "metrics",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "$metrics{instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}