{
 "title": "[SERVICE] Solr",
 "description": "Solr-exporter metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "interval", "query": "5m,10m,15m,30m,1h" },
   { "name": "service", "query": "label_values(service)" },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   {
    "name": "instance",
    "query": "label_values(solr_ping{system=~\"$system\"},instance)"
   },
   {
    "name": "base_url",
    "query": "label_values(solr_ping{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\".+\"},base_url)"
   },
   {
    "name": "collection",
    "query": "label_values(solr_ping{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", collection=~\".+\"},collection)"
   },
   {
    "name": "shard",
    "query": "label_values(solr_collections_shard_state{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", collection=~\"$collection\", shard=~\".+\"},shard)"
   },
   {
    "name": "replica",
    "query": "label_values(solr_collections_replica_state{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", collection=~\"$collection\", shard=~\"$shard\",replica=~\".+\"},replica)"
   },
   {
    "name": "core",
    "query": "label_values(solr_ping{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},core)"
   },
   {
    "name": "jetty_request_method",
    "query": "label_values(solr_metrics_jetty_requests_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},method)"
   },
   {
    "name": "jetty_response_status",
    "query": "label_values(solr_metrics_jetty_response_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},status)"
   },
   {
    "name": "jvm_buffer_pool",
    "query": "label_values(solr_metrics_jvm_buffers{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},pool)"
   },
   {
    "name": "jvm_buffer_item",
    "query": "label_values(solr_metrics_jvm_buffers_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", pool=~\"$jvm_buffer_pool\"},item)"
   },
   {
    "name": "jvm_gc_item",
    "query": "label_values(solr_metrics_jvm_gc_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},item)"
   },
   {
    "name": "jvm_heap_item",
    "query": "label_values(solr_metrics_jvm_memory_heap_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},item)"
   },
   {
    "name": "jvm_heap_space",
    "query": "label_values(solr_metrics_jvm_memory_pools_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$jvm_heap_item\"},space)"
   },
   {
    "name": "jvm_thread_item",
    "query": "label_values(solr_metrics_jvm_threads{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},item)"
   },
   {
    "name": "os_jvm_memory_item",
    "query": "label_values(solr_metrics_jvm_os_memory_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},item)"
   },
   {
    "name": "os_jvm_file_descriptors_item",
    "query": "label_values(solr_metrics_jvm_os_file_descriptors{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},item)"
   },
   {
    "name": "os_jvm_cpu_load_item",
    "query": "label_values(solr_metrics_jvm_os_cpu_load{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},item)"
   },
   {
    "name": "os_jvm_cpu_time_item",
    "query": "label_values(solr_metrics_jvm_os_cpu_time_seconds{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},item)"
   },
   {
    "name": "os_jvm_load_average_item",
    "query": "label_values(solr_metrics_jvm_os_load_average{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},item)"
   },
   {
    "name": "node_category",
    "query": "label_values(solr_metrics_node_requests_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "node_handler",
    "query": "label_values(solr_metrics_node_requests_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_category\"},handler)"
   },
   {
    "name": "node_cores_category",
    "query": "label_values(solr_metrics_node_cores{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "node_cores_item",
    "query": "label_values(solr_metrics_node_cores{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_cores_category\"},item)"
   },
   {
    "name": "node_core_fs_category",
    "query": "label_values(solr_metrics_node_core_root_fs_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "node_core_fs_item",
    "query": "label_values(solr_metrics_node_core_root_fs_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_cores_category\"},item)"
   },
   {
    "name": "node_thread_pool_completed_category",
    "query": "label_values(solr_metrics_node_thread_pool_completed_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "node_thread_pool_completed_executor",
    "query": "label_values(solr_metrics_node_thread_pool_completed_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_thread_pool_completed_category\"},executor)"
   },
   {
    "name": "node_thread_pool_completed_handler",
    "query": "label_values(solr_metrics_node_thread_pool_completed_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_thread_pool_completed_category\"},handler)"
   },
   {
    "name": "node_thread_pool_submitted_category",
    "query": "label_values(solr_metrics_node_thread_pool_submitted_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "node_thread_pool_submitted_executor",
    "query": "label_values(solr_metrics_node_thread_pool_submitted_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_thread_pool_submitted_category\"},executor)"
   },
   {
    "name": "node_thread_pool_submitted_handler",
    "query": "label_values(solr_metrics_node_thread_pool_submitted_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_thread_pool_submitted_category\"},handler)"
   },
   {
    "name": "node_thread_pool_running_category",
    "query": "label_values(solr_metrics_node_thread_pool_running{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "node_thread_pool_running_executor",
    "query": "label_values(solr_metrics_node_thread_pool_running{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_thread_pool_running_category\"},executor)"
   },
   {
    "name": "node_connections_category",
    "query": "label_values(solr_metrics_node_connections{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "node_connections_handler",
    "query": "label_values(solr_metrics_node_connections{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_connections_category\"},handler)"
   },
   {
    "name": "node_connections_item",
    "query": "label_values(solr_metrics_node_connections{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_connections_category\"},item)"
   },
   {
    "name": "core_requests_category",
    "query": "label_values(solr_metrics_core_requests_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "core_requests_handler",
    "query": "label_values(solr_metrics_core_requests_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_requests_category\"},handler)"
   },
   {
    "name": "core_cache_category",
    "query": "label_values(solr_metrics_core_field_cache_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "core_searcher_cache_item",
    "query": "label_values(solr_metrics_core_searcher_cache{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_cache_category\"},item)"
   },
   {
    "name": "core_searcher_cache_type",
    "query": "label_values(solr_metrics_core_searcher_cache{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_cache_category\"},type)"
   },
   {
    "name": "core_searcher_warmup_item",
    "query": "label_values(solr_metrics_core_searcher_warmup_time_seconds{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_cache_category\"},item)"
   },
   {
    "name": "core_searcher_warmup_type",
    "query": "label_values(solr_metrics_core_searcher_warmup_time_seconds{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_cache_category\"},type)"
   },
   {
    "name": "core_searcher_cumulative_cache_item",
    "query": "label_values(solr_metrics_core_searcher_cumulative_cache_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\",category=~\"$core_cache_category\"},item)"
   },
   {
    "name": "core_searcher_cumulative_cache_type",
    "query": "label_values(solr_metrics_core_searcher_cumulative_cache_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\",category=~\"$core_cache_category\"},type)"
   },
   {
    "name": "core_fs_category",
    "query": "label_values(solr_metrics_core_fs_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "core_fs_item",
    "query": "label_values(solr_metrics_core_fs_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_fs_category\"},item)"
   },
   {
    "name": "core_index_category",
    "query": "label_values(solr_metrics_core_index_size_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "core_searcher_documents_category",
    "query": "label_values(solr_metrics_core_searcher_documents{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"},category)"
   },
   {
    "name": "core_searcher_documents_item",
    "query": "label_values(solr_metrics_core_searcher_documents{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_searcher_documents_category\"},item)"
   }
  ]
 },
 "panels": [
  {
   "title": "Jetty Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_jetty_requests_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", method=~\"$jetty_request_method\"}[${interval}])",
       "legendFormat": "{{base_url}} {{method}}"
      }
     ]
    },
    {
     "title": "Response",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_jetty_response_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", status=~\"$jetty_response_status\"}[${interval}])",
       "legendFormat": "{{base_url}} {{status}}"
      }
     ]
    },
    {
     "title": "Dispatches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_jetty_dispatches_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\"}[${interval}])",
       "legendFormat": "{{base_url}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_buffers{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", pool=~\"$jvm_buffer_pool\"}",
       "legendFormat": "{{base_url}} {{pool}}"
      }
     ]
    },
    {
     "title": "Buffer Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_buffers_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", pool=~\"$jvm_buffer_pool\", item=~\"$jvm_buffer_item\"}",
       "legendFormat": "{{base_url}} {{pool}} {{item}}"
      }
     ]
    },
    {
     "title": "GC Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_jvm_gc_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$jvm_gc_item\"}[${interval}])",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "GC Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_jvm_gc_seconds_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$jvm_gc_item\"}[${interval}])",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Heap Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_heap_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$jvm_heap_item\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Non-Heap Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_non_heap_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$jvm_heap_item\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Pool Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_pools_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$jvm_heap_item\", space=~\"$jvm_heap_space\"}",
       "legendFormat": "{{base_url}} {{space}} {{item}}"
      }
     ]
    },
    {
     "title": "Memory Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_memory_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$jvm_heap_item\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_threads{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$jvm_thread_item\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OS Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_memory_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$os_jvm_memory_item\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_file_descriptors{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$os_jvm_file_descriptors_item\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_cpu_load{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$os_jvm_cpu_load_item\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "CPU Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_jvm_os_cpu_time_seconds{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$os_jvm_cpu_time_item\"}[${interval}])",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_jvm_os_load_average{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", item=~\"$os_jvm_load_average_item\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_node_requests_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_category\", handler=~\"$node_handler\"}[${interval}])",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Request Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_node_time_seconds_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_category\", handler=~\"$node_handler\"}[${interval}])",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Client Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_node_client_errors_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_category\", handler=~\"$node_handler\"}[${interval}])",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Server Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_node_server_errors_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_category\", handler=~\"$node_handler\"}[${interval}])",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_node_errors_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_category\", handler=~\"$node_handler\"}[${interval}])",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Timeouts",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_node_timeouts_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_category\", handler=~\"$node_handler\"}[${interval}])",
       "legendFormat": "{{base_url}}{{handler}}"
      }
     ]
    },
    {
     "title": "Cores",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_cores{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_cores_category\", item=~\"$node_cores_item\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Core Root File System",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_core_root_fs_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_core_fs_category\", item=~\"$node_core_fs_item\"}",
       "legendFormat": "{{base_url}} {{item}}"
      }
     ]
    },
    {
     "title": "Thread Pool Completed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_node_thread_pool_completed_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_thread_pool_completed_category\", executor=~\"$node_thread_pool_completed_executor\", handler=~\"$node_thread_pool_completed_handler\"}[${interval}])",
       "legendFormat": "{{base_url}} {{handler}} {{executor}}"
      }
     ]
    },
    {
     "title": "Thread Pool Submitted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(solr_metrics_node_thread_pool_submitted_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\",category=~\"$node_thread_pool_submitted_category\", executor=~\"$node_thread_pool_submitted_executor\", handler=~\"$node_thread_pool_submitted_handler\"}[${interval}])",
       "legendFormat": "{{base_url}} {{handler}} {{executor}}"
      }
     ]
    },
    {
     "title": "Thread Pool Running",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_thread_pool_running{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_thread_pool_running_category\", executor=~\"$node_thread_pool_running_executor\"}",
       "legendFormat": "{{base_url}} {{handler}} {{executor}}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_metrics_node_connections{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$node_connections_category\", handler=~\"$node_connections_handler\", item=~\"$node_connections_item\"}",
       "legendFormat": "{{base_url}} {{handler}} {{item}}"
      }
     ]
    }
   ]
  },
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_requests_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_requests_category\", handler=~\"$core_requests_handler\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Request Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_time_seconds_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_requests_category\", handler=~\"$core_requests_handler\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Client Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_client_errors_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_requests_category\", handler=~\"$core_requests_handler\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Server Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_server_errors_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_requests_category\", handler=~\"$core_requests_handler\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_errors_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_requests_category\", handler=~\"$core_requests_handler\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_timeouts_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_requests_category\", handler=~\"$core_requests_handler\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}{{handler}}"
    }
   ]
  },
  {
   "title": "Field Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_field_cache_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_cache_category\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Searcher Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_cache{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_cache_category\", item=~\"$core_searcher_cache_item\", type=~\"$core_searcher_cache_type\" }",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "Searcher Warm Up Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_warmup_time_seconds{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_cache_category\", item=~\"$core_searcher_warmup_item\", type=~\"$core_searcher_warmup_type\"}",
     "legendFormat": "{{base_url}}/{{core}} {{type}}"
    }
   ]
  },
  {
   "title": "Searcher Cumulative Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_searcher_cumulative_cache_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\",category=~\"$core_cache_category\", item=~\"$core_searcher_cumulative_cache_item\", type=~\"$core_searcher_cumulative_cache_type\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}} {{type}} {{item}}"
    }
   ]
  },
  {
   "title": "File System",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_fs_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_fs_category\", item=~\"$core_fs_item\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_index_size_bytes{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_index_category\", collection=~\"$collection\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Searcher Documents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_searcher_documents{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", category=~\"$core_searcher_documents_category\", item=~\"$core_searcher_documents_item\"}",
     "legendFormat": "{{base_url}}/{{core}} {{item}}"
    }
   ]
  },
  {
   "title": "Update Handler Adds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_adds_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Pending Docs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_update_handler_pending_docs{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By ID",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_id_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Deletes By Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_deletes_by_query_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Expunge Deletes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_expunge_deletes_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Merges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_merges_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Splits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_splits_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Optimizes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_optimizes_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Rollbacks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_rollbacks_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Soft Auto Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_soft_auto_commits_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Auto Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_auto_commits_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Commits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_commits_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "Update Handler Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_core_update_handler_errors_total{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", base_url=~\"$base_url\", collection=~\"$collection\"}[${interval}])",
     "legendFormat": "{{base_url}}/{{core}}"
    }
   ]
  },
  {
   "title": "States",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "description": "Collection states",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "solr_ping{base_url=~\"$base_url\", system=~\"$system\", instance=~\"$instance\", service=~\"$service\", collection=~\"$collection\"}",
       "requestId": "62A",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "Shards",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_collections_shard_state{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", collection=~\"$collection\", shard=~\".*\"}"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "solr_collections_replica_state{system=~\"$system\", instance=~\"$instance\", service=~\"$service\", collection=~\"$collection\", shard=~\"$shard\",replica=~\".+\"}"
      }
     ]
    }
   ]
  }
 ]
}