{
 "title": "[SERVICE] YARN L2",
 "tags": [
  "cdh ",
  "sdp",
  "service",
  "yarn",
  "queue"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "interval",
    "query": "10s,20s,30s,1m,10m,30m,1h,6h,12h,1d"
   },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   { "name": "service", "query": "label_values(service)" },
   {
    "name": "roletype",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\",service=~\"$service\"},roletype)"
   },
   {
    "name": "instance",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   },
   {
    "name": "q0",
    "query": "label_values(hadoop_yarn_jmx_allocated_vcores{roletype=~\"$roletype\",instance=~\"$instance\",},q0)"
   },
   {
    "name": "q1",
    "query": "label_values(hadoop_yarn_jmx_allocated_vcores{roletype=~\"$roletype\",instance=~\"$instance\",q0=~\"$q0\",q1!=\"null\"},q1)"
   },
   {
    "name": "q2",
    "query": "label_values(hadoop_yarn_jmx_allocated_vcores{roletype=~\"$roletype\",instance=~\"$instance\",q0=~\"$q0\",q1=~\"$q1\",},q2)"
   },
   {
    "name": "q3",
    "query": "label_values(hadoop_yarn_jmx_allocated_vcores{roletype=~\"$roletype\",instance=~\"$instance\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"},q3)"
   },
   {
    "name": "q4",
    "query": "label_values(hadoop_yarn_jmx_allocated_vcores{roletype=~\"$roletype\",instance=~\"$instance\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q3=~\"$q3\"},q4)"
   },
   { "name": "metrics", "query": "metrics(^hadoop_yarn)" },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" }
  ]
 },
 "panels": [
  { "title": "Level2: Table", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Статистика $instance quantile=$quantile",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort(quantile_over_time($quantile,max(hadoop_yarn_jmx_fair_share_vcores{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",roletype=~\"$roletype\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q3=\"null\",q4=\"null\" })by (instance,q0,q1,q2) [$__range:]))"
    },
    {
     "expr": "sort(quantile_over_time($quantile,max(hadoop_yarn_jmx_allocated_vcores{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",roletype=~\"$roletype\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q3=\"null\",q4=\"null\" })by (instance,q0,q1,q2) [$__range:]))"
    },
    {
     "expr": "sort(quantile_over_time($quantile,max(hadoop_yarn_jmx_steady_fair_share_mb{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",roletype=~\"$roletype\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q3=\"null\",q4=\"null\" })by (instance,q0,q1,q2) [$__range:]))"
    },
    {
     "expr": "sort(quantile_over_time($quantile,max(hadoop_yarn_jmx_allocated_mb{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",roletype=~\"$roletype\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q3=\"null\",q4=\"null\" })by (instance,q0,q1,q2) [$__range:]))"
    },
    {
     "expr": "sort(quantile_over_time($quantile,max(hadoop_yarn_jmx_apps_running{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",roletype=~\"$roletype\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q3=\"null\",q4=\"null\" })by (instance,q0,q1,q2) [$__range:]))"
    },
    {
     "expr": "sort(quantile_over_time($quantile,max(hadoop_yarn_jmx_apps_pending{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",roletype=~\"$roletype\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q3=\"null\",q4=\"null\" })by (instance,q0,q1,q2) [$__range:]))"
    },
    {
     "expr": "count by (q2) (count by (q1,q2,q3) (max(hadoop_yarn_jmx_apps_pending{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",roletype=~\"$roletype\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q4=\"null\" } ) by (instance,q0,q1,q2,q3)))  - 1"
    }
   ]
  },
  {
   "title": "Level2:$q1 YARN CPU&Mem summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "repeat": "q1",
   "collapsed": true,
   "panels": [
    {
     "title": "q1=$q1 q2=variables  hadoop_yarn_jmx_allocated_vcores",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort(max (hadoop_yarn_jmx_fair_share_vcores{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=\"null\",q3=\"null\",q4=\"null\"}) by (instance,q0,q1))",
       "legendFormat": "q1={{q1}} null fair_share_vcores"
      },
      {
       "expr": "sort(max(hadoop_yarn_jmx_allocated_vcores{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\"\n,q0=\"$q0\",q1=~\"$q1\",q2=\"null\",q3=\"null\",q4=\"null\"})by (instance,q0,q1))",
       "legendFormat": "q1={{q1}} allocated vcores"
      },
      {
       "expr": "sort(max (hadoop_yarn_jmx_allocated_vcores{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" }) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} share vcores"
      }
     ]
    },
    {
     "title": "q1=$q1 q2=variables hadoop_yarn_jmx_allocated_mb",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sort(max(hadoop_yarn_jmx_steady_fair_share_mb{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=~\"$q0\",q1=~\"$q1\",q2=\"null\",q3=\"null\",q4=\"null\"}) by (instance,q0,q1,q2))",
       "legendFormat": "q1={{q1}}  null  fair_share_mb"
      },
      {
       "expr": "sort(max (hadoop_yarn_jmx_allocated_mb{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=~\"$q0\",q1=~\"$q1\",q2=\"null\",q3=\"null\",q4=\"null\" }) by (instance,q0,q1,q2))",
       "legendFormat": "q1={{q1}} allocated mb"
      },
      {
       "expr": "sort(max (hadoop_yarn_jmx_allocated_mb{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" }) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} allocated mb"
      }
     ]
    }
   ]
  },
  {
   "title": "Level2:$q1 YARN App summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "repeat": "q1",
   "collapsed": true,
   "panels": [
    {
     "title": "apps_running",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort(max(hadoop_yarn_jmx_apps_running{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\"\n,q0=\"$q0\",q1=~\"$q1\",q2=\"null\",q3=\"null\",q4=\"null\"})by (instance,q0,q1))",
       "legendFormat": "q1={{q1}} apps_running"
      },
      {
       "expr": "sort(max (hadoop_yarn_jmx_apps_running{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" } > 0 ) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} apps_running"
      }
     ]
    },
    {
     "title": "apps_pending",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort(max(hadoop_yarn_jmx_apps_pending{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\"\n,q0=\"$q0\",q1=~\"$q1\",q2=\"null\",q3=\"null\",q4=\"null\"})by (instance,q0,q1))",
       "legendFormat": "q1={{q1}} apps_pending "
      },
      {
       "expr": "sort(max (hadoop_yarn_jmx_apps_pending{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" } > 0 ) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} apps_pending"
      }
     ]
    }
   ]
  },
  {
   "title": "Level2:$q1 YARN $instance CPU&Mem details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "q1",
   "collapsed": true,
   "panels": [
    {
     "title": "q1=$q1 q2=$q2",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "repeat": "q2",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort(max (hadoop_yarn_jmx_allocated_vcores{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" }) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} share vcores"
      },
      {
       "expr": "sort(max (hadoop_yarn_jmx_allocated_mb{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" }) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} allocated mb"
      }
     ]
    },
    {
     "title": "q1=$q1 q2=$q2",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort(max (hadoop_yarn_jmx_allocated_vcores{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" }) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} share vcores"
      },
      {
       "expr": "sort(max (hadoop_yarn_jmx_allocated_mb{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" }) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} allocated mb"
      }
     ]
    },
    {
     "title": "q1=$q1 q2=$q2",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort(max (hadoop_yarn_jmx_allocated_vcores{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" }) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} share vcores"
      },
      {
       "expr": "sort(max (hadoop_yarn_jmx_allocated_mb{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" }) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} allocated mb"
      }
     ]
    },
    {
     "title": "q1=$q1 q2=$q2",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sort(max (hadoop_yarn_jmx_allocated_vcores{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" }) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} share vcores"
      },
      {
       "expr": "sort(max (hadoop_yarn_jmx_allocated_mb{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",q2!=\"null\",q3=\"null\",q4=\"null\" }) by (instance,q0,q1,q2))",
       "legendFormat": "q2={{q2}} allocated mb"
      }
     ]
    }
   ]
  }
 ]
}