{
 "title": "[SERVICE] YARN RM L2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "5m,10m,15m,30m,1h" },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   { "name": "service", "query": "label_values(service)" },
   {
    "name": "instance",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   },
   {
    "name": "q0",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\"},q0)"
   },
   {
    "name": "q1",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\"},q1)"
   },
   {
    "name": "q2",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\",q1=~\"$q1\"},q2)"
   },
   {
    "name": "name",
    "label": "name",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"},name)"
   },
   {
    "name": "stage",
    "label": "stage",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"},stage)"
   },
   {
    "name": "finalStatus",
    "label": "Final status",
    "query": "label_values(hadoop_yarn_app_finalstatus{system=~\"$system\",service=~\"$service\"},finalStatus)"
   },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   { "name": "threshold_cores", "query": "-1,0,1,2,5,10,50,100" },
   { "name": "threshold_mem", "label": "threshold_mem GB", "query": "-1,0,1,2,5,10,20,50,100,500" },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" },
   { "name": "wf", "label": ".+ if only with wf_name", "query": ".*,.+" }
  ]
 },
 "panels": [
  {
   "title": "APPs summary Table, q1=$q1 q2=$q2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "APPs q1=[  $q1  ] q2=[ $q2 ] name = [ $name ] stage=[ $stage ] , finalStatus=[$finalStatus] last FINISHED run",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max_over_time(max(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\",}<hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time(max(hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}>hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time(max(hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>-1) by(name,wf_name,stage,q1,q2)[$__range:])  + max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=\"SUCCEEDED\"}) by(name,wf_name,stage,q1,q2)[$__range:]) - 6"
    },
    {
     "expr": "avg_over_time (sum((hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"})*1000) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}>-1) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "(max_over_time (max(\r\nhadoop_yarn_app_allocatedvcores{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>-1) by(name,wf_name,stage,q1,q2)[$__range:])) + max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=\"SUCCEEDED\"}) by(name,wf_name,stage,q1,q2)[$__range:]) - 6"
    },
    {
     "expr": "avg_over_time (sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}*1000) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}>-1) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time(count(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    }
   ]
  },
  {
   "title": "APPs q1=[  $q1  ] q2=[ $q2 ] name = [ $name ] stage=[ $stage ] current run",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by (name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by (name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by (name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>-1) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max((hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"})*1000) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "sum(hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(\r\nhadoop_yarn_app_allocatedvcores{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>-1) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by(name,wf_name,stage,q1,q2) * 1000"
    },
    {
     "expr": "sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>-1) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "count(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by (name,wf_name,stage,q1,q2)"
    }
   ]
  },
  {
   "title": "APPs summary History, q1=$q1 q2=$q2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "APPs q1=[  $q1  ] q2=[  $q2 ] name = [ $name ] stage=[ $stage ] mem",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>0) by (system,q1,q2)",
       "legendFormat": "mem allocated q2={{ q2 }}"
      },
      {
       "expr": "sum((hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"})*1000) by (system,q1,q2)",
       "legendFormat": "mem used q2={{ q2 }}"
      }
     ]
    },
    {
     "title": "APPs q1=[  $q1  ] q2=[ $q2 ] name = [ $name ] stage=[ $stage ] vcores ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedvcores{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"} > 0) by (system,q1,q2)",
       "legendFormat": " vcores allocated q2={{ q2 }}"
      },
      {
       "expr": "sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by(system,q1,q2) * 1000",
       "legendFormat": "vcores used q2={{ q2 }}"
      }
     ]
    },
    {
     "title": "APPs q1=[  $q1  ] q2=[ $q2 ] name = [ $name ] stage=[ $stage ] containers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_runningcontainers{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"} > 0) by (system,q1,q2)",
       "legendFormat": "running containers"
      }
     ]
    },
    {
     "title": "APPs(filtered) vcores",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedvcores{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"} > 0) by (system,q1,q2)",
       "legendFormat": " allocated vcores sum"
      }
     ]
    },
    {
     "title": "APPs(filtered) allocateted mb",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>0) by (system,q1,q2)",
       "legendFormat": "allocated mb sum"
      }
     ]
    },
    {
     "title": "APPs(filtered) state( RUNNING - 5, FINISHED - 6, FAILED - 7, KILLED - 8)",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "hadoop_yarn_app_state{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}",
       "legendFormat": "{{ name }} {{stage }} state "
      }
     ]
    },
    {
     "title": "APPs(filtered) FINAL STATUS( FINISHED - 6, FAILED - 7, KILLED - 8)",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "hadoop_yarn_app_finalstatus{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}",
       "legendFormat": "{{ name }} {{stage }} state "
      }
     ]
    }
   ]
  },
  {
   "title": "APPs detailed q1=$q1 q2=$q2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "APPs q1=[  $q1  ] q2=[  $q2 ] name = [ $name ] stage=[ $stage ] allocateted mb >$threshold_mem GB",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decmbytes" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>$threshold_mem*1024) by (system,q1,q2,name)",
       "legendFormat": "allocated mb sum {{ name }}"
      }
     ]
    },
    {
     "title": "APPs q1=[  $q1  ] q2=[ $q2 ] name = [ $name ] stage=[ $stage ] vcores >$threshold_cores",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_allocatedvcores{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>$threshold_cores) by (system,q1,q2,name)",
       "legendFormat": " allocated vcores sum {{ name }}"
      }
     ]
    },
    {
     "title": "APPs q1=[  $q1  ] q2=[ $q2 ] name = [ $name ] stage=[ $stage ] containers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(hadoop_yarn_app_runningcontainers{system=\"$system\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>0) by (system,q1,q2,name)",
       "legendFormat": "running containers {{ name }}"
      }
     ]
    }
   ]
  }
 ]
}