{
 "title": "[SERVICE] Oozie",
 "tags": [
  "cdh",
  "sdp",
  "service",
  "oozie"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" },
   { "name": "service", "query": "label_values(service)" },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   {
    "name": "instance",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   {
    "name": "alert_group",
    "query": "label_values(ALERTS_FOR_STATE,alert_group)"
   },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{alert_group=~\"$alert_group\",},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" },
   {
    "name": "regexp",
    "label": "regexp for FQDN",
    "query": "([a-zA-Z0-9]+-[a-zA-Z0-9]+)[.].+ , (.+)"
   },
   {
    "name": "mountpoint",
    "label": "mountpoint !=",
    "query": "label_values({system=~\"$system\",instance=~\"$instance_list\",fstype=~\"ext4|xfs\"},mountpoint)"
   },
   { "name": "metrics", "label": "raw metric", "query": "metrics(^hadoop_oozie)" },
   {
    "name": "instance_list",
    "query": "label_values({system=~\"$system\",service=~\"$service\"},instance)"
   },
   {
    "name": "name",
    "query": "label_values(hadoop_oozie_server_jmx_j2eetype_servlet_processing_time{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"},name)"
   },
   { "name": "name2" }
  ]
 },
 "panels": [
  {
   "title": "Readme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Описание",
     "type": "text",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "content": "\n## Описание дашборда\n\nДанный дашборд отображает основные метрики собираемые с oozie посредством\n- exporter-node\n- exporter-jmx\n\nБлоки Summary содержат информацию о всех инстансах сервиса. Остальные блоки фильтруют информацию по полю instance\n\n#### переменные\n- ds - выбор датасорса(prometheus) из которого запрашивать данные для отображения(подробнее про типы прометеусов см https://confluence.ca.sbrf.ru/pages/editpage.action?pageId=2383122863)\n- system - имя системы\n- quantile - значение персентия для расчета значений в таблицах\n- last - период вермени отображения метрик для таблиц(чтобы не делать тяжелые расчеты на больших выборках)\n- regexp for FQDN - regexp для отсекания FQDN имен на графиках (экономия используемого места дашборда)\n- ountpoint != список точек монтирования, которые НЕ интересны для мониторинга(не учитывать в TopK селектах по утилизации файловых систем)\n- raw metric - выбрать метрику для отображения ее в \"сыром\" виде в блоке RAW METRICS (возможность для пользователя посмотрить метрки данного сервиса отсутствующие на дашборде, аналогичный функционал в меню графаны EXPLORE\n\n#### drill down links\n- из таблиц возможен переход по имени инстанса на более подробный дашборд по выбранному инстансу"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Readme",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
     "content": "Данный блок должен содержать виджеты по ключевым метрикам сервиса.\nКлючивые метрики определяет разработчик/админ сервиса.\n\nКлючевыми метриками могут быть как стандартные метрики ОС или Java, так и кастомные метрики сервиса(кол-во ошибок, задержки, статус и т.д.)\n\nКрайне желательно определить метрику определяющую общий статус сервиса.\n\n"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Metrics jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "[$system] service:[$service] jmx j2eetype servlet time",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "label_replace( max(hadoop_oozie_server_jmx_j2eetype_servlet_min_time\r{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"$name\"}) by (system,instance,name, webmodule) , \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{instance}}, {{name}}"
    },
    {
     "expr": "label_replace( max(hadoop_oozie_server_jmx_j2eetype_servlet_max_time\r{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"$name\"}) by (system,instance,name, webmodule), \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{instance}}, {{name}}"
    },
    {
     "expr": "label_replace( max(hadoop_oozie_server_jmx_j2eetype_servlet_load_time{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"$name\"}) by (system,instance,name, webmodule) , \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{instance}}, {{name}}"
    },
    {
     "expr": "label_replace( max(hadoop_oozie_server_jmx_j2eetype_servlet_class_load_time{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"$name\"}) by (system,instance,name, webmodule) , \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{instance}}, {{name}}"
    },
    {
     "expr": "label_replace( max(hadoop_oozie_server_jmx_j2eetype_servlet_processing_time{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", name=~\"$name\"}) by (system,instance,name, webmodule) > 0, \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{instance}}, {{name}}"
    }
   ]
  },
  {
   "title": "[$system] service:[$service] jmx_j2eetype_servlet_error percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "label_replace((hadoop_oozie_server_jmx_j2eetype_servlet_error_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"$name\"} / hadoop_oozie_server_jmx_j2eetype_servlet_request_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"$name\"}), \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{instance}}, {{name}} "
    }
   ]
  },
  {
   "title": "[$system] service:[$service] jmx_j2eetype_servlet_error_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace((delta(hadoop_oozie_server_jmx_j2eetype_servlet_error_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"$name\"}[10m])) > 0 , \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{instance}}, {{name}} "
    }
   ]
  },
  {
   "title": "[$system] service:[$service] jmx_j2eetype_servlet_request_count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace((delta(hadoop_oozie_server_jmx_j2eetype_servlet_request_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"$name\"}[10m]))  > 0 , \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{instance}}, {{name}} "
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] jmx type cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$system] service:[$service] jmx type cache size ",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "label_replace( max(hadoop_oozie_server_jmx_type_cache_cache_size{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,instance,name, webmodule), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}} cache_size"
      },
      {
       "expr": "label_replace( max(hadoop_oozie_server_jmx_type_cache_cache_max_size{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,instance,name, webmodule), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}} cache_max_size"
      }
     ]
    },
    {
     "title": "[$system] service:[$service] jmx_type_cache_desired_entry_access_ratio ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace( max(hadoop_oozie_server_jmx_type_cache_desired_entry_access_ratio{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,instance,name, webmodule) , \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$system] service:[$service] jmx_type_cache_hits_count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace( (delta(hadoop_oozie_server_jmx_type_cache_hits_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[10m])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}, path={{path}}"
      }
     ]
    },
    {
     "title": "[$system] service:[$service] jmx_type_cache_hits_count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace((delta(hadoop_oozie_server_jmx_type_cache_hits_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[10m])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}, path={{path}}"
      }
     ]
    },
    {
     "title": "[$system] service:[$service] jmx_type_stringcache_hit_count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace((irate(hadoop_oozie_server_jmx_type_stringcache_hit_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[10m])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}} stringcache_hit_count"
      }
     ]
    },
    {
     "title": "[$system] service:[$service] jmx_type_stringcache_access_count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace( (irate(hadoop_oozie_server_jmx_type_stringcache_access_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[10m])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}} stringcache_access_count"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] jmx type threadpool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "[$system] service:[$service] jmx_type_threadpool_current_threads_busy",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace( hadoop_oozie_server_jmx_type_threadpool_current_threads_busy{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "[$system] service:[$service] jmx_type_threadpool_current_thread_count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace( hadoop_oozie_server_jmx_type_threadpool_current_thread_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}} currunt threads count"
      },
      {
       "expr": "label_replace( hadoop_oozie_server_jmx_type_threadpool_max_threads{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}} max threads count"
      }
     ]
    },
    {
     "title": "[$system] service:[$service] jmx_type_threadpool_acceptor_thread_count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace( hadoop_oozie_server_jmx_type_threadpool_acceptor_thread_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}} acceptor_thread_count"
      }
     ]
    },
    {
     "title": "[$system] service:[$service] jmx_type_threadpool_backlog",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace( max(hadoop_oozie_server_jmx_type_threadpool_backlog{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}} threadpool_backlog"
      },
      {
       "expr": "label_replace( max(hadoop_oozie_server_jmx_type_threadpool_max_header_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,instance) > 0, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}} threadpool_max_header_count"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] JMX Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "Sys CPU% max",
   "type": "singlestat",
   "description": "$service -  Max  Host system CPU% Utilization over all hosts",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 22 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",service=~\"$service\"}) by (system,service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Sys Mem Total",
   "type": "singlestat",
   "description": "$service -  Summary Memory size",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 22 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\"})\nby (system,service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Sys Cores Total",
   "type": "singlestat",
   "description": "$service -  Summary Cores count",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jmx_java_lang_operatingsystem_availableprocessors{system=~\"$system\",service=~\"$service\"})\nby (system,service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "JMX Exporters cout",
   "type": "singlestat",
   "description": "Prometheus Jobs for JMX(filter roletype <> null) metrics",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 22 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{system=~\"$system\", service=~\"$service\", roletype=~\".+\"})"
    }
   ]
  },
  {
   "title": "Java CPU% max",
   "type": "singlestat",
   "description": "$service -  Max  Java CPU% Utilization over all Java applications",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 22 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\"}) by (system,service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Heap Mem% max",
   "type": "singlestat",
   "description": "$service -  Max  Java Mem% Utilization over all Java applications",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 22 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\"} / jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "GC Time max",
   "type": "singlestat",
   "description": "$service -  Max  Garbage Collector collection time over all Java applications",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 22 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(max(rate(jmx_java_lang_garbagecollector_collectiontime{system=~\"$system\",service=~\"$service\"}[$interval])) by (system,service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Sys Mem% max",
   "type": "singlestat",
   "description": "$service -  Max  Sys Mem% Utilization over all hosts",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\"} / \non(system,service,roletype,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\"})) \nby (system,service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "JMX Exporters Up",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(jmx_exporter_build_info{system=~\"$system\", service=~\"$service\"})"
    }
   ]
  },
  {
   "title": "Open File Descriptor max count",
   "type": "singlestat",
   "description": "$service -  Max  open file descriptor count over all Java applications",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(max(jmx_java_lang_operatingsystem_openfiledescriptorcount{system=~\"$system\",service=~\"$service\"}) by (system,service))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "System:[  $system  ] Service:[  $service  ] JMX metrics, quantile=$quantile ",
   "type": "table",
   "description": "JMX metrics summary table for last $last.\n\nSys - means host OS metrics.\n\nAggregation(quanlile/max/last)  values during last $last\n\nJava/Heap/Pool - means Java application(service) metrics.\n\nYou can change colors threatholds as you wish\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": " (min(up{system=~\"$system\",service=~\"$service\",roletype=~\".+\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": "(min(jmx_java_lang_runtime_uptime{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": "(max(jmx_java_lang_operatingsystem_availableprocessors{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": "quantile_over_time ($quantile,(max(jmx_java_lang_operatingsystem_systemloadaverage{system=~\"$system\",service=~\"$service\"}) by(system,service,roletype,instance))[$__range:])"
    },
    {
     "expr": " quantile_over_time ($quantile,(max(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))[$__range:])"
    },
    {
     "expr": "quantile_over_time ($quantile,(max(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))[$__range:])"
    },
    {
     "expr": "(max(jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": " max(1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\"} / \non(system,service,roletype,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\"})) \nby (system,instance,roletype,service)"
    },
    {
     "expr": "(max(jmx_java_lang_operatingsystem_totalswapspacesize{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": "max (1 - (jmx_java_lang_operatingsystem_freeswapspacesize{system=~\"$system\",service=~\"$service\"} / on(system,service,roletype,instance)\njmx_java_lang_operatingsystem_totalswapspacesize{system=~\"$system\",service=~\"$service\"})) by (system,service,roletype,instance)"
    },
    {
     "expr": "(max(jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": "(max(jmx_java_lang_memory_heapmemoryusage_max{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": "quantile_over_time ($quantile,(max(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))[$__range:])"
    },
    {
     "expr": "quantile_over_time ($quantile,(max(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\"} / jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))[$__range:])"
    },
    {
     "expr": "(max(jmx_java_lang_memory_nonheapmemoryusage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": "max(jmx_java_lang_memory_nonheapmemoryusage_used{system=~\"$system\",service=~\"$service\"} / jmx_java_lang_memory_nonheapmemoryusage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance)"
    },
    {
     "expr": "(max(jmx_java_lang_memorypool_usage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": "max(jmx_java_lang_memorypool_usage_used{system=~\"$system\",service=~\"$service\"} / jmx_java_lang_memorypool_usage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance)"
    },
    {
     "expr": "max_over_time((max(rate(jmx_java_lang_garbagecollector_collectiontime{system=~\"$system\",service=~\"$service\"}[$interval])) by (system,service,roletype,instance))[$__range:])"
    },
    {
     "expr": "(max(jmx_java_lang_threading_threadcount{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": "(max(jmx_java_lang_operatingsystem_openfiledescriptorcount{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] JMX Host Systems - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Avarage Host Systems - [ $instance ]",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(jmx_java_lang_operatingsystem_systemloadaverage{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Usage % Host Systems - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory Usage % Host Systems - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace( (1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} / \non(system,service,roletype,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})) , \"instance\", \"$1\", \"instance\", \"$regexp\")\n",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] JMX Java - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Java Heap Usage % - [ $instance ]",
     "type": "graph",
     "description": "Java metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace( (max(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"} / jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}) by (system,service,roletype,instance)) , \"instance\", \"$1\", \"instance\", \"$regexp\")\n",
       "legendFormat": "{{ instance }}-{{ roletype }}"
      }
     ]
    },
    {
     "title": "Java CPU Usage %  - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ roletype }}"
      }
     ]
    },
    {
     "title": "Java Heap Usage MB - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ roletype }}"
      }
     ]
    },
    {
     "title": "Java GC Time - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace((rate\r\n(jmx_java_lang_garbagecollector_collectiontime{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval])\r\n), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ roletype }}"
      }
     ]
    },
    {
     "title": "Java GC count - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace((delta(jmx_java_lang_garbagecollector_collectioncount{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ roletype }}"
      }
     ]
    },
    {
     "title": "Java Thread count - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace((jmx_java_lang_threading_threadcount{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ roletype }}"
      }
     ]
    },
    {
     "title": "Java Open File Descriptor count - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace((jmx_java_lang_operatingsystem_openfiledescriptorcount{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ roletype }}"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU%",
     "type": "singlestat",
     "description": "$service -  avg Host system CPU% Utilization over all hosts",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"idle\",}[$interval])) by(system,instance)) by (system,service)"
      }
     ]
    },
    {
     "title": "CPU% User",
     "type": "singlestat",
     "description": "$service -  avg Host system CPU% user Utilization over all hosts",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"user\"}[$interval]))"
      }
     ]
    },
    {
     "title": "CPU% iowait",
     "type": "gauge",
     "description": "$service -  max Host system CPU% iowait Utilization over all hosts",
     "gridPos": { "h": 6, "w": 2, "x": 6, "y": 7 },
     "targets": [
      {
       "expr": "max_over_time (max(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"iowait\"}[$interval]))[$__range:])",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Cores Total",
     "type": "singlestat",
     "description": "$service -  Summary Cores count",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{system=~\"$system\", instance=~\"$instance_list\",}) by (cpu,system,instance)) by(system,service)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Mem Total",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 7 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}))"
      }
     ]
    },
    {
     "title": "disk util max read_time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 7 },
     "format": "s",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))",
       "legendFormat": "read"
      }
     ]
    },
    {
     "title": "Top Usage FS",
     "type": "table",
     "description": "Top  most usage File Systems over all hosts\n\nmountpoint  != variable: $mountpoint",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
     "targets": [
      {
       "expr": "label_replace( topk(5,max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by (instance,mountpoint)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Mem Free Total",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 9 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"}))"
      }
     ]
    },
    {
     "title": "CPU% System",
     "type": "singlestat",
     "description": "$service -  avg Host system CPU%  system Utilization over all hosts",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg (rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"system\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Nodes Count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_exporter_build_info{system=~\"$system\", instance=~\"$instance_list\",})"
      }
     ]
    },
    {
     "title": "disk util max write_time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 10 },
     "format": "s",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))",
       "legendFormat": "write "
      }
     ]
    },
    {
     "title": "Mem%",
     "type": "singlestat",
     "description": "$service -  avg Host system Mem% Utilization over all hosts",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 11 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} \n- (node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"} +\nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"})) / \nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})"
      }
     ]
    },
    {
     "title": "System:[  $system  ] Service:[  $service  ] OS metrics, quantile=$quantile ",
     "type": "table",
     "description": "OS metrics summary table for last $last.\n\nAggregation(quanlile/max/last)  values during last $last\n\nJava/Heap/Pool - means Java application(service) metrics.\n\nYou can change colors threatholds as you wish\n\n",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": " (min(up{system=~\"$system\", instance=~\"$instance_list\", roletype!~\".+\"}) by (system,instance))"
      },
      {
       "expr": "(min(node_boot_time_seconds{system=~\"$system\", instance=~\"$instance_list\", }) by (system,instance))"
      },
      {
       "expr": "count(count(node_cpu_seconds_total{system=~\"$system\", instance=~\"$instance_list\",}) by (cpu,system,instance)) by(system,instance)"
      },
      {
       "expr": "quantile_over_time ($quantile,max(node_load5{system=~\"$system\", instance=~\"$instance_list\",}) by(system,service,instance)[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"idle\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"system\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"user\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"iowait\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"irq\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"softirq\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "max(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by(system,instance)"
      },
      {
       "expr": "max(((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"})) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by(system,instance)"
      },
      {
       "expr": "max_over_time(max by(system,instance) (rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))[$__range:])"
      },
      {
       "expr": "max_over_time(max by(system,instance) (rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))[$__range:])"
      },
      {
       "expr": "(max(node_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by (system,service,instance))"
      },
      {
       "expr": "max (1 - (node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} / on(system,instance)\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by (system,instance)"
      },
      {
       "expr": "sum(irate(node_network_receive_bytes_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))by (system,instance)"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))by (system,instance)"
      },
      {
       "expr": "max((node_netstat_Tcp_CurrEstab{system=~\"$system\",instance=~\"$instance_list\"}))by (system,instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes CPU  - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization % Host Systems ",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"idle\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 1m Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load1{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 5m Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load5{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 15m Host Systems ",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load15{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  System %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"system\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  User %  ]  Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"user\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  IOWait %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"iowait\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Memory - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization% Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\ncurrent formula\n(node_memory_MemTotal_bytes-node_memory_MemFree_bytes-node_memory_Cached_bytes-node_memory_Buffers_bytes ) /\nnode_memory_MemTotal_bytes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Available %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Free %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory Utilization GB Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Available GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Free GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Cached %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Cached GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Buffers %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Buffers GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "[  SWAP Utilization %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max (1 - (node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance\"} / on(system,instance)\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "[  SWAP Utilization GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace( max(\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance\"}-node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance\"}) by (system,instance) , \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Disk & Network - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read/write time seconds",
     "type": "graph",
     "description": "read - negative  Y\nwrite - positive Y",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      {
       "format": "s",
       "label": "disr read s (-) / disk write s (+)"
      }
     ],
     "targets": [
      {
       "expr": "label_replace(sum by(system,instance) (rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-read"
      },
      {
       "expr": "label_replace(sum by(system,instance) (rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-write"
      }
     ]
    },
    {
     "title": "Disk IOps ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_disk_reads_completed_total{system=~\"$system\",instance=~\"$instance\",device=~\"[a-z]*[a-z]\"}[$interval])) by (service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-read"
      },
      {
       "expr": "label_replace(sum(irate(node_disk_writes_completed_total{system=~\"$system\",instance=~\"$instance\",device=~\"[a-z]*[a-z]\"}[$interval])) by (service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-write"
      }
     ]
    },
    {
     "title": "Network transmited/resived time seconds",
     "type": "graph",
     "description": "read - negative  Y\nwrite - positive Y",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Bps", "label": "transmit (-) /resive (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-out"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "description": "irate - packets per second",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-out"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "description": "irate - packets per second",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-out"
      }
     ]
    },
    {
     "title": "TCP Connections count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_netstat_Tcp_CurrEstab{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "UDP In / Out",
     "type": "graph",
     "description": "irate - per second  Datagrams",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(irate(node_netstat_Udp_InDatagrams{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-in"
      },
      {
       "expr": "label_replace(irate(node_netstat_Udp_OutDatagrams{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-out"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "description": "irate - per second  errors",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(irate(node_netstat_Udp_InErrors{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-InErrors"
      },
      {
       "expr": "label_replace(irate(node_netstat_Udp_NoPorts{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-NoPorts"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes FS - [ $instance ] - <ВНИМАНИЕ!!! рекомендуется удалить этот блок для сервисов с более чем 20 хостами>",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
     "repeat": "instance_list",
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 38 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 38 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service] Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 12 },
     "repeat": "alertname",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Alert List: system:$system, GROUP:$alert_group",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "ALERTS{system=~\"$system\", instance=~\"$instance\",alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"} "
      }
     ]
    }
   ]
  },
  {
   "title": "raw metrics: $metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "$metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "repeat": "metrics",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "$metrics{instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}