{
 "title": "[SERVICE] CTL-WF",
 "tags": [ "ctl" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "label": "какой прометеус?", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" },
   { "name": "system", "query": "label_values(system)" },
   {
    "name": "wf_group",
    "label": "wf_group",
    "query": "label_values(ctl_wf_loading_start{system=~\"$system\",},wf_group)"
   },
   {
    "name": "wf_name",
    "query": "label_values(ctl_wf_loading_start{system=~\"$system\",wf_group=~\"$wf_group\"},wf_name)"
   },
   {
    "name": "alive",
    "query": "label_values(ctl_wf_loading_start{system=~\"$system\"},alive)"
   },
   {
    "name": "status",
    "query": "label_values(ctl_wf_loading_start{system=~\"$system\"},status)"
   },
   {
    "name": "finalAlive",
    "query": "label_values(ctl_wf_loading_start{system=~\"$system\"},alive)"
   },
   { "name": "last", "query": "5m,15m,30m" },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" }
  ]
 },
 "panels": [
  {
   "title": "WF_GROUP Status by wf_group wf_group=[$wf_group]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "WF FINISHED counts Summary  Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=\"SUCCESS\"}) by (system)[$interval:]) +1",
     "legendFormat": "success"
    },
    {
     "expr": "changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status!=\"SUCCESS\", status!=\"ERROR\"}) by (system)[$interval:]) +1",
     "legendFormat": "not success"
    },
    {
     "expr": "changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=\"ERROR\"}) by (system)[$interval:]) +1",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "WF counts Summary ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\"}) by (system)[$interval:]) +1",
     "legendFormat": "finished new"
    },
    {
     "expr": "changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"ACTIVE\"}) by (system)[$interval:]) +1",
     "legendFormat": "active new"
    },
    {
     "expr": "count(count(count (ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"ACTIVE\",}) by (system,wf_group,wf_name)) by (system,wf_group)) by (system)",
     "legendFormat": "active total"
    }
   ]
  },
  {
   "title": "wf_group difference of TLA Start TIME",
   "type": "graph",
   "description": "Максимальное отклонение от запланированномо времени старта расчета среди всех потоков группы\n[<0 - старт поже], [>0 - старт раньше]",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    {
     "format": "s",
     "label": "diff (+ ahead / - later) of schedule"
    }
   ],
   "targets": [
    {
     "expr": "min(ctl_wf_loading_tla_start{system=\"$system\",wf_group=~\"$wf_group\",alive=\"COMPLETED\",status=\"SUCCESS\"}<0) by (wf_group)",
     "legendFormat": "{{ wf_group }} "
    },
    {
     "expr": "max(ctl_wf_loading_tla_start{system=\"$system\",wf_group=~\"$wf_group\",alive=\"COMPLETED\",status=\"SUCCESS\"}>=0) by (wf_group)",
     "legendFormat": "{{ wf_group }} "
    }
   ]
  },
  {
   "title": "wf_group difference of TLA End TIME",
   "type": "graph",
   "description": "Максимальное отклонение от запланированномо времени окончания расчета среди всех потоков группы\n[<0 - окончание поже], [>0 - окончание раньше]",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    {
     "format": "s",
     "label": "diff (+ ahead / - later) of schedule"
    }
   ],
   "targets": [
    {
     "expr": "min(ctl_wf_loading_tla_end{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=\"COMPLETED\",status=\"SUCCESS\"}<0) by (wf_group)",
     "legendFormat": "{{ wf_group }} "
    },
    {
     "expr": "max(ctl_wf_loading_tla_end{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=\"COMPLETED\",status=\"SUCCESS\"}>=0) by (wf_group)",
     "legendFormat": "{{ wf_group }} "
    }
   ]
  },
  {
   "title": "wf_group difference of TLA Start TIME",
   "type": "heatmap",
   "description": "Максимальное отклонение от запланированномо времени старта расчета среди всех потоков группы\n[<0 - старт поже], [>0 - старт раньше]",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "min(ctl_wf_loading_tla_start{system=\"$system\",wf_group=~\"$wf_group\",alive=\"COMPLETED\",status=\"SUCCESS\"}<0) by (wf_group)",
     "legendFormat": "{{ wf_group }} "
    },
    {
     "expr": "max(ctl_wf_loading_tla_start{system=\"$system\",wf_group=~\"$wf_group\",alive=\"COMPLETED\",status=\"SUCCESS\"}>=0) by (wf_group)",
     "legendFormat": "{{ wf_group }} "
    }
   ]
  },
  {
   "title": "wf_group difference of TLA End TIME",
   "type": "heatmap",
   "description": "Максимальное отклонение от запланированномо времени окончания расчета среди всех потоков группы\n[<0 - окончание поже], [>0 - окончание раньше]",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "min(ctl_wf_loading_tla_end{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=\"COMPLETED\",status=\"SUCCESS\"}<0) by (wf_group)",
     "legendFormat": "{{ wf_group }} "
    },
    {
     "expr": "max(ctl_wf_loading_tla_end{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=\"COMPLETED\",status=\"SUCCESS\"}>=0) by (wf_group)",
     "legendFormat": "{{ wf_group }} "
    }
   ]
  },
  {
   "title": "TLA end quantile=$quantile",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time ($quantile,(avg(min(ctl_wf_loading_tla_end_status{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=\"SUCCESS\"}) by (wf_name)) by (system))[10m:])",
     "legendFormat": "tla end median"
    }
   ]
  },
  {
   "title": "TLA start quantile=$quantile ",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time ($quantile,(avg(min(ctl_wf_loading_tla_start_status{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=\"SUCCESS\"}) by (wf_name)) by (system))[10m:])",
     "legendFormat": "tla start median"
    }
   ]
  },
  {
   "title": "WF_GROUP Status by wf_group wf_group=[$wf_group]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "WF FINISHED statistic",
   "type": "table",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "count(count(changes(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",}[$__range:])) by (wf_group,wf_name)) by (wf_group)"
    },
    {
     "expr": "avg_over_time(min(ctl_wf_loading_tla_end_status{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=\"SUCCESS\"}) by (wf_group)[1d:])",
     "legendFormat": "{{ wf_group }}"
    },
    {
     "expr": "avg_over_time(min(ctl_wf_loading_tla_end_status{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=\"SUCCESS\"}) by (wf_group)[7d:])",
     "legendFormat": "{{ wf_group }}"
    },
    {
     "expr": "sum(changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\"}) by (wf_group,wf_name)[$__range:]) +1) by (wf_group)",
     "legendFormat": "{{ wf_group }}"
    },
    {
     "expr": "sum(changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=\"ERROR\"}) by (wf_group,wf_name)[$__range:]) +1) by (wf_group)",
     "legendFormat": "{{ wf_group }}"
    },
    {
     "expr": "sum(changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status!=\"ERROR\",status!=\"SUCCESS\"}) by (wf_group,wf_name)[$__range:]) +1) by (wf_group)",
     "legendFormat": "{{ wf_group }}"
    },
    {
     "expr": "sum(changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=\"SUCCESS\"}) by (wf_group,wf_name)[$__range:]) +1) by (wf_group)",
     "legendFormat": "{{ wf_group }}"
    },
    {
     "expr": "sum(changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=\"SUCCESS\"}) by (wf_group,wf_name)[$__range:]) +1) by (wf_group)/ sum(changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\"}) by (wf_group,wf_name)[$__range:]) +1) by (wf_group)",
     "legendFormat": "{{ wf_group }}"
    },
    {
     "expr": "max_over_time(max(ctl_wf_loading_status{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_group)[$__range:])",
     "legendFormat": "{{ wf_group }}"
    }
   ]
  },
  {
   "title": "WF FINISHED  count ERRORs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=\"ERROR\"}) by (system,wf_group)[$interval:]) +1",
     "legendFormat": "{{ wf_group }} "
    }
   ]
  },
  {
   "title": "WF FINISHED  count ABORTED",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "changes(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"ABORTED\"}) by (system,wf_group)[$interval:]) +1",
     "legendFormat": "{{ wf_group }} "
    }
   ]
  },
  {
   "title": "FINISHED status [  1:8 - RUNNING  ], [  9-SUCCESS  ], [  10:11-ERROR  ]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(ctl_wf_loading_status{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_group)",
     "legendFormat": "{{ wf_group }}",
     "requestId": "1149A"
    }
   ]
  },
  {
   "title": "FINISHED status [  1:8 - RUNNING  ], [  9-SUCCESS  ], [  10:11-ERROR  ]",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "ctl_wf_loading_status{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=~\"$status\"}"
    }
   ]
  },
  {
   "title": "WF SUMMARY Table wf_group=[$wf_group]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "wf_group=[  $wf_group  ]  finalAlive=[$finalAlive] last FINISHED run",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "max_over_time(max(ctl_wf_loading_start{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=~\"$status\"} < ctl_wf_loading_end{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)[$__range:]) * 1000"
      },
      {
       "expr": "max_over_time(max(ctl_wf_loading_start_plan{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)[$__range:]) * 1000"
      },
      {
       "expr": "max_over_time(max(ctl_wf_loading_end{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=~\"$status\"}>ctl_wf_loading_start{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",}) by (wf_name,wf_group,alive,status)[$__range:]) * 1000"
      },
      {
       "expr": "max_over_time(max(ctl_wf_loading_end_plan{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)[$__range:]) * 1000"
      },
      {
       "expr": "max_over_time(max(ctl_wf_loading_tla_start{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)[$__range:])"
      },
      {
       "expr": "max_over_time(max(ctl_wf_loading_tla_end{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)[$__range:])"
      },
      {
       "expr": "max_over_time(max(ctl_wf_loading_duration{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)[$__range:])"
      },
      {
       "expr": "max_over_time(max(ctl_wf_loading_status{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)[$__range:])"
      },
      {
       "expr": "max_over_time(max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)[$__range:])"
      },
      {
       "expr": "avg_over_time(max(ctl_wf_loading_tla_start_status{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)[$__range:])"
      },
      {
       "expr": "avg_over_time(max(ctl_wf_loading_tla_end_status{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)[$__range:])"
      }
     ]
    },
    {
     "title": "wf_group=[  $wf_group  ]  alive=[$alive]  status=[$status]  lust 5 min loading",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "max(ctl_wf_loading_start{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$alive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status) * 1000"
      },
      {
       "expr": "max(ctl_wf_loading_start_plan{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$alive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status) * 1000"
      },
      {
       "expr": "max(ctl_wf_loading_end{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$alive\",status=~\"$status\"} > ctl_wf_loading_start{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$alive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status) * 1000"
      },
      {
       "expr": "max(ctl_wf_loading_end_plan{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$alive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status) * 1000"
      },
      {
       "expr": "max(ctl_wf_loading_tla_start{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$alive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)"
      },
      {
       "expr": "max(ctl_wf_loading_tla_end{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$alive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)"
      },
      {
       "expr": "max(ctl_wf_loading_duration{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$alive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)"
      },
      {
       "expr": "max(ctl_wf_loading_status{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$alive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)"
      },
      {
       "expr": "max(ctl_wf_loading_id{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$alive\",status=~\"$status\"}) by (wf_name,wf_group,alive,status)"
      }
     ]
    }
   ]
  },
  {
   "title": "WF TLA  in wf_group=[$wf_group]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "TLA Start TIME by wf_name",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(ctl_wf_loading_tla_start{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=\"SUCCESS\"}) by (wf_name,wf_group)",
       "legendFormat": "{{ wf_name }} "
      }
     ]
    },
    {
     "title": "TLA End TIME by wf_name",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(ctl_wf_loading_tla_end{system=\"$system\",wf_group=~\"$wf_group\",wf_name=~\"$wf_name\",alive=~\"$finalAlive\",status=\"SUCCESS\"}) by (wf_name,wf_group)",
       "legendFormat": "{{ wf_name }} "
      }
     ]
    }
   ]
  },
  {
   "title": "WF STATUS in wf_group=[$wf_group]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "FINISHED status 1-INIT, 2-PREREQ, 3-PARAM, 4-TIME-WAIT, 5-EVENT-WAIT, 6-LOCK-WAIT, 7-START, 8-RUNNING, 9-SUCCESS, 10-ERROR, 11-ERRORCHECK",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "ctl_wf_loading_status{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=~\"$status\"}",
       "legendFormat": "{{ wf_name }} {{ alive }} {{ status }}",
       "requestId": "1149A"
      }
     ]
    },
    {
     "title": "FINISHED status 1-INIT, 2-PREREQ, 3-PARAM, 4-TIME-WAIT, 5-EVENT-WAIT, 6-LOCK-WAIT, 7-START, 8-RUNNING, 9-SUCCESS, 10-ERROR, 11-ERRORCHECK",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
     "targets": [
      {
       "expr": "ctl_wf_loading_status{system=\"$system\",wf_group=~\"$wf_group\",alive=~\"$finalAlive\",status=~\"$status\"}"
      }
     ]
    },
    {
     "title": "ACTIVE status 1-INIT, 2-PREREQ, 3-PARAM, 4-TIME-WAIT, 5-EVENT-WAIT, 6-LOCK-WAIT, 7-START, 8-RUNNING, 9-SUCCESS, 10-ERROR, 11-ERRORCHECK",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
     "targets": [
      {
       "expr": "ctl_wf_loading_status{system=\"$system\",wf_group=~\"$wf_group\",alive=\"ACTIVE\",status=~\"$status\"}"
      }
     ]
    }
   ]
  }
 ]
}