{
 "title": "[SERVICE] Oracle",
 "tags": [
  "service",
  "oracle"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "5m,10m,15m,30m,1h" },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   { "name": "service", "query": "label_values(service)" },
   {
    "name": "instance",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   },
   { "name": "metrics", "query": "metrics(^oracle_sys)" },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   {
    "name": "alert_group",
    "query": "label_values(ALERTS_FOR_STATE,alert_group)"
   },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{alert_group=~\"$alert_group\",},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   { "name": "threshold_cores", "query": "-1,0,1,2,5,10,50,100" },
   { "name": "threshold_mem", "label": "threshold_mem GB", "query": "-1,0,1,2,5,10,20,50,100,500" },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" }
  ]
 },
 "panels": [
  {
   "title": "[$system][$service] Service summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "oracle_sys_cpu",
   "type": "graph",
   "description": "Процент использования CPU сервером в целом",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_cpu{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_dbcpu",
   "type": "graph",
   "description": "Процент использования CPU только базой данных",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_dbcpu{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_dbtime",
   "type": "graph",
   "description": "Суммарное активное время (DB Time) всех сессий в БД, выраженное в %CPU",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_dbtime{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_syspct",
   "type": "graph",
   "description": "Процент времени, в которое сервер работал в режиме ядра",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_syspct{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_read",
   "type": "graph",
   "description": " Средняя интенсивность чтения суммарно по всей БД, МБ/сек\t",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_read{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_write",
   "type": "graph",
   "description": "Средняя интенсивность записи суммарно по всей БД, МБ/сек",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_write{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_redo",
   "type": "graph",
   "description": "Средняя интенсивность генерации журналов транзакций, МБ/сек",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_redo{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_rmwait",
   "type": "graph",
   "description": "Среднее суммарное время ожидания в очереди Resource Manager, выраженное в %CPU",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_rmwait{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_actsess_max",
   "type": "graph",
   "description": "Максимальное количество одновременно активных сессий в БД",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_actsess_max{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_actsess_avg",
   "type": "graph",
   "description": "Среднее количество одновременно активных сессий в БД",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_actsess_avg{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_pga",
   "type": "graph",
   "description": "Средний объем использованного PGA, Мб",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_pga{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_pxruns",
   "type": "graph",
   "description": "Количество запросов за период, запущенных в параллельном режиме\t",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_pxruns{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_pxqct",
   "type": "graph",
   "description": "Среднее количество сессий-координаторов параллельных запросов",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_pxqct{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_pxsrvt",
   "type": "graph",
   "description": "Среднее количество подчиненных параллельных сессий",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_pxsrvt{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_iowait",
   "type": "graph",
   "description": "Среднее время ожидания ввода-вывода, выраженное в %CPU",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_iowait{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_race",
   "type": "graph",
   "description": "Среднее время ожидания при конкуренции за ресурсы, выраженное в %CPU",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_race{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_undousg",
   "type": "graph",
   "description": "Текущий размер использованного UNDO (active+unexpired)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_undousg{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_tempusg",
   "type": "graph",
   "description": "Текущий размер использованного временного табличного пространства",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_tempusg{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_cpupeak",
   "type": "graph",
   "description": "Пиковое значение CPU в %, потребляемого сервером в среднем за 1 минуту",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_cpupeak{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oracle_sys_dbcpupeak",
   "type": "graph",
   "description": "Пиковое значение CPU в %, потребляемого только базой данных в среднем за 1 минуту",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "oracle_sys_dbcpupeak{system=~\"$system\",instance=~\"$instance\",service=~\"$service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}