{
 "title": "[SERVICE] LDAP",
 "tags": [
  "service",
  "ldap"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" },
   { "name": "service", "query": "label_values(service)" },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   {
    "name": "instance",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   },
   {
    "name": "errors",
    "query": "label_values(ldap_replication_nsds5replicaLastUpdateStatus{},text)"
   },
   {
    "name": "type",
    "query": "label_values(ldap_connection_duration{},bind)"
   },
   {
    "name": "bind",
    "query": "label_values(ldap_connection_duration{bind=~\"$type.*\"},bind)"
   },
   { "name": "count", "query": "0,1,2,3,5,10,15" },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   {
    "name": "alert_group",
    "query": "label_values(ALERTS_FOR_STATE,alert_group)"
   },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{alert_group=~\"$alert_group\",},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" },
   {
    "name": "regexp",
    "label": "regexp for FQDN",
    "query": "([a-zA-Z0-9]+[-a-zA-Z0-9]+)[.].+ , (.+)"
   },
   {
    "name": "mountpoint",
    "label": "mountpoint !=",
    "query": "label_values({system=~\"$system\",instance=~\"$instance_list\",fstype=~\"ext4|xfs\"},mountpoint)"
   },
   { "name": "metrics", "label": "raw metric", "query": "metrics(^hadoop_$service)" },
   {
    "name": "instance_list",
    "query": "label_values({system=~\"$system\",service=~\"$service\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Readme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Описание",
     "type": "text",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
     "content": "\n## Описание дашборда\n\nДанный шаблон отображает основные метрики собираемые с\n- exporter-node\n- exporter-jmx\n\nБлоки Summary содержат информацию о всех инстансах сервиса. Остальные блоки фильтруют информацию по полю instance\n\n#### переменные\n- ds - выбор датасорса(prometheus) из которого запрашивать данные для отображения(подробнее про типы прометеусов см https://confluence.ca.sbrf.ru/pages/editpage.action?pageId=2383122863)\n- system - имя системы\n- quantile - значение персентия для расчета значений в таблицах\n- last - период вермени отображения метрик для таблиц(чтобы не делать тяжелые расчеты на больших выборках)\n- regexp for FQDN - regexp для отсекания FQDN имен на графиках (экономия используемого места дашборда)\n- ountpoint != список точек монтирования, которые НЕ интересны для мониторинга(не учитывать в TopK селектах по утилизации файловых систем)\n- raw metric - выбрать метрику для отображения ее в \"сыром\" виде в блоке RAW METRICS (возможность для пользователя посмотрить метрки данного сервиса отсутствующие на дашборде, аналогичный функционал в меню графаны EXPLORE\n\n\n#### drill down links\n- из таблиц возможен переход по имени инстанса на более подробный дашборд по выбранному инстансу\n\n\n\n### Тиражирование\nМожет быть использован как основа дашборда по новым сервисам, при этом ненужные элементы дашборда(графики, таблицы) могут быть удалены.\nНапример оставить график по использовании памяти в %, но удалить график по использовании памяти в GB, т.к. избыточная информация.\nАдминистрато сервиса должен удостовериться и подтвердитьь что присутствуют все необходимые метрики и отсутствуют все мало значимые метрики.\n\n\nТак же можно менять визуализацию лейблов, например: не отображать столбик max/avg на графиках, менять толщину линий и степень заливки, содержание подписей и т.д.\n\nДля систем с более чем 50 хостами - может потребоваться дополнтиельная настройка значений переменных instance и instance_list (дефалтофое значение для выбора All)\n\n#### при тиражировании данное и все остальные описания или удалить или оставить только актуальные комментарии\n\n\n\n"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "$service exporter $instance errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(ldap_exporter_errors_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$last])"
    }
   ]
  },
  {
   "title": "LDAP $instance Read waiters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "repeat": "instance",
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "max(ldap_monitor_readwaiters{instance=~\"$instance\",system=~\"$system\",service=~\"$service\"}) by (system,service)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "LDAP $instance Current connections ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ldap_monitor_currentconnections{instance=~\"$instance\",system=~\"$system\",service=~\"$service\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "topk connections",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "topk(7,count(ldap_connection_duration{instance=~\"$instance\"}) by (bind))"
    }
   ]
  },
  {
   "title": "$service exporter $instance errors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "delta(ldap_exporter_errors_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$last])"
    }
   ]
  },
  {
   "title": "LDAP $instance Read waiters",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "max(ldap_monitor_readwaiters{instance=~\"$instance\",system=~\"$system\",service=~\"$service\"}) by (system,service)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "LDAP $instance Current connections ",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(ldap_monitor_currentconnections{instance=~\"$instance\",system=~\"$system\",service=~\"$service\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$service ldap server version",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(ldap_replication_nsds5replicaLastUpdateStatus{instance=~\"$instance\",system=~\"$system\",service=~\"$service\"}) by (instance,text)"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(ldap_server_version{system=\"$system\",instance=~\"$instance\"}) by (instance, version)",
     "legendFormat": "{{instance}} {{version}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(ldap_replication_nsds5replicaLastUpdateEnd{system=\"$system\",instance=~\"$instance\"}*1000) by (instance)",
     "legendFormat": "{{instance}} {{version}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ]  connections summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "currentconnection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(ldap_monitor_currentconnections{system=~\"$system\",instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{ instance }} currentconnections"
      }
     ]
    },
    {
     "title": "connections group",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "max(ldap_connection_duration{instance=~\"$instance\",bind=~\"$bind\",bind=~\"$type.*\"}*1000) by (instance,bind)"
      },
      {
       "expr": "count(max(ldap_connection_duration{instance=~\"$instance\",bind=~\"$bind\",bind=~\"$type.*\"}) by (instance,bind,id))by (instance,bind)"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] connections details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "connections details",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "max(ldap_connection_duration{instance=~\"$instance\",bind=~\"$bind\",bind=~\"$type.*\"}*1000) by (instance,bind,id)"
      },
      {
       "expr": "count(max(ldap_connection_duration{instance=~\"$instance\",bind=~\"$bind\",bind=~\"$type.*\"}) by (instance,bind,id))by (instance,bind,id)"
      }
     ]
    },
    {
     "title": "$instance top5 connections count > $count",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, count(max(ldap_connection_duration{bind=~\"$bind\",bind=~\"$type.*\"}) by (instance,bind,id))by (instance,bind) > $count)",
       "legendFormat": " {{ bind }}"
      }
     ]
    },
    {
     "title": "$instance top5 connections count > $count",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, count(max(ldap_connection_duration{bind=~\"$bind\",bind=~\"$type.*\"}) by (instance,bind,id))by (instance,bind) > $count)",
       "legendFormat": " {{ bind }}"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ]  ldap cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "ldap_ldbm_changelog",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ldap_ldbm_changelog_currentdncachecount{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current dn cache count"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_currententrycachecount{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current entry cache count"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_currententrycachecount{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current entry cache count"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_currentnormalizeddncachecount{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current normalized dn cache count"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_dncachehitratio{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} dn cache hit ratio"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_dncachehits_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} dn cache hits total"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_dncachetries_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} dn cache tries_total"
      }
     ]
    },
    {
     "title": "$service current cache size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(ldap_ldbm_changelog_currentdncachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current dn cache size"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_currententrycachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current entry cache size"
      },
      {
       "expr": "irate(ldap_ldbm_changelog_currentnormalizeddncachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current normalized dn cache size"
      },
      {
       "expr": "irate(ldap_ldbm_changelog_maxdncachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} max dn cache size"
      },
      {
       "expr": "irate(ldap_ldbm_changelog_maxentrycachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} max entry cache size"
      },
      {
       "expr": "irate(ldap_ldbm_changelog_maxnormalizeddncachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} max normalized dn cache size"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU%",
     "type": "singlestat",
     "description": "$service -  avg Host system CPU% Utilization over all hosts",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"idle\",}[$interval])) by(system,instance)) by (system,service)"
      }
     ]
    },
    {
     "title": "CPU% User",
     "type": "singlestat",
     "description": "$service -  avg Host system CPU% user Utilization over all hosts",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"user\"}[$interval]))"
      }
     ]
    },
    {
     "title": "CPU% iowait",
     "type": "gauge",
     "description": "$service -  max Host system CPU% iowait Utilization over all hosts",
     "gridPos": { "h": 6, "w": 2, "x": 6, "y": 18 },
     "targets": [
      {
       "expr": "max_over_time (max(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"iowait\"}[$interval]))[$__range:])",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Cores Total",
     "type": "singlestat",
     "description": "$service -  Summary Cores count",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 18 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{system=~\"$system\", instance=~\"$instance_list\",}) by (cpu,system,instance)) by(system,service)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Mem Total",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 18 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}))"
      }
     ]
    },
    {
     "title": "disk util max read_time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 18 },
     "format": "s",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))",
       "legendFormat": "read"
      }
     ]
    },
    {
     "title": "Top Usage FS",
     "type": "table",
     "description": "Top  most usage File Systems over all hosts\n\nmountpoint  != variable: $mountpoint",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 18 },
     "targets": [
      {
       "expr": "label_replace( topk(5,max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by (instance,mountpoint)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Mem Free Total",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 20 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"}))"
      }
     ]
    },
    {
     "title": "CPU% System",
     "type": "singlestat",
     "description": "$service -  avg Host system CPU%  system Utilization over all hosts",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 21 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg (rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"system\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Nodes Count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 21 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_exporter_build_info{system=~\"$system\", instance=~\"$instance_list\",})"
      }
     ]
    },
    {
     "title": "disk util max write_time",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 13, "y": 21 },
     "format": "s",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))",
       "legendFormat": "write "
      }
     ]
    },
    {
     "title": "Mem%",
     "type": "singlestat",
     "description": "$service -  avg Host system Mem% Utilization over all hosts",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 22 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} \n- (node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"} +\nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"})) / \nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})"
      }
     ]
    },
    {
     "title": "System:[  $system  ] Service:[  $service  ] OS metrics, quantile=$quantile ",
     "type": "table",
     "description": "OS metrics summary table for last $last.\n\nAggregation(quanlile/max/last)  values during last $last\n\nJava/Heap/Pool - means Java application(service) metrics.\n\nYou can change colors threatholds as you wish\n\n",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": " (min(up{system=~\"$system\", instance=~\"$instance_list\", roletype!~\".+\"}) by (system,instance))"
      },
      {
       "expr": "(min(node_boot_time_seconds{system=~\"$system\", instance=~\"$instance_list\", }) by (system,instance))"
      },
      {
       "expr": "count(count(node_cpu_seconds_total{system=~\"$system\", instance=~\"$instance_list\",}) by (cpu,system,instance)) by(system,instance)"
      },
      {
       "expr": "quantile_over_time ($quantile,max(node_load5{system=~\"$system\", instance=~\"$instance_list\",}) by(system,service,instance)[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"idle\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"system\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"user\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"iowait\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"irq\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"softirq\",}[$interval])) by(system,instance))[$__range:])"
      },
      {
       "expr": "max(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by(system,instance)"
      },
      {
       "expr": "max(((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"})) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "min(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,instance)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by(system,instance)"
      },
      {
       "expr": "max_over_time(max by(system,instance) (rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))[$__range:])"
      },
      {
       "expr": "max_over_time(max by(system,instance) (rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))[$__range:])"
      },
      {
       "expr": "(max(node_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by (system,service,instance))"
      },
      {
       "expr": "max (1 - (node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} / on(system,instance)\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by (system,instance)"
      },
      {
       "expr": "sum(irate(node_network_receive_bytes_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))by (system,instance)"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))by (system,instance)"
      },
      {
       "expr": "max((node_netstat_Tcp_CurrEstab{system=~\"$system\",instance=~\"$instance_list\"}))by (system,instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes CPU  - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization % Host Systems ",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"idle\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 1m Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load1{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 5m Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load5{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 15m Host Systems ",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load15{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  System %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"system\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  User %  ]  Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"user\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  IOWait %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"iowait\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Memory - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization% Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\ncurrent formula\n(node_memory_MemTotal_bytes-node_memory_MemFree_bytes-node_memory_Cached_bytes-node_memory_Buffers_bytes ) /\nnode_memory_MemTotal_bytes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Available %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Free %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory Utilization GB Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Available GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Free GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Cached %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Cached GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Buffers %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Buffers GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "[  SWAP Utilization %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max (1 - (node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance\"} / on(system,instance)\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "[  SWAP Utilization GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace( max(\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance\"}-node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance\"}) by (system,instance) , \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Disk & Network - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read/write time seconds",
     "type": "graph",
     "description": "read - negative  Y\nwrite - positive Y",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      {
       "format": "s",
       "label": "disr read s (-) / disk write s (+)"
      }
     ],
     "targets": [
      {
       "expr": "label_replace(sum by(system,instance) (rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-read"
      },
      {
       "expr": "label_replace(sum by(system,instance) (rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-write"
      }
     ]
    },
    {
     "title": "Disk IOps ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_disk_reads_completed_total{system=~\"$system\",instance=~\"$instance\",device=~\"[a-z]*[a-z]\"}[$interval])) by (service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-read"
      },
      {
       "expr": "label_replace(sum(irate(node_disk_writes_completed_total{system=~\"$system\",instance=~\"$instance\",device=~\"[a-z]*[a-z]\"}[$interval])) by (service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-write"
      }
     ]
    },
    {
     "title": "Network transmited/resived time seconds",
     "type": "graph",
     "description": "read - negative  Y\nwrite - positive Y",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Bps", "label": "transmit (-) /resive (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-out"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "description": "irate - packets per second",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-out"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "description": "irate - packets per second",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-out"
      }
     ]
    },
    {
     "title": "TCP Connections count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_netstat_Tcp_CurrEstab{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "UDP In / Out",
     "type": "graph",
     "description": "irate - per second  Datagrams",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(irate(node_netstat_Udp_InDatagrams{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-in"
      },
      {
       "expr": "label_replace(irate(node_netstat_Udp_OutDatagrams{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-out"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "description": "irate - per second  errors",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(irate(node_netstat_Udp_InErrors{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-InErrors"
      },
      {
       "expr": "label_replace(irate(node_netstat_Udp_NoPorts{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-NoPorts"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes FS - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "repeat": "instance_list",
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service] Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 12 },
     "repeat": "alertname",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 12 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Alert List: system:$system, GROUP:$alert_group",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "ALERTS{system=~\"$system\", instance=~\"$instance\",alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"} "
      }
     ]
    }
   ]
  },
  {
   "title": "raw metrics: $metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "$metrics",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "repeat": "metrics",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "$metrics{instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}