{
 "title": "[SERVICE] RTA",
 "tags": [
  "ddrv",
  "service"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,30m,1h,6h,12h,1d" },
   { "name": "service", "query": "label_values(service)" },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   {
    "name": "roletype",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\",service=~\"$service\"},roletype)"
   },
   {
    "name": "instance",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   },
   {
    "name": "name_processors",
    "query": "label_values(rta_broker_jmx_processors_index{instance=~\"$instance\"},name)"
   },
   { "name": "metrics", "query": "metrics(^rta_broker_jmx_)" },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   {
    "name": "alert_group",
    "query": "label_values(ALERTS_FOR_STATE,alert_group)"
   },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{alert_group=~\"$alert_group\",},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   { "name": "last", "query": "15m" },
   { "name": "last_h", "query": "8h" },
   {
    "name": "route_host",
    "query": "label_values(ru_sberbank_bigdata_rta_aggregatedjmxmetric_avgtomaxthrottle{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"},host)"
   },
   {
    "name": "route_name",
    "query": "label_values(ru_sberbank_bigdata_rta_aggregatedjmxmetric_avgtomaxthrottle{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"},name)"
   }
  ]
 },
 "panels": [
  { "title": "Aggregate jmx metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg to max throttle",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_avgtomaxthrottle{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\", name=~\"$route_name\"}"
    }
   ]
  },
  {
   "title": "Count Throttle Message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_countthrottlemessage{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\"}"
    }
   ]
  },
  {
   "title": "Avg Solr Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_avgsolrresponsetime{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\"}"
    }
   ]
  },
  {
   "title": "Count Not Response Message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_countnotresponsemessage{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\"}"
    }
   ]
  },
  {
   "title": "Avg To Max end2end",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_avgtomaxend2end{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\"}"
    }
   ]
  },
  {
   "title": "Count end2end",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_countend2end{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\"}"
    }
   ]
  },
  {
   "title": "Avg end2end Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_avgend2endtime{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\"}"
    }
   ]
  },
  {
   "title": "Avg Throttle Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_avgthrottletime{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\"}"
    }
   ]
  },
  {
   "title": "Max Solr Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_maxsolrresponsetime{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\"}"
    }
   ]
  },
  {
   "title": "Build Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_buildtime{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\"}"
    }
   ]
  },
  {
   "title": "Max end2end Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_maxend2endtime{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\"}"
    }
   ]
  },
  {
   "title": "Count ErrorCode Message",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ru_sberbank_bigdata_rta_aggregatedjmxmetric_counterrorcodemessage{system=~\"$system\", instance=~\"$instance\", host=~\"$route_host\"}"
    }
   ]
  },
  {
   "title": "$metrics $instance raw metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "cl:[$system] service:[$service] JMX current status",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "$metrics{instance=~\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service] Service summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "$service processcpuload max",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 9, "x": 5, "y": 2 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\"}) by (system,service)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Services %physical Mem util max",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 10, "x": 14, "y": 2 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "max(1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\"} / \non(system,service,roletype,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\"})) \nby (system,service)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "cl:[$system] service:[$service] JMX current status",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "(max(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,service,roletype,instance))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "(max(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,service,roletype,instance))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": " max(1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} / \non(system,service,roletype,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})) \nby (system,instance,roletype,service)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "max (1 - (jmx_java_lang_operatingsystem_freeswapspacesize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} / on(system,service,roletype,instance)\njmx_java_lang_operatingsystem_totalswapspacesize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})) by (system,service,roletype,instance)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "max(jmx_java_lang_memory_heapmemoryusage_max{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,service,roletype,instance)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "heap",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "max(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} / jmx_java_lang_memory_heapmemoryusage_max{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,service,roletype,instance)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "heap",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service] Nodes summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_exporter_build_info{system=~\"$system\", instance=~\"$instance_list\"})"
      }
     ]
    },
    {
     "title": "CPU% System",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 3, "y": 3 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "quantile_over_time ($quantile, avg by (system, service,mode) (rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"system\"}[$interval]))[$__range:])"
      }
     ]
    },
    {
     "title": "CPU% Util",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 3 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "max(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[$interval])) by (system)"
      }
     ]
    },
    {
     "title": "CPU% iowait",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 3, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "quantile_over_time ($quantile, avg by (system, mode) (rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"iowait\"}[$interval]))[$__range:])",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Mem Free Total",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 15, "y": 3 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}) by(system))"
      }
     ]
    },
    {
     "title": "disk util max read_time",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
     "format": "s",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))",
       "legendFormat": "read"
      }
     ]
    },
    {
     "title": "CPU% User",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 3, "y": 5 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "quantile_over_time ($quantile, avg by (system, mode) (rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"user\"}[$interval]))[$__range:])"
      }
     ]
    },
    {
     "title": "mem% util",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 15, "y": 5 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "max((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} \n- (node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"} +\nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"})) / \nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"}) by(system,service,instance)"
      }
     ]
    },
    {
     "title": "disk util max write_time",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
     "format": "s",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))",
       "legendFormat": "write "
      }
     ]
    },
    {
     "title": "cl:[$system] OS current status",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "count(count(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\"}) by (cpu,system,instance)) by(system,instance)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "quantile_over_time ($quantile,max(node_load1{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)[$__range:])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "quantile_over_time ($quantile,max(node_load5{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)[$__range:])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "quantile_over_time ($quantile,max(node_load15{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)[$__range:])",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "max(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[$interval])) by(system,instance)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "max(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "min(100 - ((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"} * 100) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service]  routers time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "cl:[$system] service:[$service] instance:[$instance] time table  ",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "max(rta_broker_jmx_routes_max_processing_time{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}}"
      },
      {
       "expr": "min(rta_broker_jmx_routes_min_processing_time{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}}"
      },
      {
       "expr": "max(rta_broker_jmx_routes_last_processing_time{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\" ,name=~\"$name_routes\"}) by (system,instance,name)",
       "legendFormat": "{{instance}} {{name}}"
      },
      {
       "expr": "max(rta_broker_jmx_routes_mean_processing_time{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}}"
      },
      {
       "expr": "max((rta_broker_jmx_routes_uptime_millis{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"})) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}} "
      }
     ]
    },
    {
     "title": "cl:[$system] service:[$service] instance:[$instance]  routes mean processing time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(rta_broker_jmx_routes_mean_processing_time{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}) by (system,instance,name)> 0",
       "legendFormat": "{{instance}} {{name}}"
      }
     ]
    },
    {
     "title": "cl:[$system] service:[$service] instance:[$instance]  routes last processing time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "max(rta_broker_jmx_routes_last_processing_time{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\" ,name=~\"$name_routes\"}) by (system,instance,name) > 0",
       "legendFormat": "{{instance}} {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service]  processors time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "cl:[$system] service:[$service] instance:[$instance] time table  ",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "max(rta_broker_jmx_processors_max_processing_time{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_processors\"}) by (system,instance,name)",
       "legendFormat": "{{instance}} {{name}}"
      },
      {
       "expr": "min(rta_broker_jmx_processors_min_processing_time{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_processors\"}) by (system,instance,name)",
       "legendFormat": "{{instance}} {{name}}"
      },
      {
       "expr": "max(rta_broker_jmx_processors_last_processing_time{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\" ,name=~\"$name_processors\"}) by (system,instance,name)",
       "legendFormat": "{{instance}} {{name}}"
      },
      {
       "expr": "max(rta_broker_jmx_processors_mean_processing_time{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_processors\"}) by (system,instance,name)",
       "legendFormat": "{{instance}} {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service] routers exchanges",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "cl:[$system] service:[$service] $instance  exchanges table",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "max(delta(rta_broker_jmx_routes_exchanges_total{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}[$__range:])) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}} exchanges total"
      },
      {
       "expr": "max(delta(rta_broker_jmx_routes_exchanges_completed{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}[$__range:])) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}} exchanges completed"
      },
      {
       "expr": "max(delta(rta_broker_jmx_routes_exchanges_inflight{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}[$__range:])) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}} exchanges inflight"
      },
      {
       "expr": " max(delta(rta_broker_jmx_routes_exchanges_failed{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}[$__range:])) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}} exchanges failed"
      }
     ]
    },
    {
     "title": "cl:[$system] service:[$service] $instance exchanges graph",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(increase(rta_broker_jmx_routes_exchanges_failed{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}[10m]) > 0 ) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}} exchanges failed"
      },
      {
       "expr": "max(rate(rta_broker_jmx_routes_exchanges_inflight{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}[10m]) > 0) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}} exchanges inflight"
      },
      {
       "expr": "max(increase(rta_broker_jmx_routes_exchanges_completed{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}[10m]) ) by (system,instance,name) ",
       "legendFormat": "{{name}} exchanges completed"
      },
      {
       "expr": "max(increase(rta_broker_jmx_routes_exchanges_total{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}[10m]) ) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}} exchanges total"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service] routers statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "cl:[$system] service:[$service] $instance router's metrics table",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "max(rta_broker_jmx_routes_external_redeliveries{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}} external_redeliveries"
      },
      {
       "expr": "max(rta_broker_jmx_routes_redeliveries{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}} external_redeliveries"
      },
      {
       "expr": "max(rta_broker_jmx_routes_failures_handled{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\",name=~\"$name_routes\"}) by (system,instance,name) ",
       "legendFormat": "{{instance}} {{name}} external_redeliveries"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service] traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic by Packets",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_packets_total{system=~\"$system\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{ instance }} int:{{device}} - Receive"
      },
      {
       "expr": "irate(node_network_transmit_packets_total{system=~\"$system\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{ instance }} int:{{device}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{device}} - Receive errors"
      },
      {
       "expr": "irate(node_network_transmit_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{device}} - Rransmit errors"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "irate(node_network_receive_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} int:{{device}} - Receive drop"
      },
      {
       "expr": "irate(node_network_transmit_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} int:{{device}} - Transmit drop"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service] Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 28 },
     "repeat": "alertname",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 28 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Список текущих аварий: $system, $alert_group",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "ALERTS{system=~\"$system\", instance=~\"$instance\"} "
      }
     ]
    }
   ]
  },
  {
   "title": "Статистика: ОС",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "System average load",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{system=~\"$system\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}} load 1m"
      },
      {
       "expr": "node_load5{system=~\"$system\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}} load 5m"
      },
      {
       "expr": "node_load15{system=~\"$system\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}} load 15m"
      }
     ]
    },
    {
     "title": "$instance Memory Basic",
     "type": "graph",
     "description": "Basic memory usage",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}} RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}} RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} \n+ node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}} RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}} RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}} SWAP Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Статистика:FS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance Free space for each partition",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 17 },
     "repeat": "instance",
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes {system=~\"$system\",instance=~\"$instance\",fstype=~\"ext4|xfs\"}"
      },
      {
       "expr": "1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance\",fstype=~\"ext4|xfs\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "JMX CPU&Mem info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Pool Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_memorypool_usage_used{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}:{{type}} memorypool used",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory Heap ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}:{{type}} committed"
      },
      {
       "expr": "jmx_java_lang_memory_heapmemoryusage_max{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}:{{type}} max"
      },
      {
       "expr": "jmx_java_lang_memory_heapmemoryusage_init{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}:{{type}} init"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} * 100",
       "legendFormat": "{{instance}}:{{type}} SystemLoad"
      },
      {
       "expr": "jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} * 100",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}:{{type}} ProcessCpuTime",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "JMX Additional info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_threading_threadcount{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}:{{roletype}}  threadcount"
      },
      {
       "expr": "jmx_java_lang_threading_daemonthreadcount{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}:{{roletype}} daemonthreadcount "
      },
      {
       "expr": "jmx_java_lang_threading_peakthreadcount{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}:{{roletype}}  peakthreadcount"
      }
     ]
    },
    {
     "title": "Class loading",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 9, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_classloading_totalloadedclasscount{system=~\"$system\",roletype=~\"$roletype\", instance=~\"$instance\"}",
       "legendFormat": " {{instance}} {{roletype}} Total Loaded Class"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_operatingsystem_openfiledescriptorcount{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}}:{{roletype}} Open File Descriptor ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_garbagecollector_collectiontime{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}:{{roletype}} Garbage Collector "
      }
     ]
    },
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 11, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_garbagecollector_collectioncount{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}:{{roletype}} Garbage Collector Count"
      }
     ]
    }
   ]
  }
 ]
}