{
 "title": "[SERVICE] LDAP",
 "description": "Dashboard for ldap",
 "tags": [
  "service",
  "ldap"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "es", "query": "elasticsearch" },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" },
   { "name": "service", "query": "ldap" },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   {
    "name": "instance",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   },
   {
    "name": "type",
    "query": "fqdn,uid,cn,,krbprincipalname,NULLDN"
   },
   {
    "name": "bind",
    "query": "query_result(count by (bind) (count_over_time(ldap_connection_duration{bind=~\"$type.*\"}[$last])))"
   },
   { "name": "count", "query": "0,1,2,3,5,10,15" },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{system=~\"$system\",service=~\"$service\"},alertname)"
   },
   { "name": "severity", "query": "0,1,2,3" },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" },
   {
    "name": "regexp",
    "label": "regexp for FQDN",
    "query": "([a-zA-Z0-9]+[-a-zA-Z0-9]+)[.].+ , (.+)"
   },
   {
    "name": "mountpoint",
    "label": "mountpoint !=",
    "query": "label_values(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance\",fstype=~\"ext4|xfs\"},mountpoint)"
   },
   {
    "name": "instance_list",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "[ $system ] - [ $service ] Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 19, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(delta(ldap_exporter_errors_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Read waiters",
   "type": "stat",
   "gridPos": { "h": 19, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(max(ldap_monitor_readwaiters{instance=~\"$instance\",system=~\"$system\",service=~\"$service\"}) by (system,service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "connections ",
   "type": "stat",
   "gridPos": { "h": 19, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(max(ldap_monitor_currentconnections{instance=~\"$instance\",system=~\"$system\",service=~\"$service\"}) by (system,service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "service status",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "label_replace((max(node_systemd_unit_state{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"dirsrv.*service\", state=\"active\"}) by (instance)),\n \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "dirsrv.*service"
    },
    {
     "expr": "label_replace((max(node_systemd_unit_state{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"pki-tomcatd.*service\", state=\"active\"}) by (instance)),\n \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "krb5kdc.service"
    },
    {
     "expr": "label_replace((max(node_systemd_unit_state{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"ipa-dnskeysyncd.service\", state=\"active\"}) by (instance)),\n \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "ipa-dnskeysyncd.service"
    },
    {
     "expr": "label_replace((max(node_systemd_unit_state{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"krb5kdc.service\", state=\"active\"}) by (instance)),\n \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "krb5kdc.service"
    },
    {
     "expr": "label_replace((max(node_systemd_unit_state{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=~\"ipa.service\", state=\"active\"}) by (instance)),\n \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "ipa.service"
    }
   ]
  },
  {
   "title": "LDAP rerplica warnings (Error!=0)",
   "type": "graph",
   "description": " Replication error acquiring replica:",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(count by (instance) (ldap_replication_nsds5replicaLastUpdateStatus{text!~\"Error .0..*\"}) or vector(0), \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "alerts count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", system=~\"$system\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "LDAP connection duration sum",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by(system,servce,instance) (rate(ldap_connection_duration{system=~\"$system\", service=~\"$service\", instance=~\"$instance\"}[$interval])) > 0, \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "topk connection duration",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5,rate(ldap_connection_duration{system=~\"$system\", service=~\"$service\",instance=~\"$instance\"}[$interval]))",
     "legendFormat": "{{ bind }}"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ]  Connections summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "LDAP connection duration sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(sum by(system,servce,instance) (rate(ldap_connection_duration{system=~\"$system\", service=~\"$service\", instance=~\"$instance\"}[$interval])) > 0, \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "LDAP connections count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(ldap_monitor_currentconnections{system=~\"$system\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "LDAP connection duration bind ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace((rate(ldap_connection_duration{system=~\"$system\", service=~\"$service\", instance=~\"$instance\"}[$interval])) > 0, \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{ instance }} : {{ bind }}"
    }
   ]
  },
  {
   "title": "KDC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ISSUE",
     "bucketAggs": [
      {
       "$$hashKey": "object:794",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:792", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host_h.name: $instance AND source:  \"/var/log/krb5kdc.log\" AND message: \"ISSUE\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "NEEDED_PREAUTH",
     "bucketAggs": [
      {
       "$$hashKey": "object:812",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:810", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host_h.name: $instance AND source:  \"/var/log/krb5kdc.log\" AND message: \"NEEDED_PREAUTH\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "PREAUTH_FAILED",
     "bucketAggs": [
      {
       "$$hashKey": "object:830",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:828", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host_h.name: $instance AND source:  \"/var/log/krb5kdc.log\" AND message: \"PREAUTH_FAILED\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Disk & Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read/write time seconds",
     "type": "graph",
     "description": "read - negative  Y\nwrite - positive Y",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      {
       "format": "s",
       "label": "disr read s (-) / disk write s (+)"
      }
     ],
     "targets": [
      {
       "expr": "label_replace(sum by(system,instance) (rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-read"
      },
      {
       "expr": "label_replace(sum by(system,instance) (rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-write"
      }
     ]
    },
    {
     "title": "Disk IOps ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_disk_reads_completed_total{system=~\"$system\",instance=~\"$instance\",device=~\"[a-z]*[a-z]\"}[$interval])) by (service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-read"
      },
      {
       "expr": "label_replace(sum(irate(node_disk_writes_completed_total{system=~\"$system\",instance=~\"$instance\",device=~\"[a-z]*[a-z]\"}[$interval])) by (service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-write"
      }
     ]
    },
    {
     "title": "Network transmited/resived time seconds",
     "type": "graph",
     "description": "read - negative  Y\nwrite - positive Y",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "Bps", "label": "transmit (-) /resive (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-out"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "description": "irate - packets per second",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-out"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "description": "irate - packets per second",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 55 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-out"
      }
     ]
    },
    {
     "title": "TCP Connections count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_netstat_Tcp_CurrEstab{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "UDP In / Out",
     "type": "graph",
     "description": "irate - per second  Datagrams",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 64 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(irate(node_netstat_Udp_InDatagrams{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-in"
      },
      {
       "expr": "label_replace(irate(node_netstat_Udp_OutDatagrams{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-out"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "description": "irate - per second  errors",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 64 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(irate(node_netstat_Udp_InErrors{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-InErrors"
      },
      {
       "expr": "label_replace(irate(node_netstat_Udp_NoPorts{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-NoPorts"
      }
     ]
    },
    {
     "title": "Network Speed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(node_network_receive_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "RX : {{ instance }}"
      },
      {
       "expr": "label_replace(rate(node_network_transmit_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "TX : {{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Connections details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "connections group",
     "type": "table-old",
     "gridPos": { "h": 12, "w": 16, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "max by  (instance,bind,id) (rate(ldap_connection_duration{instance=~\"$instance\",bind=~\"$bind\",bind=~\"$type.*\"}[$interval]) )"
      }
     ]
    },
    {
     "title": "topk connection count",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(5,count(ldap_connection_duration{instance=~\"$instance\"}) by (bind))",
       "legendFormat": "{{ bind }}"
      }
     ]
    },
    {
     "title": "connections duration >= $count s",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\nmax by(service,system,instance,bind) (rate(ldap_connection_duration{system=~\"$system\", service=~\"$service\", instance=~\"$instance\",bind=~\"$bind\",bind=~\"$type.*\"}[$interval]) >= $count),\r\n \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": " {{ instance }} {{ bind }}"
      }
     ]
    },
    {
     "title": "$instance top5 connections count >= $count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\ntopk(5, count(max(ldap_connection_duration{system=~\"$system\", service=~\"$service\", instance=~\"$instance\",bind=~\"$bind\",bind=~\"$type.*\"}) by (instance,bind,id))by (instance,bind) >= $count),\r\n \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance }} {{ bind }}"
      }
     ]
    }
   ]
  },
  {
   "title": "[ ipa-dev ] - [ ldap ] Replication status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service server version/replica status",
     "type": "table-old",
     "gridPos": { "h": 15, "w": 13, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "max(ldap_replication_nsds5replicaLastUpdateStatus{instance=~\"$instance\",system=~\"$system\",service=~\"$service\"}) by (instance,text)"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "max(ldap_server_version{system=\"$system\",instance=~\"$instance\"}) by (instance, version)",
       "legendFormat": "{{instance}} {{version}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "max(ldap_replication_nsds5replicaLastUpdateEnd{system=\"$system\",instance=~\"$instance\"}*1000) by (instance)",
       "legendFormat": "{{instance}} {{version}}",
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    },
    {
     "title": "LDAP rerplica warning (Error!=0)",
     "type": "graph",
     "description": " Replication error acquiring replica: Incremental update transient warning.  Backing off, will retry update later. (transient warning)",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 48 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (instance,replica_root ) (ldap_replication_nsds5replicaLastUpdateStatus{text!~\"Error .0..*\"}) or vector(0)",
       "legendFormat": "{{ instance }}  {{ replica_root }}"
      }
     ]
    },
    {
     "title": "LDAP rerplica transient warning (retry update)",
     "type": "graph",
     "description": " Replication error acquiring replica: Incremental update transient warning.  Backing off, will retry update later. (transient warning)",
     "gridPos": { "h": 8, "w": 6, "x": 13, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (instance,replica_root ) (ldap_replication_nsds5replicaLastUpdateStatus{text=~\"Error .18..*\"}) or vector(0)",
       "legendFormat": "{{ instance }}  {{ replica_root }}"
      }
     ]
    },
    {
     "title": "LDAP Busy Replica  [1m]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (instance,replica_root,text ) (ldap_replication_nsds5replicaLastUpdateStatus{text=~\"Error .1..*\"}) or vector(0)",
       "legendFormat": "{{ instance }} {{ replica_root}}"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ]  ldap cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "ldap_ldbm_changelog",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(ldap_ldbm_changelog_currentdncachecount{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current dn cache count"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_currententrycachecount{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current entry cache count"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_currententrycachecount{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current entry cache count"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_currentnormalizeddncachecount{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current normalized dn cache count"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_dncachehitratio{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} dn cache hit ratio"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_dncachehits_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} dn cache hits total"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_dncachetries_total{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} dn cache tries_total"
      }
     ]
    },
    {
     "title": "$service current cache size",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(ldap_ldbm_changelog_currentdncachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current dn cache size"
      },
      {
       "expr": "rate(ldap_ldbm_changelog_currententrycachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current entry cache size"
      },
      {
       "expr": "irate(ldap_ldbm_changelog_currentnormalizeddncachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} current normalized dn cache size"
      },
      {
       "expr": "irate(ldap_ldbm_changelog_maxdncachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} max dn cache size"
      },
      {
       "expr": "irate(ldap_ldbm_changelog_maxentrycachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} max entry cache size"
      },
      {
       "expr": "irate(ldap_ldbm_changelog_maxnormalizeddncachesize{instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}} max normalized dn cache size"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU%",
     "type": "stat",
     "description": "$service -  avg Host system CPU% Utilization over all hosts",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"idle\",}[$interval])) by(system,instance)) by (system)"
      }
     ]
    },
    {
     "title": "CPU% User",
     "type": "stat",
     "description": "$service -  avg Host system CPU% user Utilization over all hosts",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"user\"}[$interval])) by (system,service)"
      }
     ]
    },
    {
     "title": "CPU% iowait",
     "type": "bargauge",
     "description": "$service -  max Host system CPU% iowait Utilization over all hosts",
     "gridPos": { "h": 6, "w": 2, "x": 6, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "max_over_time (max(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"iowait\"}[$interval])) [$__range:]) ",
       "legendFormat": "{{ mode }}"
      }
     ]
    },
    {
     "title": "Cores Total",
     "type": "stat",
     "description": "$service -  Summary Cores count",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{system=~\"$system\", instance=~\"$instance_list\",}) by (cpu,system,instance)) by(system)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Mem%",
     "type": "stat",
     "description": "$service -  avg Host system Mem% Utilization over all hosts",
     "gridPos": { "h": 6, "w": 2, "x": 10, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} \n- (node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"} +\nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"})) / \nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by (system)"
      }
     ]
    },
    {
     "title": "Mem Free Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by (system))"
      }
     ]
    },
    {
     "title": "disk util max read_time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval])) by (system)",
       "legendFormat": "read"
      }
     ]
    },
    {
     "title": "Top Usage FS",
     "type": "table",
     "description": "Top  most usage File Systems over all hosts\n\nmountpoint  != variable: $mountpoint",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 50 },
     "targets": [
      {
       "expr": "label_replace( topk(5,max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by (instance,mountpoint)), \"instance\", \"$1\", \"instance\", \"$regexp\") ",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "CPU% System",
     "type": "stat",
     "description": "$service -  avg Host system CPU%  system Utilization over all hosts",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg (rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"system\"}[$interval])) by (system,service)"
      }
     ]
    },
    {
     "title": "Nodes Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(node_exporter_build_info{system=~\"$system\", instance=~\"$instance_list\",}) by (system)"
      }
     ]
    },
    {
     "title": "Mem Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by (system))"
      }
     ]
    },
    {
     "title": "disk util max write_time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "max(rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval])) by (system)",
       "legendFormat": "write "
      }
     ]
    },
    {
     "title": "System:[  $system  ] Service:[  $service  ] CPU and Mem metrics, quantile=$quantile ",
     "type": "table",
     "description": "OS metrics summary table for last $last.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": " (max(up{system=~\"$system\", instance=~\"$instance_list\", noderole=~\".+\"}) by (system,service,instance))"
      },
      {
       "expr": "(min(node_boot_time_seconds{system=~\"$system\", instance=~\"$instance_list\", }) by (system,service,instance))"
      },
      {
       "expr": "count(count(node_cpu_seconds_total{system=~\"$system\", instance=~\"$instance_list\",}) by (cpu,system,instance)) by(system,service,instance)"
      },
      {
       "expr": "quantile_over_time ($quantile,max(node_load5{system=~\"$system\", instance=~\"$instance_list\",}) by(system,service,instance)[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"idle\",}[$interval])) by(system,service,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"system\",}[$interval])) by(system,service,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"user\",}[$interval])) by(system,service,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"iowait\",}[$interval])) by(system,service,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"irq\",}[$interval])) by(system,service,instance))[$__range:])"
      },
      {
       "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"softirq\",}[$interval])) by(system,service,instance))[$__range:])"
      },
      {
       "expr": "max(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by(system,service,instance)"
      },
      {
       "expr": "max(((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"})) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,service,instance)"
      },
      {
       "expr": "min(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,service,instance)"
      },
      {
       "expr": "min(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,service,instance)"
      },
      {
       "expr": "min(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,service,instance)"
      },
      {
       "expr": "min(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,service,instance)"
      },
      {
       "expr": "topk(5,max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by (instance,mountpoint))"
      },
      {
       "expr": "max(((node_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} - node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance_list\"}) / (node_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} )) * 100) by (system,service,instance)"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes CPU  - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization % Host Systems ",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"idle\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 1m Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load1{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 5m Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load5{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 15m Host Systems ",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load15{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  System %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"system\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  User %  ]  Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"user\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  IOWait %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"iowait\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Memory - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization% Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\ncurrent formula\n(node_memory_MemTotal_bytes-node_memory_MemFree_bytes-node_memory_Cached_bytes-node_memory_Buffers_bytes ) /\nnode_memory_MemTotal_bytes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 123 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Available %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 123 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Free %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 123 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory Utilization GB Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 131 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Available GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 131 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Free GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 131 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Cached %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 139 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Cached GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 139 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Buffers %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 139 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Buffers GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 139 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "[  SWAP Utilization %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 145 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max (1 - (node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance\"} / on(system,instance)\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "[  SWAP Utilization GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 145 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace( max(\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance\"}-node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance\"}) by (system,instance) , \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Disk and Network Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "System:[  $system  ] Service:[  $service  ] Disk and Network metrics, quantile=$quantile ",
     "type": "table",
     "description": "OS metrics summary table for last $last.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by(system,instance)"
      },
      {
       "expr": "max_over_time(max by(system,instance) (rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))[$__range:])"
      },
      {
       "expr": "max_over_time(max by(system,instance) (rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))[$__range:])"
      },
      {
       "expr": "(max(node_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by (system,service,instance))"
      },
      {
       "expr": "max (1 - (node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} / on(system,instance)\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by (system,instance)"
      },
      {
       "expr": "sum(irate(node_network_receive_bytes_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))by (system,instance)"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))by (system,instance)"
      },
      {
       "expr": "max((node_netstat_Tcp_CurrEstab{system=~\"$system\",instance=~\"$instance_list\"}))by (system,instance)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by (instance,mountpoint)"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes FS - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "repeat": "instance_list",
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "$alertname:",
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\", system=~\"$system\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "system=[ $system ] , service=[ $service ] current alert list",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "(ALERTS{system=~\"$system\", alertname=~\"$alertname\", severity=~\"$severity\"})"
      }
     ]
    }
   ]
  }
 ]
}