{
 "title": "[SERVICE] YARN RM APP",
 "description": "Dashboard for yarn rm app",
 "tags": [
  "yarn",
  "queue",
  "cdh",
  "sdp"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "5m,10m,15m,30m,1h" },
   {
    "name": "service",
    "query": "label_values(hadoop_yarn_app_state{},service)"
   },
   {
    "name": "system",
    "query": "label_values(hadoop_yarn_app_state{service=~\"$service\"},system)"
   },
   {
    "name": "instance",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\"},instance)"
   },
   {
    "name": "q0",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\"},q0)"
   },
   {
    "name": "q1",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\"},q1)"
   },
   {
    "name": "q2",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\",q1=~\"$q1\"},q2)"
   },
   {
    "name": "name",
    "label": "name",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"},name)"
   },
   {
    "name": "stage",
    "label": "stage",
    "query": "label_values(hadoop_yarn_app_state{system=~\"$system\",service=~\"$service\",q0=~\"$q0\",q1=~\"$q1\",q2=~\"$q2\"},stage)"
   },
   {
    "name": "finalStatus",
    "label": "Final status",
    "query": "label_values(hadoop_yarn_app_finalstatus{system=~\"$system\",service=~\"$service\"},finalStatus)"
   },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   { "name": "threshold_cores", "query": "-1,0,1,2,5,10,50,100" },
   { "name": "threshold_mem", "label": "threshold_mem GB", "query": "-1,0,1,2,5,10,20,50,100,500" },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" },
   { "name": "wf", "label": ".+ if only with wf_name", "query": ".*,.+" }
  ]
 },
 "panels": [
  {
   "title": "APPs summary Table, q1=$q1 q2=$q2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "APPs q1=[  $q1  ] q2=[ $q2 ] finalStatus=[$finalStatus] last FINISHED run",
   "type": "table-old",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max_over_time(max(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\",}<hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time(max(hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"}>hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time(max(hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"}) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",}>-1) by(name,wf_name,stage,q1,q2)[$__range:])  + max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=\"SUCCEEDED\"}) by(name,wf_name,stage,q1,q2)[$__range:]) - 6"
    },
    {
     "expr": "avg_over_time (sum((hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"})*1000) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"}>-1) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "(max_over_time (max(\r\nhadoop_yarn_app_allocatedvcores{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",}>-1) by(name,wf_name,stage,q1,q2)[$__range:])) + max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=\"SUCCEEDED\"}) by(name,wf_name,stage,q1,q2)[$__range:]) - 6"
    },
    {
     "expr": "avg_over_time (sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"}*1000) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"}>-1) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time(count(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    }
   ]
  },
  {
   "title": "APPs q1=[  $q1  ] q2=[ $q2 ] current run",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "max(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}) by (name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}>hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}) by (name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}) by (name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}>-1) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max((hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"})*1000) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "sum(hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",finalStatus=~\"$finalStatus\"}) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(\r\nhadoop_yarn_app_allocatedvcores{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}>-1) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}) by(name,wf_name,stage,q1,q2) * 1000"
    },
    {
     "expr": "sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\"}>-1) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "count(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\"}) by (name,wf_name,stage,q1,q2)"
    }
   ]
  },
  { "title": "APP name=$name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "name" },
  {
   "title": "APPs q1=[  $q1  ] q2=[ $q2 ] name = [ $name ] stage=[ $stage ] , finalStatus=[$finalStatus] last FINISHED run",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max_over_time(max(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\",}<hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time(max(hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}>hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time(max(hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>-1) by(name,wf_name,stage,q1,q2)[$__range:])  + max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=\"SUCCEEDED\"}) by(name,wf_name,stage,q1,q2)[$__range:]) - 6"
    },
    {
     "expr": "avg_over_time (sum((hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"})*1000) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}>-1) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "(max_over_time (max(\r\nhadoop_yarn_app_allocatedvcores{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>-1) by(name,wf_name,stage,q1,q2)[$__range:])) + max_over_time (max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=\"SUCCEEDED\"}) by(name,wf_name,stage,q1,q2)[$__range:]) - 6"
    },
    {
     "expr": "avg_over_time (sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"} * 1000) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time (sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}>-1) by(name,wf_name,stage,q1,q2)[$__range:])"
    },
    {
     "expr": "max_over_time(count(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by (name,wf_name,stage,q1,q2)[$__range:])"
    }
   ]
  },
  {
   "title": "APPs q1=[  $q1  ] q2=[ $q2 ] name = [ $name ] stage=[ $stage ] current run",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "max(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\",}<hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by (name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(hadoop_yarn_app_finishedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}>hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by (name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by (name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(hadoop_yarn_app_finalstatus{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>-1) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "sum((hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"})*1000) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "sum(hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "max(\r\nhadoop_yarn_app_allocatedvcores{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>-1) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by(name,wf_name,stage,q1,q2) * 1000"
    },
    {
     "expr": "sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}>-1) by(name,wf_name,stage,q1,q2)"
    },
    {
     "expr": "count(hadoop_yarn_app_startedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",wf_name=~\".+\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"}) by (name,wf_name,stage,q1,q2)"
    }
   ]
  },
  {
   "title": "name=[ $name ] mem allocateted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(hadoop_yarn_app_allocatedmb{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"} > 0) by (q1,q2,name,stage)",
     "legendFormat": "{{ name }} {{stage }} mem allocated"
    }
   ]
  },
  {
   "title": "name=[$name] vcores & containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hadoop_yarn_app_allocatedvcores{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"} > 0) by (q1,q2,name,stage)",
     "legendFormat": " {{ name }} {{ stage }} vcores allocated"
    },
    {
     "expr": "sum(hadoop_yarn_app_runningcontainers{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"} >0 ) by (q1,q2,name,stage)",
     "legendFormat": " {{ name }} {{ stage }} containers  running "
    }
   ]
  },
  {
   "title": "name=[$name] vcores used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hadoop_yarn_app_vcoreseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"}*1000) by(q1,q2,name,stage)",
     "legendFormat": " {{ name }} {{ stage }} vcores used"
    }
   ]
  },
  {
   "title": "name=[ $name ] mem used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum((hadoop_yarn_app_memoryseconds{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"} / hadoop_yarn_app_elapsedtime{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\",finalStatus=~\"$finalStatus\"})*1000) by(system,q1,q2,name,stage)",
     "legendFormat": "{{ name }} {{stage }} mem used"
    }
   ]
  },
  {
   "title": "name=[$name]  state( RUNNING - 5, FINISHED - 6, FAILED - 7)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(hadoop_yarn_app_state{system=\"$system\",q1=~\"$q1\",q2=~\"$q2\",name=~\"$name\",stage=~\"$stage\",wf_name=~\"$wf\"} > 0) by (q1,q2,name,stage)",
     "legendFormat": "{{ name }} {{stage}} state "
    }
   ]
  }
 ]
}