{
 "title": "[SYSTEM] Template OS",
 "description": "Template for  Node metrics",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" },
   { "name": "system", "query": "label_values(up{},system)" },
   {
    "name": "service",
    "query": "label_values(up{system=~\"$system\"},service)"
   },
   {
    "name": "instance",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   {
    "name": "alert_group",
    "query": "label_values(ALERTS_FOR_STATE,alert_group)"
   },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{alert_group=~\"$alert_group\",},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" },
   {
    "name": "regexp",
    "label": "regexp for FQDN",
    "query": "([a-zA-Z0-9]+-[a-zA-Z0-9]+)[.].+ , (.+)"
   },
   {
    "name": "mountpoint",
    "label": "mountpoint !=",
    "query": "label_values(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",fstype=~\"ext4|xfs\"},mountpoint)"
   },
   {
    "name": "instance_list",
    "query": "label_values(up{system=~\"$system\",service=~\"$service\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Readme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Описание",
     "type": "text",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "\r\n## Описание дашборда\r\n\r\nДанный шаблон отображает основные метрики операционной системы собираемые с\r\n- exporter-node\r\n\r\nБлоки Summary содержат информацию о всех инстансах сервиса. Остальные блоки фильтруют информацию по полю instance\r\n\r\n#### переменные\r\n- ds - выбор датасорса(prometheus) из которого запрашивать данные для отображения(подробнее про типы прометеусов см https://confluence.ca.sbrf.ru/pages/editpage.action?pageId=2383122863)\r\n- system - имя системы\r\n- quantile - значение персентия для расчета значений в таблицах\r\n- last - период вермени отображения метрик для таблиц(чтобы не делать тяжелые расчеты на больших выборках)\r\n- regexp for FQDN - regexp для отсекания FQDN имен на графиках (экономия используемого места дашборда)\r\n- ountpoint != список точек монтирования, которые НЕ интересны для мониторинга(не учитывать в TopK селектах по утилизации файловых систем)\r\n- raw metric - выбрать метрику для отображения ее в \"сыром\" виде в блоке RAW METRICS (возможность для пользователя посмотрить метрки данного сервиса отсутствующие на дашборде, аналогичный функционал в меню графаны EXPLORE\r\n\r\n\r\n#### drill down links\r\n- из таблиц возможен переход по имени инстанса на более подробный дашборд по выбранному инстансу\r\n\r\n\r\n\r\n### Тиражирование\r\nМожет быть использован как основа дашборда по новым сервисам, при этом ненужные элементы дашборда(графики, таблицы) могут быть удалены.\r\nНапример оставить график по использовании памяти в %, но удалить график по использовании памяти в GB, т.к. избыточная информация.\r\nАдминистрато сервиса должен удостовериться и подтвердитьь что присутствуют все необходимые метрики и отсутствуют все мало значимые метрики.\r\n\r\n\r\nТак же можно менять визуализацию лейблов, например: не отображать столбик max/avg на графиках, менять толщину линий и степень заливки, содержание подписей и т.д.\r\n\r\nДля систем с более чем 50 хостами - может потребоваться дополнтиельная настройка значений переменных instance и instance_list (дефалтофое значение для выбора All)\r\n\r\n#### при тиражировании данное и все остальные описания или удалить или оставить только актуальные комментарии\r\n\r\n\r\n\r\n"
     }
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "CPU%",
   "type": "stat",
   "description": "$service -  avg Host system CPU% Utilization over all hosts",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"idle\",}[$interval])) by(system,instance)) by (system)"
    }
   ]
  },
  {
   "title": "CPU% User",
   "type": "stat",
   "description": "$service -  avg Host system CPU% user Utilization over all hosts",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"user\"}[$interval])) by (system,service)"
    }
   ]
  },
  {
   "title": "CPU% iowait",
   "type": "bargauge",
   "description": "$service -  max Host system CPU% iowait Utilization over all hosts",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max_over_time (max(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"iowait\"}[$interval])) [$__range:]) ",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Cores Total",
   "type": "stat",
   "description": "$service -  Summary Cores count",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{system=~\"$system\", instance=~\"$instance_list\",}) by (cpu,system,instance)) by(system)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Mem%",
   "type": "stat",
   "description": "$service -  avg Host system Mem% Utilization over all hosts",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} \n- (node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"} +\nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"})) / \nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by (system)"
    }
   ]
  },
  {
   "title": "Mem Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by (system))"
    }
   ]
  },
  {
   "title": "disk util max read_time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval])) by (system)",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Top Usage FS",
   "type": "table",
   "description": "Top  most usage File Systems over all hosts\n\nmountpoint  != variable: $mountpoint",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "targets": [
    {
     "expr": "label_replace( topk(5,max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by (instance,mountpoint)), \"instance\", \"$1\", \"instance\", \"$regexp\") ",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "CPU% System",
   "type": "stat",
   "description": "$service -  avg Host system CPU%  system Utilization over all hosts",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"system\"}[$interval])) by (system,service)"
    }
   ]
  },
  {
   "title": "Nodes Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{system=~\"$system\", instance=~\"$instance_list\",noderole=~\".+\"})"
    }
   ]
  },
  {
   "title": "Mem Free Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by (system))"
    }
   ]
  },
  {
   "title": "disk util max write_time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval])) by (system)",
     "legendFormat": "write "
    }
   ]
  },
  {
   "title": "System:[  $system  ] Service:[  $service  ] CPU and Mem metrics, quantile=$quantile ",
   "type": "table",
   "description": "OS metrics summary table for last $last.",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": " (max(up{system=~\"$system\", instance=~\"$instance_list\", noderole=~\".+\"}) by (system,service,instance))"
    },
    {
     "expr": "(min(node_boot_time_seconds{system=~\"$system\", instance=~\"$instance_list\", }) by (system,service,instance))"
    },
    {
     "expr": "count(count(node_cpu_seconds_total{system=~\"$system\", instance=~\"$instance_list\",}) by (cpu,system,instance)) by(system,service,instance)"
    },
    {
     "expr": "quantile_over_time ($quantile,max(node_load5{system=~\"$system\", instance=~\"$instance_list\",}) by(system,service,instance)[$__range:])"
    },
    {
     "expr": "quantile_over_time ($quantile,(1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"idle\",}[$interval])) by(system,service,instance))[$__range:])"
    },
    {
     "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"system\",}[$interval])) by(system,service,instance))[$__range:])"
    },
    {
     "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"user\",}[$interval])) by(system,service,instance))[$__range:])"
    },
    {
     "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"iowait\",}[$interval])) by(system,service,instance))[$__range:])"
    },
    {
     "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"irq\",}[$interval])) by(system,service,instance))[$__range:])"
    },
    {
     "expr": "quantile_over_time ($quantile,(avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance_list\",mode=\"softirq\",}[$interval])) by(system,service,instance))[$__range:])"
    },
    {
     "expr": "max(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by(system,service,instance)"
    },
    {
     "expr": "max(((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"})) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,service,instance)"
    },
    {
     "expr": "min(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,service,instance)"
    },
    {
     "expr": "min(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,service,instance)"
    },
    {
     "expr": "min(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,service,instance)"
    },
    {
     "expr": "min(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance_list\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by(system,service,instance)"
    },
    {
     "expr": "topk(5,max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by (instance,mountpoint))"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Disk and Network Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "System:[  $system  ] Service:[  $service  ] Disk and Network metrics, quantile=$quantile ",
     "type": "table",
     "description": "OS metrics summary table for last $last.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by(system,instance)"
      },
      {
       "expr": "max_over_time(max by(system,instance) (rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))[$__range:])"
      },
      {
       "expr": "max_over_time(max by(system,instance) (rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))[$__range:])"
      },
      {
       "expr": "(max(node_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"}) by (system,service,instance))"
      },
      {
       "expr": "max (1 - (node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance_list\"} / on(system,instance)\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance_list\"})) by (system,instance)"
      },
      {
       "expr": "sum(irate(node_network_receive_bytes_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))by (system,instance)"
      },
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{system=~\"$system\",instance=~\"$instance_list\"}[$interval]))by (system,instance)"
      },
      {
       "expr": "max((node_netstat_Tcp_CurrEstab{system=~\"$system\",instance=~\"$instance_list\"}))by (system,instance)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"})) by (instance,mountpoint)"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes CPU  - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization % Host Systems ",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((1 - avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"idle\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 1m Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load1{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 5m Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load5{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage 15m Host Systems ",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_load15{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  System %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"system\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  User %  ]  Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"user\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Utilization [  IOWait %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace((avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"iowait\",}[$interval])) by(system,instance)), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Memory - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization% Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\ncurrent formula\n(node_memory_MemTotal_bytes-node_memory_MemFree_bytes-node_memory_Cached_bytes-node_memory_Buffers_bytes ) /\nnode_memory_MemTotal_bytes",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Available %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Free %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory Utilization GB Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Available GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Free GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Cached %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Cached GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Buffers %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory [  Buffers GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(max(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}))) by(system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "[  SWAP Utilization %  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(max (1 - (node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance\"} / on(system,instance)\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "[  SWAP Utilization GB  ] Host Systems",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace( max(\nnode_memory_SwapTotal_bytes{system=~\"$system\",instance=~\"$instance\"}-node_memory_SwapFree_bytes{system=~\"$system\",instance=~\"$instance\"}) by (system,instance) , \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes Disk & Network - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk read/write time seconds",
     "type": "graph",
     "description": "read - negative  Y\nwrite - positive Y",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      {
       "format": "s",
       "label": "disr read s (-) / disk write s (+)"
      }
     ],
     "targets": [
      {
       "expr": "label_replace(sum by(system,instance) (rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-read"
      },
      {
       "expr": "label_replace(sum by(system,instance) (rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-write"
      }
     ]
    },
    {
     "title": "Disk IOps ",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "iops", "label": "IO read (-) / write (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_disk_reads_completed_total{system=~\"$system\",instance=~\"$instance\",device=~\"[a-z]*[a-z]\"}[$interval])) by (service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-read"
      },
      {
       "expr": "label_replace(sum(irate(node_disk_writes_completed_total{system=~\"$system\",instance=~\"$instance\",device=~\"[a-z]*[a-z]\"}[$interval])) by (service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-write"
      }
     ]
    },
    {
     "title": "Network transmited/resived time seconds",
     "type": "graph",
     "description": "read - negative  Y\nwrite - positive Y",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "Bps", "label": "transmit (-) /resive (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_bytes_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-out"
      }
     ]
    },
    {
     "title": "Network Traffic Errors",
     "type": "graph",
     "description": "irate - packets per second",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_errs_total{system=~\"$system\",instance=~\"$instance\"}[$interval])) by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-out"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "graph",
     "description": "irate - packets per second",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "pps", "label": "Packets out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(sum(irate(node_network_receive_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-in"
      },
      {
       "expr": "label_replace(sum(irate(node_network_transmit_drop_total{system=~\"$system\",instance=~\"$instance\"}[$interval]))by (system,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{instance}}-out"
      }
     ]
    },
    {
     "title": "TCP Connections count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Connections" }
     ],
     "targets": [
      {
       "expr": "label_replace(node_netstat_Tcp_CurrEstab{system=~\"$system\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "UDP In / Out",
     "type": "graph",
     "description": "irate - per second  Datagrams",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(irate(node_netstat_Udp_InDatagrams{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-in"
      },
      {
       "expr": "label_replace(irate(node_netstat_Udp_OutDatagrams{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-out"
      }
     ]
    },
    {
     "title": "UDP Errors",
     "type": "graph",
     "description": "irate - per second  errors",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "Datagrams out (-) / in (+)" }
     ],
     "targets": [
      {
       "expr": "label_replace(irate(node_netstat_Udp_InErrors{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-InErrors"
      },
      {
       "expr": "label_replace(irate(node_netstat_Udp_NoPorts{system=~\"$system\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-NoPorts"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Nodes FS - [ $instance ] - <ВНИМАНИЕ!!! рекомендуется удалить этот блок для сервисов с более чем 20 хостами>",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 32 },
     "repeat": "instance_list",
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 32 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 32 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 38 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 38 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 44 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 44 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 50 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 50 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 50 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 56 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 56 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    },
    {
     "title": "$instance_list FS",
     "type": "table",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "max(node_filesystem_avail_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      },
      {
       "expr": "max(1-(node_filesystem_free_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"} / \nnode_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}))by (instance,fstype,mountpoint)"
      },
      {
       "expr": "max(node_filesystem_size_bytes{system=~\"$system\",instance=~\"$instance_list\",mountpoint!~\"$mountpoint\",fstype=~\"ext4|xfs\"}) by (instance,mountpoint)"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system][$service] Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4.8, "x": 0, "y": 23 },
     "repeat": "alertname",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4.8, "x": 4.8, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4.8, "x": 9.6, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4.8, "x": 14.399999999999999, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4.8, "x": 19.2, "y": 23 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Alert List: system:$system, GROUP:$alert_group",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "ALERTS{system=~\"$system\", instance=~\"$instance\",alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"} "
      }
     ]
    }
   ]
  }
 ]
}