groups:
- name: ldap
  rules:
#####################################CPU#####################################
    - alert: ServiceLdapMetricsStatusNull
      expr: up{ service="ldap"} == 0
      for: 30m
      labels:
        severity: 0
        severityText: NODATA
        summary: Service Metrics Scrape Error
        alertid: "{{ $labels.system }}-{{ $labels.service }}-{{ $labels.instance }}-ServiceLdapMetricsStatusNull"
      annotations:
        summary: Service Metrics Scrape Error [{{ $labels.system }}] [{{ $labels.service }}] [{{ $labels.instance }}]
        description: There are no metrics for service [{{ $labels.service }}] [{{ $labels.instance }}]
