{
 "title": "[AS] DDRV",
 "tags": [
  "ddrv",
  "system"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "5m,10m,15m,30m,1h" },
   { "name": "system", "query": "label_values(system)" },
   {
    "name": "service",
    "label": "service",
    "query": "hdfs,hive,zookeeper,oozie,sentry,yarn,rta,solrfarm-blue,solrfarm-green,solr-blue,solr-green"
   },
   {
    "name": "roletype",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\",service=~\"$service\"},roletype)"
   },
   {
    "name": "instance",
    "query": "label_values({system=~\"$system\"},instance)"
   },
   {
    "name": "instance_list",
    "query": "label_values({system=~\"$system\",},instance)"
   },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   {
    "name": "alert_group",
    "query": "label_values(ALERTS_FOR_STATE,alert_group)"
   },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{alert_group=~\"$alert_group\",},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" }
  ]
 },
 "panels": [
  {
   "title": "[$system] Services status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2.1818181818181817, "x": 0, "y": 1 },
     "repeat": "service",
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2.1818181818181817, "x": 2.1818181818181817, "y": 1 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2.1818181818181817, "x": 4.363636363636363, "y": 1 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2.1818181818181817, "x": 6.545454545454545, "y": 1 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2.1818181818181817, "x": 8.727272727272727, "y": 1 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2.1818181818181817, "x": 10.909090909090908, "y": 1 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2.1818181818181817, "x": 13.09090909090909, "y": 1 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2.1818181818181817, "x": 15.272727272727272, "y": 1 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2.1818181818181817, "x": 17.454545454545453, "y": 1 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2.1818181818181817, "x": 19.636363636363633, "y": 1 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    },
    {
     "title": "$service status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2.1818181818181817, "x": 21.818181818181813, "y": 1 },
     "format": "none",
     "valueName": "min",
     "targets": [
      {
       "expr": "min(service_status{system=~\"$system\",service=~\"$service\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system] Services summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Services Current %CPU",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 17, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "max_over_time((max(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\"}) by (system,service))[$__range:])",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "system[$system] %physical Mem util",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 2 },
     "format": "percentunit",
     "valueName": "avg",
     "targets": [
      {
       "expr": "avg(1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\"} / \non(system,service,roletype,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\"})) by (system)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Services %physical Mem util",
     "type": "bargauge",
     "gridPos": { "h": 4, "w": 14, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "max(1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\"} / \non(system,service,roletype,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\"})) \nby (system,service)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "Nodes Count",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 14, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(count by (instance) (up{system=~\"$system\"}))"
      }
     ]
    },
    {
     "title": "system[$system] processcpuload",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 7, "x": 17, "y": 6 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\"}) by (system)",
       "legendFormat": "{{service}}"
      }
     ]
    },
    {
     "title": "cl:[$system] service:[$service] JMX current status",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "(max(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,service,roletype,instance))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "(max(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,service,roletype,instance))",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": " max(1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} / \non(system,service,roletype,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})) \nby (system,instance,roletype,service)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "max (1 - (jmx_java_lang_operatingsystem_freeswapspacesize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} / on(system,service,roletype,instance)\njmx_java_lang_operatingsystem_totalswapspacesize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})) by (system,service,roletype,instance)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "max(jmx_java_lang_memory_heapmemoryusage_max{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,service,roletype,instance)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "heap",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      },
      {
       "aggregation": "Last",
       "decimals": 2,
       "displayAliasType": "Warning / Critical",
       "displayType": "Regular",
       "displayValueWithAlias": "Never",
       "expr": "max(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} / jmx_java_lang_memory_heapmemoryusage_max{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,service,roletype,instance)",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "heap",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "units": "none",
       "valueHandler": "Number Threshold"
      }
     ]
    }
   ]
  },
  {
   "title": "[$system] Queue & Apps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CL:$system apps failed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(delta(hadoop_yarn_jmx_apps_failed{system=~\"$system\",service=~\"$service\",name=\"QueueMetrics\",\nq0=\"root\",q1!=\"null\"}[10m])>0) by (q1,q2,q3)",
       "legendFormat": "failed: q1={{q1}} q2={{q2}} q3={{q3}}"
      }
     ]
    },
    {
     "title": "CL:$system apps pending",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(delta(hadoop_yarn_jmx_apps_pending{system=~\"$system\",service=~\"$service\",name=\"QueueMetrics\",\nq0=\"root\",q1!=\"null\"}[10m])>0) by (q1,q2,q3)",
       "legendFormat": "pending:q1={{q1}} q2={{q2}} q3={{q3}}"
      }
     ]
    },
    {
     "title": "Top queue(q1) Mem%",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "topk(5, (max_over_time(max((hadoop_yarn_jmx_allocated_mb{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=\"root\",q1!=\"null\",q2=\"null\",q3=\"null\",q4=\"null\" }) / \nscalar(max(hadoop_yarn_jmx_allocated_mb{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=\"QueueMetrics\",q0=\"root\",q1=\"null\",q2=\"null\",q3=\"null\",q4=\"null\" })) ) \nby (instance,q0,q1) [1m:]) ) )",
       "legendFormat": "{{q1}}"
      }
     ]
    },
    {
     "title": "Top queue(q2) Mem%",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "topk(5, (max_over_time(max((hadoop_yarn_jmx_allocated_mb{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=\"QueueMetrics\",\nq0=\"root\",q1!=\"null\",q2!=\"null\",q3=\"null\",q4=\"null\" }) / \nscalar(max(hadoop_yarn_jmx_allocated_mb{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",name=\"QueueMetrics\",q0=\"root\",q1=\"null\",q2=\"null\",q3=\"null\",q4=\"null\" })) ) \nby (instance,q0,q1,q2) [1m:]) ) )"
      }
     ]
    }
   ]
  },
  { "title": "[$system] Nodes summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "MEM util avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(avg((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} \n- (node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"} +\nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"})) / \nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"}) by(system))"
    }
   ]
  },
  {
   "title": "CPU util avg",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[$interval])) by (system)"
    }
   ]
  },
  {
   "title": "CPU% System",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "quantile_over_time ($quantile, avg by (system, mode) (rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"system\"}[$interval]))[$__range:])",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU% User",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "targets": [
    {
     "expr": "quantile_over_time ($quantile, avg by (system, mode) (rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"user\"}[$interval]))[$__range:])",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU% iowait",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "targets": [
    {
     "expr": "quantile_over_time ($quantile, avg by (system, mode) (rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode=\"iowait\"}[$interval]))[$__range:])",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "mem% util",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 4 },
   "targets": [
    {
     "expr": "quantile_over_time ($quantile, (avg((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} \n- (node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"} +\nnode_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"})) / \nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"}) by(system)) [$__range:])"
    }
   ]
  },
  {
   "title": "disk util max",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "targets": [
    {
     "expr": "max(rate(node_disk_write_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$last]))",
     "legendFormat": "write "
    },
    {
     "expr": "max(rate(node_disk_read_time_seconds_total{system=~\"$system\",instance=~\"$instance\"}[$last]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "Mem Free Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}) by(system))"
    }
   ]
  },
  {
   "title": "Nodes Count",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_exporter_build_info{system=~\"$system\", instance=~\"$instance_list\"})"
    }
   ]
  },
  {
   "title": "cl:[$system] OS current status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(count(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\"}) by (cpu,system,instance)) by(system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "quantile_over_time ($quantile,max(node_load1{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)[$__range:])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "quantile_over_time ($quantile,max(node_load5{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)[$__range:])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "quantile_over_time ($quantile,max(node_load15{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)[$__range:])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[$interval])) by(system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "min(((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "min(((node_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "min(((node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "min(((node_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"}) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(((node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"} - \nnode_memory_MemFree_bytes{system=~\"$system\",instance=~\"$instance\"} - \n(node_memory_Cached_bytes{system=~\"$system\",instance=~\"$instance\"} + \nnode_memory_Buffers_bytes{system=~\"$system\",instance=~\"$instance\"})) /\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "cl:[$system] OS current status",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(count(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\"}) by (cpu,system,instance)) by(system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "quantile_over_time ($quantile,max(node_load1{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)[$__range:])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "quantile_over_time ($quantile,max(node_load5{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)[$__range:])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "quantile_over_time ($quantile,max(node_load15{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)[$__range:])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(rate(node_cpu_seconds_total{system=~\"$system\",instance=~\"$instance\",mode!=\"idle\",mode!=\"iowait\"}[$interval])) by(system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(node_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"}) by(system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "quantile_over_time ($quantile,min(100 - ((node_memory_MemAvailable_bytes{system=~\"$system\",instance=~\"$instance\"} * 100) /\r\nnode_memory_MemTotal_bytes{system=~\"$system\",instance=~\"$instance\"})) by(system,instance)[$__range:])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "[$system] Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4.8, "x": 0, "y": 26 },
     "repeat": "alertname",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4.8, "x": 4.8, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4.8, "x": 9.6, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4.8, "x": 14.399999999999999, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "$alertname: count",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4.8, "x": 19.2, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(ALERTS{system=~\"$system\", instance=~\"$instance\", alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Alert List: system:$system, GROUP:$alert_group",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "ALERTS{system=~\"$system\", instance=~\"$instance\",alert_group=~\"$alert_group\", alertname=~\"$alertname\", severity=~\"$severity\"} "
      }
     ]
    }
   ]
  },
  {
   "title": "[$system] instance summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "$system instances-job status",
     "type": "table",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": " min(up{system=~\"$system\",service=~\"$service\"}) by (service,instance,job)"
      }
     ]
    },
    {
     "title": "$system jmx_exporters",
     "type": "table",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 6 },
     "targets": [
      {
       "expr": "max(jmx_scrape_error{system=~\"$system\",service=~\"$service\"}) by (service,instance)"
      },
      {
       "expr": "max(jmx_scrape_duration_seconds{system=~\"$system\",service=~\"$service\"}) by (service,instance)"
      },
      {
       "expr": "max(jmx_exporter_build_info{system=~\"$system\",service=~\"$service\"}) by (service,instance,version)"
      }
     ]
    }
   ]
  },
  {
   "title": "End",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true
  }
 ]
}