{
 "title": "[AS] INFRA",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU_Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"IPA-Load-Test-node-exp\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "memory_Active_bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_bytes{job=\"IPA-Load-Test-node-exp\"} /1024 /1024 /1024",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disc usage %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"IPA-Load-Test-node-exp\",device=~\"vd.\"}[30s]) * 100",
     "legendFormat": "{{ instance }} ({{ device }})"
    }
   ]
  },
  {
   "title": "LA_1min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"IPA-Load-Test-node-exp\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"IPA-Load-Test-node-exp\"} /1024 /1024",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk Read/Write Latencies ???",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{job=\"IPA-Load-Test-node-exp\",device=~\"vd.\"}[10s])/rate(node_disk_reads_completed_total{job=\"IPA-Load-Test-node-exp\",device=~\"vd.\"}[10s])",
     "legendFormat": "{{ instance }} {{ device }} r"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{job=\"IPA-Load-Test-node-exp\",device=~\"vd.\"}[10s])/rate(node_disk_writes_completed_total{job=\"IPA-Load-Test-node-exp\",device=~\"vd.\"}[10s])",
     "legendFormat": "{{ instance }} {{ device }} w"
    }
   ]
  },
  {
   "title": "LDAP Current connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ldap_monitor_currentconnections",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Allocated File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{job=\"IPA-Load-Test-node-exp\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_now{job=\"IPA-Load-Test-node-exp\"}[10s])"
    }
   ]
  },
  {
   "title": "KDC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ISSUE",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host_h.name:[um0050 TO um0059] AND source: \"/var/log/krb5kdc.log\" AND message:\"ISSUE\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "NEEDED_PREAUTH",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30s", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "host_h.name:[um0050 TO um0059] AND source: \"/var/log/krb5kdc.log\" AND message:\"NEEDED_PREAUTH\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "PREAUTH_FAILED",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "host_h.name:[um0050 TO um0059] AND source: \"/var/log/krb5kdc.log\" AND message:\"PREAUTH_FAILED\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "LDAP Read waiters",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ldap_monitor_readwaiters", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "LDAP Busy Replica",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ldap_replication_nsds5replicaLastUpdateStatus{text=~\"Error..1.*\",replica_root=\"dc=lt,dc=esrt,dc=cloud,dc=sbrf,dc=ru\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "dirsrv status",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"dirsrv@LT-ESRT-CLOUD-SBRF-RU.service\", state=\"active\"}",
     "legendFormat": "{{ instance }} "
    }
   ]
  },
  {
   "title": "PKI status",
   "type": "table",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 36 },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"pki-tomcatd@pki-tomcat.service\", state=\"active\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}