{
 "title": "[AS] SDP Manager",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "service", "query": "label_values(service)" },
   {
    "name": "system",
    "query": "label_values(up{service=~\"$service\"},system)"
   },
   {
    "name": "instance",
    "query": "label_values({system=~\"$system\",service=~\"$service\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "PUMA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resident memory size in bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes", "label": "gauge" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{service=~\"puma\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Jenkins server data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Количество работающих узлов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_node_count_value", "legendFormat": "Node count" },
    { "expr": "jenkins_node_online_value", "legendFormat": "Node online" }
   ]
  },
  {
   "title": "Процент пройденных Health Check",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "jenkins_health_check_score", "legendFormat": "Health Check Score" }
   ]
  },
  {
   "title": "Количество используемых исполнителей",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jenkins_executor_count_value", "legendFormat": "Executor count" },
    { "expr": "jenkins_executor_in_use_value", "legendFormat": "Executor in use" }
   ]
  },
  { "title": "Jenkins agents data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Процент использования CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_load5{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Процент использования HDD",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/home\",instance=~\"$instance\"} - node_filesystem_free_bytes{mountpoint=\"/home\", instance=~\"$instance\"}) / node_filesystem_size_bytes{mountpoint=\"/home\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\",instance=~\"$instance\"} - node_filesystem_free_bytes{mountpoint=\"/\", instance=~\"$instance\"}) / node_filesystem_size_bytes{mountpoint=\"/\",system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/var\",instance=~\"$instance\"} - node_filesystem_free_bytes{mountpoint=\"/var\", instance=~\"$instance\"}) / node_filesystem_size_bytes{mountpoint=\"/var\",system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{mountpoint}}"
    },
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/usr\",instance=~\"$instance\"} - node_filesystem_free_bytes{mountpoint=\"/usr\", instance=~\"$instance\"}) / node_filesystem_size_bytes{mountpoint=\"/usr\",system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Процент использования RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$instance\"} / node_memory_MemTotal_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}