{
 "title": "[BT] business block",
 "tags": [
  "bt",
  "wf"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "ds", "label": "какой прометеус?", "query": "prometheus" },
   { "name": "system", "query": "label_values(system)" },
   {
    "name": "business_block",
    "query": "label_values({system=~\"$system\"},business_block)"
   },
   {
    "name": "datamart",
    "label": "витрины/выгрузки",
    "query": "label_values({system=~\"$system\",business_block=~\"$business_block\"},datamart)"
   },
   {
    "name": "wf_name",
    "label": "поток",
    "query": "label_values(wf_loading_time_start{system=~\"$system\",business_block=~\"$business_block\", datamart=~\"$datamart\"},wf_name)"
   },
   {
    "name": "wf_current_name",
    "label": "личный поток",
    "query": "label_values(wf_loading_time_start{system=~\"$system\",business_block=~\"$business_block\", datamart=~\"$datamart\",wf_children_name=\"null\"},wf_name)"
   },
   {
    "name": "wf_children_name",
    "query": "label_values(wf_loading_time_start{system=~\"$system\",business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\",},wf_children_name)"
   },
   {
    "name": "wf_parent_name",
    "query": "label_values(wf_loading_time_start{system=~\"$system\",business_block=~\"$business_block\", wf_children_name=~\"$wf_name\"},wf_name)"
   },
   {
    "name": "alive",
    "query": "label_values(wf_loading_time_start{system=~\"$system\"},alive)"
   },
   {
    "name": "status",
    "query": "label_values(wf_loading_time_start{system=~\"$system\"},status)"
   },
   { "name": "last", "query": "5m,15m,30m" }
  ]
 },
 "panels": [
  { "title": "Текущий статус", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "repeat": "datamart",
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "Текущий статус",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_current_name\", wf_children_name=\"null\"}) by (datamart,wf_name,alive,status)) * 1000"
    },
    {
     "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\",wf_name=~\"$wf_current_name\", wf_children_name=\"null\", }) by (datamart,wf_name,alive,status) > 1) * 1000"
    },
    {
     "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_currnet_name\", wf_children_name=\"null\",}) by (datamart,wf_name,alive,status)"
    },
    {
     "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_current_name\", wf_children_name=\"null\"}) by (datamart,wf_name,alive,status)"
    },
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_current_name\", wf_children_name=\"null\"}) by (datamart,wf_name,alive,status)"
    },
    {
     "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_current_name\", wf_children_name=\"null\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
    }
   ]
  },
  {
   "title": "Статус по фильтру alive=$alive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 24 },
     "repeat": "datamart",
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 24 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 24 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 24 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 24 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 24 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 26 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 26 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 26 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 26 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 26 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 28 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 28 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 28 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 12, "y": 28 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 16, "y": 28 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 20, "y": 28 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 30 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 4, "y": 30 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    },
    {
     "title": "$datamart",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 8, "y": 30 },
     "format": "none",
     "valueName": "max",
     "targets": [
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_children_name=\"null\", alive=~\"$alive\"}) by (datamart)"
      }
     ]
    }
   ]
  },
  {
   "title": "Сводная таблица-фильтр личных потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "progress(фильруется по витрине,потокам, статусам) alive=$alive",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_current_name\", wf_children_name=\"null\", alive=~\"$alive\", status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\",wf_name=~\"$wf_current_name\", wf_children_name=\"null\", alive=~\"$alive\", status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_currnet_name\", wf_children_name=\"null\", alive=~\"$alive\", status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_current_name\", wf_children_name=\"null\", alive=~\"$alive\", status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_current_name\", wf_children_name=\"null\", alive=\"COMPLETED\", status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Сводная таблица личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "progress alive=$alive",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\", status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 1) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status) >0) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "repeat": "datamart",
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "$business_block - $datamart статус личных и родительских потоков",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "$business_block - $datamart",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
      },
      {
       "expr": "max(wf_loading_duration{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_id{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "max(wf_loading_status{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
      },
      {
       "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=~\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
      }
     ]
    }
   ]
  },
  {
   "title": "End",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true
  }
 ]
}