{
 "title": "[BT] datamart",
 "tags": [
  "bt",
  "wf"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "какой прометеус?", "query": "prometheus" },
   { "name": "system", "query": "label_values(system)" },
   {
    "name": "business_block",
    "query": "label_values({system=~\"$system\"},business_block)"
   },
   {
    "name": "datamart",
    "label": "Витрины/выгрузки",
    "query": "label_values(wf_loading_time_start{system=\"$system\",business_block=\"$business_block\"},datamart)"
   },
   {
    "name": "wf_name",
    "label": "поток",
    "query": "label_values(wf_loading_time_start{system=\"$system\",business_block=\"$business_block\", datamart=\"$datamart\"},wf_name)"
   },
   {
    "name": "wf_current_name",
    "label": "личный поток",
    "query": "label_values(wf_loading_time_start{system=\"$system\",business_block=\"$business_block\", datamart=\"$datamart\",wf_children_name=\"null\"},wf_name)"
   },
   {
    "name": "wf_parent_name",
    "label": "родительский поток",
    "query": "label_values(wf_loading_time_start{system=\"$system\", wf_children_name=\"$wf_name\"},wf_name)"
   },
   {
    "name": "wf_children_name",
    "label": "дочерний поток",
    "query": "label_values(wf_loading_time_start{system=\"$system\", wf_name=~\"$wf_name\"},wf_children_name)"
   },
   {
    "name": "alive",
    "query": "label_values(wf_loading_time_start{system=\"$system\"},alive)"
   },
   {
    "name": "status",
    "query": "label_values(wf_loading_time_start{system=\"$system\"},status)"
   },
   { "name": "last", "query": "15m" },
   {
    "name": "wf_status_active",
    "query": "INIT, PREREQ, PARAM, TIME-WAIT, EVENT-WAIT, LOCK-WAIT, START, RUNNING"
   },
   { "name": "wf_status_success", "query": "SUCCESS" },
   { "name": "wf_status_error", "query": "ERROR, ERRORCHECK" },
   { "name": "last_h", "query": "8h" }
  ]
 },
 "panels": [
  { "title": "Статус", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$datamart",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(wf_loading_status{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_current_name\"}) by (datamart)"
    }
   ]
  },
  {
   "title": "$datamart sum allocatedMB",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 5, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(wf_allocatedmb{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\"}))"
    }
   ]
  },
  {
   "title": "$datamart sum allocatedVCores",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(sum(wf_allocatedvcores{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\"}))"
    }
   ]
  },
  {
   "title": "max allocatedMB",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "max(wf_allocatedmb{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\"}) by (wf_name)",
     "legendFormat": "{{ wf_name }}"
    }
   ]
  },
  {
   "title": "max allocatedVCores",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "max(wf_allocatedvcores{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\"}) by (wf_name)",
     "legendFormat": "{{ wf_name }}"
    }
   ]
  },
  { "title": "История", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "$datamart - статусы потоков",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Status" }
   ],
   "targets": [
    {
     "expr": "max(wf_loading_status{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$wf_status_active\"}) by (datamart,wf_name,alive,status)",
     "legendFormat": "{{ wf_name }} : active"
    },
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$wf_status_success\"}) by (datamart,wf_name,alive,status)",
     "legendFormat": "{{ wf_name }} : success"
    },
    {
     "expr": "max(wf_loading_status{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$wf_status_error\"}) by (datamart,wf_name,alive,status)",
     "legendFormat": "{{ wf_name }} : error"
    }
   ]
  },
  {
   "title": "$datamart YARN allocatedMB",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "wf_allocatedmb{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\"}",
     "legendFormat": "{{ wf_name }}"
    }
   ]
  },
  {
   "title": "$datamart YARN allocatedVCores",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wf_allocatedvcores{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\"}",
     "legendFormat": "allocatedVCores {{ wf_name }}"
    }
   ]
  },
  {
   "title": "$datamart status сводная таблицы по личным и родительским потокам",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "$datamart - личные и родительские потоки, alive=$alive",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
    },
    {
     "expr": "(max(wf_loading_time_end{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) > 0) * 1000"
    },
    {
     "expr": "max(wf_loading_duration{system=~\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
    },
    {
     "expr": "max(wf_loading_id{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
    },
    {
     "expr": "max(wf_loading_status{system=~\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
    },
    {
     "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)) * 1000"
    }
   ]
  },
  {
   "title": "$datamart status сводные таблицы по всем типам потоков(личные, дочерние, родительские)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }
  },
  {
   "title": "$datamart - статус личных потоков, alive=$alive",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "(max(wf_loading_time_start{system=~\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_current_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)) * 1000"
    },
    {
     "expr": "(max(wf_loading_time_end{system=\"$system\", business_block=\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_current_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status) >0) * 1000"
    },
    {
     "expr": " max(wf_loading_duration{system=~\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_current_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
    },
    {
     "expr": "max(wf_loading_id{system=\"$system\", business_block=\"$business_block\", datamart=~\"$datamart\", wf_name=~\"$wf_current_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,alive,status)"
    },
    {
     "expr": "max(wf_loading_status{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_current_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,alive,status)"
    }
   ]
  },
  {
   "title": "$datamart - статус родительских потоков",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "(max(wf_loading_time_start{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_parent_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,wf_children_name,alive,status)) * 1000"
    },
    {
     "expr": "(max(wf_loading_time_end{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_parent_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,wf_children_name,alive,status)>0) * 1000"
    },
    {
     "expr": " max(wf_loading_duration{system=~\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_parent_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,wf_children_name,alive,status)"
    },
    {
     "expr": "max(wf_loading_id{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_parent_name\", alive=~\"$alive\",  status=~\"$status\"}) by (datamart,wf_name,wf_children_name,alive,status)"
    },
    {
     "expr": "max(wf_loading_status{system=\"$system\", business_block=\"$business_block\", datamart=\"$datamart\", wf_name=~\"$wf_parent_name\", alive=\"COMPLETED\",  status=\"SUCCESS\"}) by (datamart,wf_name,wf_children_name,alive,status)"
    }
   ]
  },
  {
   "title": "$datamart - статус дочерних потоков",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "(max(wf_loading_time_start{system=\"$system\", business_block=\"$business_block\", wf_name=~\"$wf_children_name\", alive=~\"$alive\",  status=~\"$status\"}) by (wf_name,alive,status)) * 1000"
    },
    {
     "expr": "(max(wf_loading_time_end{system=~\"$system\", business_block=\"$business_block\",  wf_name=~\"$wf_children_name\", alive=~\"$alive\",  status=~\"$status\"}) by (wf_name,alive,status) > 0) * 1000"
    },
    {
     "expr": " max(wf_loading_duration{system=~\"$system\", business_block=\"$business_block\",  wf_name=~\"$wf_children_name\", alive=~\"$alive\",  status=~\"$status\"}) by (wf_name,alive,status)"
    },
    {
     "expr": "max(wf_loading_id{system=\"$system\", business_block=\"$business_block\", wf_name=~\"$wf_children_name\", alive=~\"$alive\",  status=~\"$status\"}) by (wf_name,alive,status)"
    },
    {
     "expr": "max(wf_loading_status{system=\"$system\", business_block=\"$business_block\", wf_name=~\"$wf_children_name\", alive=~\"$alive\",  status=~\"$status\"}) by (wf_name,alive,status)"
    }
   ]
  },
  {
   "title": "End",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true
  }
 ]
}