{
 "title": "[NODE] JMX",
 "tags": [
  "node",
  "jmx"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "5m,10m,15m,30m,1h" },
   {
    "name": "system",
    "query": "label_values(jmx_exporter_build_info{},system)"
   },
   {
    "name": "service",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\"},service)"
   },
   {
    "name": "roletype",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\",service=~\"$service\"},roletype)"
   },
   {
    "name": "instance",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",},instance)"
   },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{alert_group=~\"$alert_group\",},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   {
    "name": "alertstate",
    "query": "label_values(ALERTS{},alertstate)"
   },
   { "name": "last_h", "query": "8h" }
  ]
 },
 "panels": [
  { "title": "Status summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ roletype }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "max(100 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=\"$instance\"} /\non(system,service,instance,roletype) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=\"$instance\"} * 100))",
     "legendFormat": "{{ roletype }}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(jmx_java_lang_operatingsystem_totalswapspacesize{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ roletype }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "max(100 - (jmx_java_lang_operatingsystem_freeswapspacesize{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=\"$instance\"} /\non(system,service,instance,roletype) jmx_java_lang_operatingsystem_totalswapspacesize{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=\"$instance\"} * 100))",
     "legendFormat": "{{ roletype }}"
    }
   ]
  },
  {
   "title": "CPU System Load 1m",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max(avg_over_time(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}[10m:]) * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "system",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load 5m",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "max(avg_over_time(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}[10m]) * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(jmx_java_lang_operatingsystem_availableprocessors {system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ roletype }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "JMX CPU&Mem info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jmx_java_lang_memorypool_usage_used{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ service }} {{ roletype }} {{ name }} memeory pool used ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Heap Used MB",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\"}",
     "legendFormat": "{{ service }} {{ roletype }} committed"
    },
    {
     "expr": "jmx_java_lang_memory_heapmemoryusage_init{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\"}",
     "legendFormat": "{{ service }} {{ roletype }}  init"
    },
    {
     "expr": "jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\"}",
     "legendFormat": "{{ service }} {{ roletype }}  used"
    }
   ]
  },
  {
   "title": "Memory Heap Used %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"} / on(system,service,instance,roletype) jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"})",
     "legendFormat": "{{ service }} {{ roletype }} used %"
    }
   ]
  },
  {
   "title": "Mem Used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " max(1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} / \non(system,service,roletype,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})) \nby (system,instance)",
     "legendFormat": "{{ instance}} mem used %"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\"} * 100) by (system,instance)",
     "legendFormat": "{{ instance}} SystemLoad"
    },
    {
     "expr": "max(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\",roletype=~\"$roletype\",instance=~\"$instance\"} * 100) by (system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance}} ProcessCpuTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "JMX Additional info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jmx_java_lang_threading_threadcount{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
     "legendFormat": "{{roletype}}  threadcount"
    },
    {
     "expr": "jmx_java_lang_threading_daemonthreadcount{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
     "legendFormat": "{{roletype}} daemonthreadcount "
    },
    {
     "expr": "jmx_java_lang_threading_peakthreadcount{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
     "legendFormat": "{{roletype}}  peakthreadcount"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jmx_java_lang_classloading_totalloadedclasscount{system=~\"$system\",roletype=~\"$roletype\", instance=~\"$instance\"}",
     "legendFormat": "{{roletype}} Total Loaded Class"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jmx_java_lang_operatingsystem_openfiledescriptorcount{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{roletype}} Open File Descriptor ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GC time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jmx_java_lang_garbagecollector_collectiontime{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
     "legendFormat": "{{roletype}} Garbage Collector "
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jmx_java_lang_garbagecollector_collectioncount{system=~\"$system\",roletype=~\"$roletype\",instance=~\"$instance\"}",
     "legendFormat": "{{roletype}} Garbage Collector Count"
    }
   ]
  },
  {
   "title": "End",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true
  }
 ]
}