{
 "title": "[NODE] WIN",
 "description": "Enhanced and updated windows node dashboard",
 "tags": [
  "windows",
  "prometheus",
  "windows_exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "60s" },
   {
    "name": "system",
    "query": "label_values(windows_exporter_build_info{},system)"
   },
   {
    "name": "instance",
    "query": "label_values(windows_exporter_build_info{system=~\"$system\"},instance)"
   },
   {
    "name": "cpumode",
    "label": "cpumode",
    "query": "label_values(windows_cpu_core_frequency_mhz,core)"
   },
   {
    "name": "cpu_core",
    "label": "cpu_core",
    "query": "label_values(windows_cpu_core_frequency_mhz,core) "
   }
  ]
 },
 "panels": [
  { "title": "Quick info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\", instance=~\"$instance.*\"}[3m])) * 100) > 0"
    }
   ]
  },
  {
   "title": "memory available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_memory_available_bytes{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Virtual memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_memory_swap_page_operations_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "C: space used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_logical_disk_size_bytes{instance=~\"$instance\", volume=\"C:\"} - windows_logical_disk_free_bytes{instance=~\"$instance\", volume=\"C:\"}) / windows_logical_disk_size_bytes{instance=~\"$instance\", volume=\"C:\"} * 100"
    }
   ]
  },
  {
   "title": "HarddiskVolume1 space used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(windows_logical_disk_size_bytes{instance=~\"$instance\", volume=\"HarddiskVolume1\"} - windows_logical_disk_free_bytes{instance=~\"$instance\", volume=\"HarddiskVolume1\"}) / windows_logical_disk_size_bytes{instance=~\"$instance\", volume=\"HarddiskVolume1\"} * 100"
    }
   ]
  },
  {
   "title": "HDD free size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{instance=~\"$instance\", volume!~\"HarddiskVolume.+\"}"
    }
   ]
  },
  { "title": "Cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(windows_cpu_time_total{instance=~\"$instance.*\", mode !~ \"idle\"}[3m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU load per process",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "CPU load" }
   ],
   "targets": [
    {
     "expr": "sum by (process) (rate(windows_cpu_time_total{instance=~\"$instance\", process !~\"Idle\"}[5m]))",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  {
   "title": "Cores frequency",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "mhz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_cpu_core_frequency_mhz{instance=~\"$instance\", core=~\"$cpu_core\"}",
     "legendFormat": "Core={{ core }}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "memory cache bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "windows_memory_cache_bytes{instance=~\"$instance\"} ",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Average commit bytes per process",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (process) (windows_memory_commit_limit{instance=~\"$instance\", process=~\".*\"})",
     "legendFormat": "{{ process }}"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hard drive load",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_write_bytes_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[3m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Write {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(windows_logical_disk_write_bytes_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[3m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Read {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Hard disk i/o ops total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 9, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "rate(windows_logical_disk_split_ios_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "i/o {{volume}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Hard disk used space",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "(windows_logical_disk_size_bytes{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"} - windows_logical_disk_free_bytes{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}) / windows_logical_disk_size_bytes{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"} * 100",
       "legendFormat": "used {{volume}}"
      }
     ]
    },
    {
     "title": "disk latency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg by (process) (rate(windows_logical_disk_read_latency_seconds_total{instance=~\"$instance\"}[5m])) >0",
       "legendFormat": "{{ process }} read"
      },
      {
       "expr": "- avg by (process) (rate(windows_logical_disk_write_latency_seconds_total{instance=~\"$instance\"}[5m])) <0",
       "legendFormat": "{{ process }} write"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network discarded/error packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "irate(wmi_net_packets_outbound_discarded{instance=~\"$server.*\", nic!~\"isatap.+\"}[$interval]) + irate(wmi_net_packets_outbound_errors{instance=~\"$server.*\"}[$interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Sent {{nic}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "irate(wmi_net_packets_received_discarded{instance=~\"$server.*\", nic!~\"isatap.+\"}[$interval]) + irate(wmi_net_packets_received_errors{instance=~\"$server.*\"}[$interval])",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Received {{nic}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Network",
     "type": "graph",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 36 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "application": { "filter": "" },
       "expr": "rate(wmi_net_bytes_sent_total{instance=~\"$server.*\"}[$interval]) >0",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Sent {{nic}}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "" },
       "expr": "- rate(wmi_net_bytes_received_total{instance=~\"$server.*\"}[$interval]) <0",
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "legendFormat": "Received {{nic}}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  }
 ]
}