{
 "title": "[NODE] JMX",
 "description": "Dashboard for node jmx",
 "tags": [
  "node",
  "jmx"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "5m,10m,15m,30m,1h" },
   {
    "name": "system",
    "query": "label_values(jmx_exporter_build_info{},system)"
   },
   {
    "name": "service",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\"},service)"
   },
   {
    "name": "jmxrole",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\",service=~\"$service\"},jmxrole)"
   },
   {
    "name": "instance",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",},instance)"
   },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{alert_group=~\"$alert_group\",},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   {
    "name": "alertstate",
    "query": "label_values(ALERTS{},alertstate)"
   },
   { "name": "last_h", "query": "8h" }
  ]
 },
 "panels": [
  { "title": "Status summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ jmxrole }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(100 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=\"$instance\"} /\non(system,service,instance,jmxrole) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=\"$instance\"} * 100))",
     "legendFormat": "{{ jmxrole }}"
    }
   ]
  },
  {
   "title": "Total SWAP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(jmx_java_lang_operatingsystem_totalswapspacesize{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ jmxrole }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Used SWAP",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(100 - (jmx_java_lang_operatingsystem_freeswapspacesize{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=\"$instance\"} /\non(system,service,instance,jmxrole) jmx_java_lang_operatingsystem_totalswapspacesize{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=\"$instance\"} * 100))",
     "legendFormat": "{{ jmxrole }}"
    }
   ]
  },
  {
   "title": "CPU System Load 1m",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(avg_over_time(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}[10m:]) * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "system",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU System Load 5m",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(avg_over_time(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}[10m]) * 100)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "max(jmx_java_lang_operatingsystem_availableprocessors {system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=\"$instance\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ jmxrole }}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "JMX CPU&Mem info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Memory Pool Used",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jmx_java_lang_memorypool_usage_used{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ service }} {{ jmxrole }} {{ name }} memeory pool used ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Heap Used MB",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}",
     "legendFormat": "{{ service }} {{ jmxrole }} committed"
    },
    {
     "expr": "jmx_java_lang_memory_heapmemoryusage_init{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}",
     "legendFormat": "{{ service }} {{ jmxrole }}  init"
    },
    {
     "expr": "jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}",
     "legendFormat": "{{ service }} {{ jmxrole }}  used"
    }
   ]
  },
  {
   "title": "Memory Heap Used %",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"} / on(system,service,instance,jmxrole) jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"})",
     "legendFormat": "{{ service }} {{ jmxrole }} used %"
    }
   ]
  },
  {
   "title": "Mem Used %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": " max(1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} / \non(system,service,jmxrole,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})) \nby (system,instance)",
     "legendFormat": "{{ instance}} mem used %"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"} * 100) by (system,instance)",
     "legendFormat": "{{ instance}} SystemLoad"
    },
    {
     "expr": "max(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"} * 100) by (system,instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ instance}} ProcessCpuTime",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "JMX Additional info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_threading_threadcount{system=~\"$system\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}",
       "legendFormat": "{{jmxrole}}  threadcount"
      },
      {
       "expr": "jmx_java_lang_threading_daemonthreadcount{system=~\"$system\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}",
       "legendFormat": "{{jmxrole}} daemonthreadcount "
      },
      {
       "expr": "jmx_java_lang_threading_peakthreadcount{system=~\"$system\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}",
       "legendFormat": "{{jmxrole}}  peakthreadcount"
      }
     ]
    },
    {
     "title": "Class loading",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 9, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_classloading_totalloadedclasscount{system=~\"$system\",jmxrole=~\"$jmxrole\", instance=~\"$instance\"}",
       "legendFormat": "{{jmxrole}} Total Loaded Class"
      }
     ]
    },
    {
     "title": "Open File Descriptors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_operatingsystem_openfiledescriptorcount{system=~\"$system\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{jmxrole}} Open File Descriptor ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_garbagecollector_collectiontime{system=~\"$system\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}",
       "legendFormat": "{{jmxrole}} Garbage Collector "
      }
     ]
    },
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jmx_java_lang_garbagecollector_collectioncount{system=~\"$system\",jmxrole=~\"$jmxrole\",instance=~\"$instance\"}",
       "legendFormat": "{{jmxrole}} Garbage Collector Count"
      }
     ]
    }
   ]
  },
  {
   "title": "End",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true
  }
 ]
}