{
 "title": "[TEMPLATE] Kamon",
 "description": "Template for JMX  metrics",
 "tags": [
  "template",
  "kamon"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" },
   {
    "name": "service",
    "query": "label_values(kamon_trace_sampler_decisions_total{},service)"
   },
   {
    "name": "system",
    "query": "label_values(kamon_trace_sampler_decisions_total{service=~\"$service\"},system)"
   },
   {
    "name": "port",
    "query": "label_values(kamon_trace_sampler_decisions_total{service=~\"$service\",system=~\"$system\"},port)"
   },
   {
    "name": "instance",
    "query": "label_values(kamon_trace_sampler_decisions_total{system=~\"$system\",service=~\"$service\"},instance)"
   },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{system=~\"$system\",service=~\"$service\"},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" },
   {
    "name": "regexp",
    "label": "regexp for FQDN",
    "query": "([a-zA-Z0-9]+-[a-zA-Z0-9]+)[.].+ , (.+)"
   },
   {
    "name": "mount",
    "label": "mount!=",
    "query": "label_values(host_storage_mount_space_total_bytes{system=~\"$system\",instance=~\"$instance\"},mount)"
   }
  ]
 },
 "panels": [
  {
   "title": "[ $system ] - [ $service ] http_server_connection_open",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "http_server_connection_open_sum rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\nrate(http_server_connection_open_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])\r\n, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} [component={{ component }}]"
      }
     ]
    },
    {
     "title": "http_server_connection_open_bucket quantile=$quantile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\nhistogram_quantile(0.95,(rate(http_server_connection_open_bucket{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])))\n, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} [component={{ component }}]"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] span_processing_time_seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "span_processing_time_seconds_sum rate ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\nrate(span_processing_time_seconds_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])\r\n, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} [component={{ component }}], [span_kind={{ span_kind }}], [error={{ error }}], [http_method={{ http_method }}], [http_status_code={{ http_status_code }}], [operation={{ operation }}] "
      }
     ]
    },
    {
     "title": "span_processing_time_seconds_bucket, quantile=$quantile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\nhistogram_quantile(0.95,(rate(span_processing_time_seconds_bucket{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])))\n, \"instance\", \"$1\", \"instance\", \"$regexp\") > 0",
       "legendFormat": "{{ instance }} [component={{ component }}], [span_kind={{ span_kind }}], [error={{ error }}], [http_method={{ http_method }}], [http_status_code={{ http_status_code }}], [operation={{ operation }}] "
      }
     ]
    },
    {
     "title": "span_processing_time_seconds_sum rate  sum by (instance,component,operation,span_kind,http_status_code,le) ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\nsum by (instance,component,operation,span_kind,http_status_code,le) (rate(span_processing_time_seconds_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])\r)\n, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} [component={{ component }}], [span_kind={{ span_kind }}], [error={{ error }}], [http_method={{ http_method }}], [http_status_code={{ http_status_code }}], [operation={{ operation }}] "
      }
     ]
    },
    {
     "title": "span_processing_time_seconds_bucket, quantile=$quantile sum by (instance,component,operation,span_kind,http_status_code,le) ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\nhistogram_quantile(0.95,(sum by (instance,component,operation,span_kind,http_status_code,le) (rate(span_processing_time_seconds_bucket{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])) ))\r\n, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} [component={{ component }}], [span_kind={{ span_kind }}], [error={{ error }}], [http_method={{ http_method }}], [http_status_code={{ http_status_code }}], [operation={{ operation }}] "
      }
     ]
    },
    {
     "title": "span_processing_time_seconds_bucket, quantile=$quantile",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "sum by (instance,component,operation,span_kind,http_status_code,le) (rate(span_processing_time_seconds_bucket{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])) ",
       "legendFormat": "{{ instance }} [component={{ component }}], [span_kind={{ span_kind }}], [error={{ error }}], [http_method={{ http_method }}], [http_status_code={{ http_status_code }}], [operation={{ operation }}] "
      }
     ]
    },
    {
     "title": "span_processing_time_seconds_sum AVG by operation,http_status_code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\navg(span_processing_time_seconds_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}/span_processing_time_seconds_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}) by (system,service,instance,component,operation,http_status_code)\r\n, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} component={{ component }} operation={{ operation }}  http_status_code={{ http_status_code }}"
      }
     ]
    },
    {
     "title": "span_processing_time_seconds AVG",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace(span_processing_time_seconds_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}/span_processing_time_seconds_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} component={{ component }}, span_kind={{ span_kind }}, error={{ error }}, http_method={{ http_method }}, http_status_code={{ http_status_code }}, operation={{ operation }} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] akka_group_processing_time_seconds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "akka_group_processing_time_seconds_sum rate sum by (instance,group)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\nsum by (instance,group) (rate(akka_group_processing_time_seconds_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])\r)\n, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} [{{ group }}]"
      }
     ]
    },
    {
     "title": "akka_group_processing_time_seconds_bucket, quantile=$quantile sum by (instance,group) ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace(\r\nhistogram_quantile(0.95,(sum by (instance,group,le) (rate(akka_group_processing_time_seconds_bucket{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])) ))\r\n, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} [{{ group }}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Readme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Описание",
     "type": "text",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "\n## Описание дашборда\n\nДанный шаблон отображает основные Kamon-метрики собираемые с\n- Kamon exporter\n\nБлоки Summary содержат информацию о всех инстансах сервиса. Остальные блоки фильтруют информацию по полю instance\n\n#### переменные\n- ds - выбор датасорса(prometheus) из которого запрашивать данные для отображения(подробнее про типы прометеусов см https://confluence.ca.sbrf.ru/pages/editpage.action?pageId=2383122863)\n- system - имя системы\n- quantile - значение персентия для расчета значений в таблицах\n- last - период вермени отображения метрик для таблиц(чтобы не делать тяжелые расчеты на больших выборках)\n- regexp for FQDN - regexp для отсекания FQDN имен на графиках (экономия используемого места дашборда)\n- ountpoint != список точек монтирования, которые НЕ интересны для мониторинга(не учитывать в TopK селектах по утилизации файловых систем)\n- raw metric - выбрать метрику для отображения ее в \"сыром\" виде в блоке RAW METRICS (возможность для пользователя посмотрить метрки данного сервиса отсутствующие на дашборде, аналогичный функционал в меню графаны EXPLORE\n\n\n### Тиражирование\nМожет быть использован как основа дашборда по новым сервисам, при этом ненужные элементы дашборда(графики, таблицы) могут быть удалены.\nНапример оставить график по использовании памяти в %, но удалить график по использовании памяти в GB, т.к. избыточная информация.\nАдминистрато сервиса должен удостовериться и подтвердить что присутствуют все необходимые метрики и отсутствуют все мало значимые метрики.\n\n\nТак же можно менять визуализацию лейблов, например: не отображать столбик max/avg на графиках, менять толщину линий и степень заливки, содержание подписей и т.д.\n\nДля систем с более чем 50 хостами - может потребоваться дополнтиельная настройка значений переменных instance и instance_list (дефалтофое значение для выбора All)\n\n#### при тиражировании данное и все остальные описания или удалить или оставить только актуальные комментарии\n\n\n\n"
     }
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "Sys CPU% max",
   "type": "stat",
   "description": "$service -  Max  Host system CPU% Utilization over all hosts",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(sum(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"combined\"}[$interval]))\n/\nsum(rate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"combined\"}[$interval])))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU %usr",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy on user mode.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",  mode=\"user\"}[$interval]))\n/\nsum(rate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",  mode=\"user\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Proc %usr",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy by the process in user mode.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_usage_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", mode=\"user\"}[$interval]))\n/\nsum(rate(process_cpu_usage_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", mode=\"user\"}[$interval]))"
    }
   ]
  },
  {
   "title": "File Descriptors Userd",
   "type": "stat",
   "description": "$service -  Max  open file descriptor count over all Java applications",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(process_ulimit_file_descriptors_used{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", component=\"process\"}) by (system))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Sys Mem Total",
   "type": "stat",
   "description": "$service -  Summary Memory size",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(host_memory_total_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})\nby (system)"
    }
   ]
  },
  {
   "title": "Sys Mem% max",
   "type": "stat",
   "description": "$service -  Max  Sys Mem% Utilization over all hosts",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(host_memory_used_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}/host_memory_total_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Heap Used Max ",
   "type": "stat",
   "description": "$service -  Max  Java Mem% Utilization over all Java applications",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_memory_used_bytes_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"heap\"}\n/\njvm_memory_used_bytes_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"heap\"})",
     "legendFormat": "{{  service }}"
    }
   ]
  },
  {
   "title": "System load average",
   "type": "bargauge",
   "description": "Tracks the system load average in 1m / 5m / 15m.\n\nThey indicate the average number of tasks (processes) wanting to run in the last 1m / 5m / 15m.\n\nOn Linux systems, these numbers is approximated and include processes wanting to run on the CPUs, as well as processes blocked in uninterruptible I/O (usually disk I/O).\nThis gives a high-level idea of resource load (or demand).\n\nThe three numbers give some idea of how load is changing over time.\n\nExcellent post on the subject: http://www.brendangregg.com/blog/2017-08-08/linux-load-averages.html",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(host_load_average{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", period=\"1m\"})",
     "legendFormat": "Avg. 1m"
    },
    {
     "expr": "max(host_load_average{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", period=\"5m\"})",
     "legendFormat": "Avg. 5m"
    },
    {
     "expr": "max(host_load_average{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", period=\"15m\"})",
     "legendFormat": "Avg. 15m"
    }
   ]
  },
  {
   "title": "CPU %system",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy on system mode.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",  mode=\"system\"}[$interval]))\n/\nsum(rate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",  mode=\"system\"}[$interval])))"
    }
   ]
  },
  {
   "title": "Proc %system",
   "type": "stat",
   "description": "Tracks the current time the CPU is busy by the process in kernel mode.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_usage_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", mode=\"system\"}[$interval]))\n/\nsum(rate(process_cpu_usage_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", mode=\"system\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Thread Peak max",
   "type": "stat",
   "description": "$service -  Max  Java CPU% Utilization over all Java applications",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_threads_peak{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "VM Hiccups (or idle jitters) in nanoseconds (p90)",
   "type": "heatmap",
   "description": "Tracks the hiccups detected in the VM (also known as idle jitters) measured in nanoseconds. The 90ht percentile is presented.\n\nFor more info: https://www.azul.com/jhiccup/",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(process_hiccups_seconds_bucket{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval])) by (le, instance))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Top Usage FS",
   "type": "table",
   "description": "Top  most usage File Systems over all hosts\n\nmountpoint  != variable: $mountpoint",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "label_replace( topk(6,max(host_storage_mount_space_used_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\",mount!~\"$mount\"} / \nhost_storage_mount_space_total_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\",mount!~\"$mount\"}) by (instance,mount)), \"instance\", \"$1\", \"instance\", \"$regexp\") ",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "CPU %wait",
   "type": "stat",
   "description": "Tracks the current time the CPU is stuck waiting for IO.\n\nIf this value is high, the disk might be the bottleneck.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", mode=\"wait\"}[$interval]))\n/\nsum(rate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", mode=\"wait\"}[$interval])))"
    }
   ]
  },
  {
   "title": "CPU %steal",
   "type": "stat",
   "description": "Tracks the current time the CPU is stolen by some process outside the VM.\n\nIf this value is high, it could be caused either by the supervisor is very busy, by a noisy neighbor or by some limitation on the quota assigned by the virtualization service.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", mode=\"stolen\"}[$interval]))\n/\nsum(rate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", mode=\"stolen\"}[$interval]))"
    }
   ]
  },
  {
   "title": "GC Time max",
   "type": "stat",
   "description": "$service -  Max  Garbage Collector collection time over all Java applications",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(rate(jvm_gc_seconds_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (system))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Java Thread count ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "label_replace((jvm_threads_total {system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}), \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "span processing time, quantile=$quantile by operation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(\r\nhistogram_quantile(0.95,(sum by (instance,component,operation,le) (rate(span_processing_time_seconds_bucket{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])) ))\r\n, \"instance\", \"$1\", \"instance\", \"$regexp\") > 0",
     "legendFormat": "{{ instance }} [{{ component }}] [{{ operation}}]"
    }
   ]
  },
  {
   "title": "HTTP connections quantile=$quantile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(\r\nhistogram_quantile(0.95,(rate(http_server_connection_open_bucket{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])))\n, \"instance\", \"$1\", \"instance\", \"$regexp\")",
     "legendFormat": "{{ instance }} [component={{ component }}]"
    }
   ]
  },
  {
   "title": "akka group processing time, quantile=$quantile by (group) ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "label_replace(\r\nhistogram_quantile(0.95,(sum by (instance,group,le) (rate(akka_group_processing_time_seconds_bucket{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",}[$interval])) ))\r\n, \"instance\", \"$1\", \"instance\", \"$regexp\") > 0",
     "legendFormat": "{{ instance }} [{{ group }}]"
    }
   ]
  },
  {
   "title": "System:[  $system  ] Service:[  $service  ] Kamon metrics, quantile=$quantile ",
   "type": "table",
   "description": "JMX metrics summary table for last $last.\n\nSys - means host OS metrics.\n\nAggregation(quanlile/max/last)  values during last $last\n\nJava/Heap/Pool - means Java application(service) metrics.\n\nYou can change colors threatholds as you wish\n\n",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "quantile_over_time($quantile,(max(host_load_average{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}) by(system,service,instance))[$__range:])"
    },
    {
     "expr": "max(sum(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"combined\"}[$interval])) by (system,service,instance)\r\n/\r\nsum(rate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"combined\"}[$interval])) by(system,service,instance)) by (system,service,instance)"
    },
    {
     "expr": "max(sum(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"user\"}[$interval])) by (system,service,instance)\r\n/\r\nsum(rate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"user\"}[$interval])) by(system,service,instance)) by (system,service,instance)"
    },
    {
     "expr": "max(sum(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"wait\"}[$interval])) by (system,service,instance)\r\n/\r\nsum(rate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"wait\"}[$interval])) by(system,service,instance)) by (system,service,instance)"
    },
    {
     "expr": "(max(host_memory_total_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}) by (system,service,instance))"
    },
    {
     "expr": "max(host_memory_used_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}\n/\nhost_memory_total_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}) by (system,service,instance)"
    },
    {
     "expr": "(max(host_swap_total_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}) by (system,service,instance))"
    },
    {
     "expr": "max (1 - (host_swap_used_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"} / on(system,service,jmxrole,instance)\nhost_swap_total_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"})) by (system,service,instance)"
    },
    {
     "expr": "quantile_over_time ($quantile,(max(jvm_memory_used_bytes_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"heap\"}\n/\njvm_memory_used_bytes_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"heap\"}) by (system,service,instance))[$__range:])"
    },
    {
     "expr": "max(jvm_memory_committed_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"heap\"}) by (system,service,instance)"
    },
    {
     "expr": "max_over_time((max(rate(jvm_gc_seconds_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval])) by (system,service,jmxrole,instance))[$__range:])"
    },
    {
     "expr": "(max(jvm_threads_total {system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}) by (system,service,instance))"
    },
    {
     "expr": "(max(process_ulimit_file_descriptors_used{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}) by (system,service,instance))"
    },
    {
     "expr": "min(host_memory_free_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"} /\r\nhost_memory_total_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}) by(system,service,instance)"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Kamon Host Systems - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Avarage Host Systems - 1m",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(host_load_average{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", period=\"1m\",component=\"host\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage Host Systems - 5m",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(host_load_average{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", period=\"5m\",component=\"host\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Load Avarage Host Systems - 15m",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(host_load_average{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", period=\"15m\",component=\"host\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Usage % System - hosts [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace(avg(sum(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", mode=\"system\"}[$interval])) by (system,service,instance)\n/\nsum(rate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",  mode=\"system\"}[$interval])) by (system,service,instance))  by (system,service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "CPU Usage % User - hosts [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace(avg(sum(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", mode=\"user\"}[$interval])) by (system,service,instance)\n/\nsum(rate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\",  mode=\"user\"}[$interval])) by (system,service,instance))  by (system,service,instance), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "Memory Usage % Host Systems - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace( (1 - (host_memory_free_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} / \non(system,service,jmxrole,instance) host_memory_total_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})) , \"instance\", \"$1\", \"instance\", \"$regexp\")\n",
       "legendFormat": "{{ instance }} "
      }
     ]
    },
    {
     "title": "FS usage $instance",
     "type": "graph",
     "description": "Tracks usage of disk.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "repeat": "instance",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by(mount)(host_storage_mount_space_used_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})\n/\nsum by (mount)(host_storage_mount_space_total_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})",
       "legendFormat": "{{ mount }}"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ]  CPU&Mem Usage - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU usage $instance",
     "type": "graph",
     "description": "Tracks the usage of CPU by the app in the different typical views.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "repeat": "instance",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(process_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"user\"}[$interval])\n/\nrate(process_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"user\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "User mode"
      },
      {
       "expr": "label_replace(rate(process_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"system\"}[$interval])\n/\nrate(process_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"system\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Kernel mode"
      }
     ]
    },
    {
     "title": "VM CPU usage $instance",
     "type": "graph",
     "description": "Tracks the usage of CPU by the VM in the different typical views.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "repeat": "instance",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"user\"}[$interval])\n/\nrate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"user\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "User mode"
      },
      {
       "expr": "label_replace(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"system\"}[$interval])\n/\nrate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"system\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Kernel mode"
      }
     ]
    },
    {
     "title": "Host Memory $instance",
     "type": "graph",
     "description": "Tracks the total memory available Vs. the amount of used memory.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "repeat": "instance",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(host_memory_used_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Used Memory"
      },
      {
       "expr": "label_replace(host_memory_total_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Total Memory "
      }
     ]
    },
    {
     "title": "Swap Memory $instance",
     "type": "graph",
     "description": "Tracks the total swap memory available Vs. the amount of used swap memory.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
     "repeat": "instance",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(host_swap_used_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Used Swap Memory "
      },
      {
       "expr": "label_replace(host_swap_total_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Total Swap Memory"
      }
     ]
    },
    {
     "title": "Process CPU usage $instance",
     "type": "graph",
     "description": "Tracks the usage of CPU by the app in the different typical views.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(process_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"user\"}[$interval])\n/\nrate(process_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"user\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "User mode"
      },
      {
       "expr": "label_replace(rate(process_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"system\"}[$interval])\n/\nrate(process_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"system\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Kernel mode"
      }
     ]
    },
    {
     "title": "VM CPU usage $instance",
     "type": "graph",
     "description": "Tracks the usage of CPU by the VM in the different typical views.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 27 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"user\"}[$interval])\n/\nrate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"user\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "User mode"
      },
      {
       "expr": "label_replace(rate(host_cpu_usage_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"system\"}[$interval])\n/\nrate(host_cpu_usage_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", mode=\"system\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Kernel mode"
      }
     ]
    },
    {
     "title": "Host Memory $instance",
     "type": "graph",
     "description": "Tracks the total memory available Vs. the amount of used memory.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(host_memory_used_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Used Memory"
      },
      {
       "expr": "label_replace(host_memory_total_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Total Memory "
      }
     ]
    },
    {
     "title": "Swap Memory $instance",
     "type": "graph",
     "description": "Tracks the total swap memory available Vs. the amount of used swap memory.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(host_swap_used_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Used Swap Memory "
      },
      {
       "expr": "label_replace(host_swap_total_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "Total Swap Memory"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Disk&Network Usage - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data transferred $instance",
     "type": "graph",
     "description": "Tracks the amount of data transferred to disk device.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
     "repeat": "instance",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(host_storage_device_data_read_bytes_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "read"
      },
      {
       "expr": "label_replace(rate(host_storage_device_data_write_bytes_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Disk I/O (ops/sec) $instance",
     "type": "graph",
     "description": "Tracks the number of completed disk I/O operations.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
     "repeat": "instance",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(host_storage_device_ops_read_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "read"
      },
      {
       "expr": "label_replace(rate(host_storage_device_ops_write_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Read / Write bandwidth $instance",
     "type": "graph",
     "description": "Tracks incoming and outgoing data through the network interfaces.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
     "repeat": "instance",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(host_network_data_read_bytes_total{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "read {{ interface }}"
      },
      {
       "expr": "label_replace(rate(host_network_packets_write_total{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval]) * -1, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "write {{ interface }}"
      }
     ]
    },
    {
     "title": "Failed Read / Write packets $instance",
     "type": "graph",
     "description": "Tracks incoming and outgoing failed packets on all network interfaces.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
     "repeat": "instance",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(host_network_packets_read_failed_total{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "read {{ interface }}"
      },
      {
       "expr": "label_replace(rate(host_network_packets_write_failed_total{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval]) * -1, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "write {{ interface }}"
      }
     ]
    },
    {
     "title": "Data transferred $instance",
     "type": "graph",
     "description": "Tracks the amount of data transferred to disk device.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(host_storage_device_data_read_bytes_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "read"
      },
      {
       "expr": "label_replace(rate(host_storage_device_data_write_bytes_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Disk I/O (ops/sec) $instance",
     "type": "graph",
     "description": "Tracks the number of completed disk I/O operations.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(host_storage_device_ops_read_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "read"
      },
      {
       "expr": "label_replace(rate(host_storage_device_ops_write_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "Read / Write bandwidth $instance",
     "type": "graph",
     "description": "Tracks incoming and outgoing data through the network interfaces.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(host_network_data_read_bytes_total{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "read {{ interface }}"
      },
      {
       "expr": "label_replace(rate(host_network_packets_write_total{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval]) * -1, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "write {{ interface }}"
      }
     ]
    },
    {
     "title": "Failed Read / Write packets $instance",
     "type": "graph",
     "description": "Tracks incoming and outgoing failed packets on all network interfaces.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "label_replace(rate(host_network_packets_read_failed_total{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval]), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "read {{ interface }}"
      },
      {
       "expr": "label_replace(rate(host_network_packets_write_failed_total{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval]) * -1, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "write {{ interface }}"
      }
     ]
    },
    {
     "title": "System:[  $system  ] Service:[  $service  ] Disk and Network metrics, quantile=$quantile ",
     "type": "table",
     "description": "OS metrics summary table for last $last.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "topk(1,max(host_storage_mount_space_used_bytes{system=~\"$system\", service=~\"$service\", instance=~\"$instance\",mount!~\"$mount\"} / \nhost_storage_mount_space_total_bytes{system=~\"$system\", service=~\"$service\", instance=~\"$instance\",mount!~\"$mount\"}) by (instance,mount)) by (instance)"
      },
      {
       "expr": "max_over_time(max  by(system,instance) (rate(host_storage_device_ops_read_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]))[$last:])"
      },
      {
       "expr": "max_over_time(max  by(system,instance) (rate(host_storage_device_ops_write_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]))[$last:])"
      },
      {
       "expr": "min(delta(host_storage_mount_space_free_bytes{system=~\"$system\", service=~\"$service\", instance=~\"$instance\",mount!~\"$mount\"}[$__range])) by (system,instance)"
      },
      {
       "expr": "max_over_time(max  by(system,instance) (rate(host_storage_device_data_read_bytes_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]))[$last:])"
      },
      {
       "expr": "max_over_time(max  by(system,instance) (rate(host_storage_device_data_write_bytes_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]))[$last:])"
      },
      {
       "expr": "max_over_time(max  by(system,instance) (rate(host_network_data_read_bytes_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]))[$last:])"
      },
      {
       "expr": "max_over_time(max  by(system,instance) (rate(host_network_packets_write_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval]))[$last:])"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Kamon Java  Heap - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Usage MB - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "repeat": "instance",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(jvm_memory_committed_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"heap\"},\"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": " commited"
      },
      {
       "expr": "label_replace(jvm_memory_used_bytes_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"heap\"}\n/\njvm_memory_used_bytes_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"heap\"},\"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": " used"
      }
     ]
    },
    {
     "title": "Heap Usage MB - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(jvm_memory_committed_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"heap\"},\"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": " commited"
      },
      {
       "expr": "label_replace(jvm_memory_used_bytes_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"heap\"}\n/\njvm_memory_used_bytes_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"heap\"},\"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": " used"
      }
     ]
    },
    {
     "title": "Garbage Collection $instance",
     "type": "graph",
     "description": "Tracks the distribution of GC events duration",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "repeat": "instance",
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_seconds_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval])\n/\nrate(jvm_gc_seconds_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "GC count: {{collector}} "
      }
     ]
    },
    {
     "title": "Garbage Collection $instance",
     "type": "graph",
     "description": "Tracks the distribution of GC events duration",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_seconds_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval])\n/\nrate(jvm_gc_seconds_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "GC count: {{collector}} "
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Kamon Java  Off-Heap - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Off-Heap Used",
     "type": "graph",
     "description": "Tracks the amount of memory used by the JVM outside the heap.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(jvm_memory_used_bytes_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", region=\"non-heap\"}\n/\njvm_memory_used_bytes_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", region=\"non-heap\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")\n",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Off-Heap Free",
     "type": "graph",
     "description": "Tracks the amount of memory used by the JVM outside the heap.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace((jvm_memory_free_bytes_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"non-heap\"}\n/\njvm_memory_free_bytes_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"non-heap\"}), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Off-Heap Max",
     "type": "graph",
     "description": "Tracks the amount of memory used by the JVM outside the heap.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(jvm_memory_max_bytes{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", region=\"non-heap\" }, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Off-Heap Commited",
     "type": "graph",
     "description": "Tracks the amount of memory used by the JVM outside the heap.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(jvm_memory_committed_bytes{system=~\"$system\",service=~\"$service\", instance=~\"$instance\", region=\"non-heap\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Java executor Thread count - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "repeat": "instance",
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(executor_threads_total_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval])\n/\nrate(executor_threads_total_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{ name }} ({{ type }})"
      }
     ]
    },
    {
     "title": "Java Thread count - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(executor_threads_total_count{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval])\n/\nrate(executor_threads_total_sum{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{ name }} ({{ type }})"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ]  Executor Metrics - $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Threads",
     "type": "graph",
     "description": "Tracks the number of threads in use.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(executor_threads_total_count{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval])\n/\nrate(executor_threads_total_sum{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{ name }} ({{ type }}) $instance"
      }
     ]
    },
    {
     "title": "Number Of Tasks Completed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(executor_tasks_completed_total{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{ name }} ({{ type }}) $instance"
      }
     ]
    },
    {
     "title": "Queue Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(executor_queue_size_bucket{system=~\"$system\",service=~\"$service\",instance=~\"$instance\", le=\"+Inf\"}[$interval])",
       "legendFormat": "{{ name }} ({{ type }}) $instance"
      }
     ]
    },
    {
     "title": "Maximum Number of Threads",
     "type": "graph",
     "description": "Tracks maximum number of Threads of the executors.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_threads_max{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}",
       "legendFormat": "{{ name }} ({{ type }}) $instance"
      }
     ]
    },
    {
     "title": "Minimum Number of Threads",
     "type": "graph",
     "description": "Tracks minimum number of Threads of the executors.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_threads_min{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}",
       "legendFormat": "{{ name }} ({{ type }}) $instance"
      }
     ]
    },
    {
     "title": "Executor parallelism",
     "type": "graph",
     "description": "Tracks executor parallelism.",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_parallelism{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}",
       "legendFormat": "{{ name }} ({{ type }}) $instance"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "$alertname: count",
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
     "repeat": "alertname",
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
      }
     ]
    },
    {
     "title": "system=[ $system ] , service=[ $service ] current alert list",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "(ALERTS{system=~\"$system\", alertname=~\"$alertname\", severity=~\"$severity\"})"
      }
     ]
    }
   ]
  }
 ]
}