{
 "title": "[TEMPLATE] JMX",
 "description": "Template for JMX  metrics",
 "tags": [
  "template",
  "jmx"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   { "name": "interval", "query": "1m,5m,10m,15m,30m,1h" },
   {
    "name": "system",
    "query": "label_values(jmx_exporter_build_info{},system)"
   },
   {
    "name": "service",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\"},service)"
   },
   {
    "name": "instance",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\",service=~\"$service\"},instance)"
   },
   { "name": "quantile", "query": "0.5,0.6,0.7,0.8,0.9,0.95" },
   {
    "name": "alertname",
    "query": "label_values(ALERTS_FOR_STATE{system=~\"$system\",service=~\"$service\"},alertname)"
   },
   {
    "name": "severity",
    "query": "label_values(ALERTS_FOR_STATE{},severity)"
   },
   { "name": "last", "query": "15m,30m,1h" },
   { "name": "last_h", "query": "8h" },
   {
    "name": "regexp",
    "label": "regexp for FQDN",
    "query": "([a-zA-Z0-9]+-[a-zA-Z0-9]+)[.].+ , (.+)"
   },
   {
    "name": "instance_list",
    "query": "label_values(jmx_exporter_build_info{system=~\"$system\",service=~\"$service\"},instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Readme",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Описание",
     "type": "text",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "\n## Описание дашборда\n\nДанный шаблон отображает основные JMX-метрики собираемые с\n- exporter-jmx\n\nБлоки Summary содержат информацию о всех инстансах сервиса. Остальные блоки фильтруют информацию по полю instance\n\n#### переменные\n- ds - выбор датасорса(prometheus) из которого запрашивать данные для отображения(подробнее про типы прометеусов см https://confluence.ca.sbrf.ru/pages/editpage.action?pageId=2383122863)\n- system - имя системы\n- quantile - значение персентия для расчета значений в таблицах\n- last - период вермени отображения метрик для таблиц(чтобы не делать тяжелые расчеты на больших выборках)\n- regexp for FQDN - regexp для отсекания FQDN имен на графиках (экономия используемого места дашборда)\n- ountpoint != список точек монтирования, которые НЕ интересны для мониторинга(не учитывать в TopK селектах по утилизации файловых систем)\n- raw metric - выбрать метрику для отображения ее в \"сыром\" виде в блоке RAW METRICS (возможность для пользователя посмотрить метрки данного сервиса отсутствующие на дашборде, аналогичный функционал в меню графаны EXPLORE\n\n\n#### drill down links\n- из таблиц возможен переход по имени инстанса на более подробный дашборд по выбранному инстансу\n\n\n\n### Тиражирование\nМожет быть использован как основа дашборда по новым сервисам, при этом ненужные элементы дашборда(графики, таблицы) могут быть удалены.\nНапример оставить график по использовании памяти в %, но удалить график по использовании памяти в GB, т.к. избыточная информация.\nАдминистрато сервиса должен удостовериться и подтвердитьь что присутствуют все необходимые метрики и отсутствуют все мало значимые метрики.\n\n\nТак же можно менять визуализацию лейблов, например: не отображать столбик max/avg на графиках, менять толщину линий и степень заливки, содержание подписей и т.д.\n\nДля систем с более чем 50 хостами - может потребоваться дополнтиельная настройка значений переменных instance и instance_list (дефалтофое значение для выбора All)\n\n#### при тиражировании данное и все остальные описания или удалить или оставить только актуальные комментарии\n\n\n\n"
     }
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] JMX Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Sys CPU% max",
   "type": "stat",
   "description": "$service -  Max  Host system CPU% Utilization over all hosts",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",service=~\"$service\"}) by (system)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Sys Mem Total",
   "type": "stat",
   "description": "$service -  Summary Memory size",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\"})\nby (system)"
    }
   ]
  },
  {
   "title": "JMX Exporters count",
   "type": "stat",
   "description": "Prometheus Jobs for JMX(filter roletype <> null) metrics",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{system=~\"$system\",service=~\"$service\",jmxrole=~\".+\"})"
    }
   ]
  },
  {
   "title": "Java CPU% max",
   "type": "stat",
   "description": "$service -  Max  Java CPU% Utilization over all Java applications",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\"}) by (system)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "GC Time max",
   "type": "stat",
   "description": "$service -  Max  Garbage Collector collection time over all Java applications",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(rate(jmx_java_lang_garbagecollector_collectiontime{system=~\"$system\",service=~\"$service\"}[$interval])) by (system))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Sys Mem% max",
   "type": "stat",
   "description": "$service -  Max  Sys Mem% Utilization over all hosts",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\"} / \non(system,service,jmxrole,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\"})) \nby (system)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Sys Cores Total",
   "type": "stat",
   "description": "$service -  Summary Cores count",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jmx_java_lang_operatingsystem_availableprocessors{system=~\"$system\",service=~\"$service\"})\nby (system)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "JMX Exporters Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{system=~\"$system\",service=~\"$service\",jmxrole=~\".+\"}==1)"
    }
   ]
  },
  {
   "title": "Heap Mem% max",
   "type": "stat",
   "description": "$service -  Max  Java Mem% Utilization over all Java applications",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\"} / jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",service=~\"$service\"}) by (system)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Open File Descriptor max count",
   "type": "stat",
   "description": "$service -  Max  open file descriptor count over all Java applications",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(max(jmx_java_lang_operatingsystem_openfiledescriptorcount{system=~\"$system\",service=~\"$service\"}) by (system))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "System:[  $system  ] Service:[  $service  ] JMX metrics, quantile=$quantile ",
   "type": "table",
   "description": "JMX metrics summary table for last $last.\n\nSys - means host OS metrics.\n\nAggregation(quanlile/max/last)  values during last $last\n\nJava/Heap/Pool - means Java application(service) metrics.\n\nYou can change colors threatholds as you wish\n\n",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": " (max(up{system=~\"$system\",service=~\"$service\",jmxrole=~\".+\"}) by (system,service,jmxrole,instance))"
    },
    {
     "expr": "(min(jmx_java_lang_runtime_uptime{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance))"
    },
    {
     "expr": "(max(jmx_java_lang_operatingsystem_availableprocessors{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance))"
    },
    {
     "expr": "quantile_over_time ($quantile,(max(jmx_java_lang_operatingsystem_systemloadaverage{system=~\"$system\",service=~\"$service\"}) by(system,service,jmxrole,instance))[$__range:])"
    },
    {
     "expr": " quantile_over_time ($quantile,(max(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance))[$__range:])"
    },
    {
     "expr": "quantile_over_time ($quantile,(max(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))[$__range:])"
    },
    {
     "expr": "(max(jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": " max(1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\"} / \non(system,service,jmxrole,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\"})) \nby (system,instance,roletype,service)"
    },
    {
     "expr": "(max(jmx_java_lang_operatingsystem_totalswapspacesize{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance))"
    },
    {
     "expr": "max (1 - (jmx_java_lang_operatingsystem_freeswapspacesize{system=~\"$system\",service=~\"$service\"} / on(system,service,jmxrole,instance)\njmx_java_lang_operatingsystem_totalswapspacesize{system=~\"$system\",service=~\"$service\"})) by (system,service,jmxrole,instance)"
    },
    {
     "expr": "(max(jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": "(max(jmx_java_lang_memory_heapmemoryusage_max{system=~\"$system\",service=~\"$service\"}) by (system,service,roletype,instance))"
    },
    {
     "expr": "quantile_over_time ($quantile,(max(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance))[$__range:])"
    },
    {
     "expr": "quantile_over_time ($quantile,(max(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\"} / jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance))[$__range:])"
    },
    {
     "expr": "(max(jmx_java_lang_memory_nonheapmemoryusage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance))"
    },
    {
     "expr": "max(jmx_java_lang_memory_nonheapmemoryusage_used{system=~\"$system\",service=~\"$service\"} / jmx_java_lang_memory_nonheapmemoryusage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance)"
    },
    {
     "expr": "(max(jmx_java_lang_memorypool_usage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance))"
    },
    {
     "expr": "max(jmx_java_lang_memorypool_usage_used{system=~\"$system\",service=~\"$service\"} / jmx_java_lang_memorypool_usage_committed{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance)"
    },
    {
     "expr": "max_over_time((max(rate(jmx_java_lang_garbagecollector_collectiontime{system=~\"$system\",service=~\"$service\"}[$interval])) by (system,service,jmxrole,instance))[$__range:])"
    },
    {
     "expr": "(max(jmx_java_lang_threading_threadcount{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance))"
    },
    {
     "expr": "(max(jmx_java_lang_operatingsystem_openfiledescriptorcount{system=~\"$system\",service=~\"$service\"}) by (system,service,jmxrole,instance))"
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] JMX Host Systems - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load Avarage Host Systems - [ $instance ]",
     "type": "graph",
     "description": "System metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace(jmx_java_lang_operatingsystem_systemloadaverage{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}  {{ service }}"
      }
     ]
    },
    {
     "title": "CPU Usage % Host Systems - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(jmx_java_lang_operatingsystem_systemcpuload{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }} -{{ service }}"
      }
     ]
    },
    {
     "title": "Memory Usage % Host Systems - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace( (1 - (jmx_java_lang_operatingsystem_freephysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"} / \non(system,service,jmxrole,instance) jmx_java_lang_operatingsystem_totalphysicalmemorysize{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"})) , \"instance\", \"$1\", \"instance\", \"$regexp\")\n",
       "legendFormat": "{{ instance }} -{{ service }}"
      }
     ]
    }
   ]
  },
  {
   "title": "[ $system ] - [ $service ] JMX Java - [ $instance ]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Java Heap Usage % - [ $instance ]",
     "type": "graph",
     "description": "Java metrics over filtered host instances(dashboard variable instance)\n\nsystem=\"$system\"\nservice=\"$service\"",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace( (max(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"} / jmx_java_lang_memory_heapmemoryusage_committed{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}) by (system,service,roletype,instance)) , \"instance\", \"$1\", \"instance\", \"$regexp\")\n",
       "legendFormat": "{{ instance }}-{{ service }}"
      }
     ]
    },
    {
     "title": "Java CPU Usage %  - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "label_replace(jmx_java_lang_operatingsystem_processcpuload{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ service }}"
      }
     ]
    },
    {
     "title": "Java Heap Usage MB - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "label_replace(jmx_java_lang_memory_heapmemoryusage_used{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}, \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ service }}"
      }
     ]
    },
    {
     "title": "Java GC Time - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "label_replace((rate\r\n(jmx_java_lang_garbagecollector_collectiontime{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}[$interval])\r\n), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ service }}"
      }
     ]
    },
    {
     "title": "Java GC count - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace((delta(jmx_java_lang_garbagecollector_collectioncount{system=~\"$system\",service=~\"$service\",instance=~\"$instance\"}[$interval])), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ service }}"
      }
     ]
    },
    {
     "title": "Java Thread count - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace((jmx_java_lang_threading_threadcount{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ service }}"
      }
     ]
    },
    {
     "title": "Java Open File Descriptor count - [ $instance ]",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "label_replace((jmx_java_lang_operatingsystem_openfiledescriptorcount{system=~\"$system\",service=~\"$service\", instance=~\"$instance\"}), \"instance\", \"$1\", \"instance\", \"$regexp\")",
       "legendFormat": "{{ instance }}-{{ service }}"
      }
     ]
    }
   ]
  },
  { "title": "[$system][$service] Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 28 },
   "repeat": "alertname",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "$alertname: count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max(ALERTS{alertstate=\"firing\",system=~\"$system\", service=~\"$service\", alertname=~\"$alertname\"}) by (system,service,instance,alertname)) or vector(0)"
    }
   ]
  },
  {
   "title": "system=[ $system ] , service=[ $service ] current alert list",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "(ALERTS{system=~\"$system\", alertname=~\"$alertname\", severity=~\"$severity\"})"
    }
   ]
  }
 ]
}